//! The Java emitter.
//!
//! Emits one `.java` file per public type plus the three shared boilerplate
//! classes (`ValidationException`, `Violation`, `SpecNumbers`) and one
//! interface per Nexus service. Every model class carries class-level
//! `@JsonDeserialize`/`@JsonSerialize` bound to nested collecting
//! (de)serializers that aggregate `Violation`s into a `ValidationException`
//! (Java §5). JSpecify `@NullMarked` packages; optional/nullable references are
//! `@Nullable`.

use std::path::PathBuf;

use nex_gen_core::{Emitter, EmittedFile, IR, Language, Result, Service};

use crate::emit::{PackageInfo, as_map, as_record, services, symbol_name, type_symbols};
use crate::ir::{Additional, Field, FieldType, Kind, MapType, Record, Scalar};
use crate::naming;

pub fn emitter(pkg: PackageInfo) -> Box<dyn Emitter<Kind>> {
    Box::new(JavaEmitter { pkg })
}

struct JavaEmitter {
    pkg: PackageInfo,
}

impl Emitter<Kind> for JavaEmitter {
    fn language(&self) -> Language {
        Language::Java
    }

    fn emit(&self, ir: &IR<Kind>) -> Result<Vec<EmittedFile>> {
        let pkg = &self.pkg.java_package;
        let mut files = Vec::new();

        files.push(self.file("ValidationException", validation_exception(pkg)));
        files.push(self.file("Violation", violation(pkg)));
        files.push(self.file("SpecNumbers", spec_numbers(pkg)));

        for symbol in type_symbols(ir) {
            let name = naming::type_ident(symbol.name.as_str(), Language::Java, &Default::default());
            let body = if let Some(record) = as_record(symbol) {
                render_record(ir, pkg, &name, record)
            } else if let Some(map) = as_map(symbol) {
                render_map(pkg, &name, map)
            } else {
                continue;
            };
            files.push(self.file(&name, body));
        }

        for svc in services(ir) {
            let name = naming::type_ident(svc.name.as_str(), Language::Java, &Default::default());
            files.push(self.file(&name, render_service(ir, pkg, svc)));
        }

        Ok(files)
    }
}

impl JavaEmitter {
    fn file(&self, class: &str, body: String) -> EmittedFile {
        let dir = self.pkg.java_package.replace('.', "/");
        EmittedFile {
            path: PathBuf::from(format!("{dir}/{class}.java")),
            body,
        }
    }
}

const HEADER: &str = "// Generated by nex-gen. DO NOT EDIT!\n";

// ---------------------------------------------------------------------------
// Java type mapping.
// ---------------------------------------------------------------------------

fn java_type(ir: &IR<Kind>, ty: &FieldType) -> String {
    match ty {
        FieldType::String => "String".to_string(),
        FieldType::Integer => "Long".to_string(),
        FieldType::Number => "Double".to_string(),
        FieldType::Boolean => "Boolean".to_string(),
        FieldType::Array(inner) => format!("List<{}>", java_type(ir, inner)),
        FieldType::Ref(id) => {
            naming::type_ident(symbol_name(ir, *id), Language::Java, &Default::default())
        }
    }
}

/// A field's declared class name (const fields get their own nested value class).
fn field_class(field: &Field) -> Option<String> {
    if matches!(field.constant, Some(Scalar::String(_))) && matches!(field.ty, FieldType::String) {
        Some(naming::type_ident(&field.json_name, Language::Java, &field.overrides))
    } else {
        None
    }
}

fn field_ident(field: &Field) -> String {
    naming::field_ident(&field.json_name, Language::Java, &field.overrides)
}

// ---------------------------------------------------------------------------
// Records.
// ---------------------------------------------------------------------------

fn render_record(ir: &IR<Kind>, pkg: &str, name: &str, record: &Record) -> String {
    let open = matches!(record.additional, Additional::Open);
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');
    out.push_str(&format!("package {pkg};\n\n"));
    out.push_str(&model_imports(record, open));
    out.push('\n');
    push_doc(&mut out, record.docs.as_deref(), "");
    out.push_str("@NullMarked\n");
    out.push_str(&format!("@JsonDeserialize(using = {name}.Deserializer.class)\n"));
    out.push_str(&format!("@JsonSerialize(using = {name}.Serializer.class)\n"));
    out.push_str(&format!("public final class {name} {{\n"));

    if open {
        let names: Vec<String> = record
            .fields
            .iter()
            .map(|f| format!("\"{}\"", f.json_name))
            .collect();
        out.push_str(&format!(
            "  private static final java.util.Set<String> DECLARED =\n      new java.util.HashSet<>(java.util.Arrays.asList({}));\n\n",
            names.join(", ")
        ));
    }

    for field in &record.fields {
        if let Some(cls) = field_class(field) {
            if let Some(Scalar::String(value)) = &field.constant {
                out.push_str(&value_class(&cls, value));
            }
        }
    }

    for field in &record.fields {
        let ident = field_ident(field);
        if let Some(cls) = field_class(field) {
            let value = const_value_name(field);
            out.push_str(&format!("  private final {cls} {ident} = {cls}.{value};\n"));
        } else {
            let ty = java_type(ir, &field.ty);
            let nullable = !field.required || field.nullable;
            let ann = if nullable { "@Nullable " } else { "" };
            out.push_str(&format!("  private final {ann}{ty} {ident};\n"));
        }
    }
    if open {
        out.push_str("  private final Map<String, Object> additionalProperties;\n");
    }
    out.push('\n');

    let ctor_params = ctor_params(ir, record, open);
    out.push_str(&format!("  public {name}({}) {{\n", ctor_params.join(", ")));
    for field in &record.fields {
        if field_class(field).is_some() {
            continue;
        }
        let ident = field_ident(field);
        out.push_str(&format!("    this.{ident} = {ident};\n"));
    }
    if open {
        out.push_str("    this.additionalProperties = additionalProperties;\n");
    }
    out.push_str("  }\n\n");

    for field in &record.fields {
        let ident = field_ident(field);
        let getter = format!("get{}", pascal(&ident));
        push_doc(&mut out, field.docs.as_deref(), "  ");
        if let Some(cls) = field_class(field) {
            out.push_str(&format!("  public {cls} {getter}() {{\n    return {ident};\n  }}\n\n"));
        } else if let Some(default) = &field.default {
            let (ret, expr) = default_getter(ir, field, default);
            out.push_str(&format!("  public {ret} {getter}() {{\n    return {expr};\n  }}\n\n"));
        } else {
            let ty = java_type(ir, &field.ty);
            let nullable = !field.required || field.nullable;
            let ann = if nullable { "@Nullable " } else { "" };
            out.push_str(&format!("  public {ann}{ty} {getter}() {{\n    return {ident};\n  }}\n\n"));
        }
    }
    if open {
        out.push_str("  /** Undeclared members preserved verbatim for forward compatibility. */\n");
        out.push_str("  public Map<String, Object> getAdditionalProperties() {\n    return Collections.unmodifiableMap(additionalProperties);\n  }\n\n");
    }

    out.push_str(&record_deserializer(ir, name, record, open));
    out.push('\n');
    out.push_str(&record_serializer(ir, name, record, open));

    out.push_str("}\n");
    out
}

fn ctor_params(ir: &IR<Kind>, record: &Record, open: bool) -> Vec<String> {
    let mut params = Vec::new();
    for field in &record.fields {
        if field_class(field).is_some() {
            continue;
        }
        let ty = java_type(ir, &field.ty);
        let ident = field_ident(field);
        let nullable = !field.required || field.nullable;
        let ann = if nullable { "@Nullable " } else { "" };
        params.push(format!("{ann}{ty} {ident}"));
    }
    if open {
        params.push("Map<String, Object> additionalProperties".to_string());
    }
    params
}

fn const_value_name(field: &Field) -> String {
    match &field.constant {
        Some(Scalar::String(s)) => s.to_uppercase().replace(|c: char| !c.is_alphanumeric(), "_"),
        _ => "VALUE".to_string(),
    }
}

fn default_getter(ir: &IR<Kind>, field: &Field, default: &Scalar) -> (String, String) {
    let ident = field_ident(field);
    match (&field.ty, default) {
        (FieldType::Integer, Scalar::Integer(v)) => {
            ("long".to_string(), format!("{ident} != null ? {ident} : {v}L"))
        }
        (FieldType::Number, Scalar::Number(v)) => {
            ("double".to_string(), format!("{ident} != null ? {ident} : {v}"))
        }
        (FieldType::Boolean, Scalar::Boolean(v)) => {
            ("boolean".to_string(), format!("{ident} != null ? {ident} : {v}"))
        }
        (FieldType::String, Scalar::String(v)) => (
            "String".to_string(),
            format!("{ident} != null ? {ident} : \"{v}\""),
        ),
        _ => (java_type(ir, &field.ty), ident),
    }
}

fn value_class(cls: &str, value: &str) -> String {
    let upper = value.to_uppercase().replace(|c: char| !c.is_alphanumeric(), "_");
    format!(
        r#"  /**
   * Open value class for the discriminator (const "{value}"). Any wire value is
   * representable for forward compatibility; the validator rejects anything but
   * {{@link #{upper}}} because a const is a closed contract.
   */
  public static final class {cls} {{
    public static final {cls} {upper} = new {cls}("{value}");

    private final String value;

    private {cls}(String value) {{
      this.value = value;
    }}

    @JsonCreator
    public static @Nullable {cls} fromString(@Nullable String v) {{
      if (v == null) {{
        return null;
      }}
      if (v.equals("{value}")) {{
        return {upper};
      }}
      return new {cls}(v);
    }}

    @JsonValue
    public String getValue() {{
      return value;
    }}

    public boolean isUnrecognized() {{
      return this != {upper};
    }}

    @Override
    public boolean equals(@Nullable Object o) {{
      return o instanceof {cls} && value.equals((({cls}) o).value);
    }}

    @Override
    public int hashCode() {{
      return value.hashCode();
    }}

    @Override
    public String toString() {{
      return value;
    }}
  }}

"#
    )
}

fn record_deserializer(ir: &IR<Kind>, name: &str, record: &Record, open: bool) -> String {
    let mut out = String::new();
    out.push_str(&format!("  public static final class Deserializer extends JsonDeserializer<{name}> {{\n"));
    out.push_str("    @Override\n");
    out.push_str(&format!("    public {name} deserialize(JsonParser p, DeserializationContext ctx) throws IOException {{\n"));
    out.push_str("      JsonNode root = p.readValueAsTree();\n");
    out.push_str("      List<Violation> errs = new ArrayList<>();\n\n");

    for field in &record.fields {
        out.push_str(&deser_field(ir, field));
        out.push('\n');
    }

    if open {
        out.push_str("      Map<String, Object> extra = new LinkedHashMap<>();\n");
        out.push_str("      Iterator<Map.Entry<String, JsonNode>> extraIt = root.fields();\n");
        out.push_str("      while (extraIt.hasNext()) {\n");
        out.push_str("        Map.Entry<String, JsonNode> e = extraIt.next();\n");
        out.push_str("        if (!DECLARED.contains(e.getKey())) {\n");
        out.push_str("          extra.put(e.getKey(), ctx.readTreeAsValue(e.getValue(), Object.class));\n");
        out.push_str("        }\n      }\n\n");
    } else if matches!(record.additional, Additional::Closed) {
        let names: Vec<String> = record
            .fields
            .iter()
            .map(|f| format!("!key.equals(\"{}\")", f.json_name))
            .collect();
        out.push_str("      Iterator<String> keyIt = root.fieldNames();\n");
        out.push_str("      while (keyIt.hasNext()) {\n");
        out.push_str("        String key = keyIt.next();\n");
        if names.is_empty() {
            out.push_str("        errs.add(new Violation(key, \"unknown field\"));\n");
        } else {
            out.push_str(&format!("        if ({}) {{\n", names.join(" && ")));
            out.push_str("          errs.add(new Violation(key, \"unknown field\"));\n        }\n");
        }
        out.push_str("      }\n\n");
    }

    out.push_str("      if (!errs.isEmpty()) {\n        throw new ValidationException(p, errs);\n      }\n");
    let args = ctor_args(record, open);
    out.push_str(&format!("      return new {name}({});\n", args.join(", ")));
    out.push_str("    }\n  }\n");
    out
}

fn ctor_args(record: &Record, open: bool) -> Vec<String> {
    let mut args = Vec::new();
    for field in &record.fields {
        if field_class(field).is_some() {
            continue;
        }
        let ident = field_ident(field);
        if field.required && !field.nullable {
            args.push(format!("Objects.requireNonNull({ident})"));
        } else {
            args.push(ident);
        }
    }
    if open {
        args.push("extra".to_string());
    }
    args
}

fn deser_field(ir: &IR<Kind>, field: &Field) -> String {
    let ident = field_ident(field);
    let json = &field.json_name;
    let node = format!("{ident}Node");

    if let Some(cls) = field_class(field) {
        if let Some(Scalar::String(value)) = &field.constant {
            return format!(
                "      JsonNode {node} = root.get(\"{json}\");\n\
                 \x20     if ({node} == null || {node}.isNull()) {{\n\
                 \x20       errs.add(new Violation(\"{json}\", \"required\"));\n\
                 \x20     }} else if (!{node}.isTextual()) {{\n\
                 \x20       errs.add(new Violation(\"{json}\", \"expected string\"));\n\
                 \x20     }} else {{\n\
                 \x20       {cls} k = {cls}.fromString({node}.asText());\n\
                 \x20       if (k == null || k.isUnrecognized()) {{\n\
                 \x20         errs.add(new Violation(\"{json}\", \"const: expected \\\"{value}\\\"\"));\n\
                 \x20       }}\n\
                 \x20     }}\n"
            );
        }
    }

    match &field.ty {
        FieldType::String => deser_string(field, &ident, json, &node),
        FieldType::Integer => deser_integer(field, &ident, json, &node),
        FieldType::Number => {
            deser_generic_number(field, &ident, json, &node, "Double", "isNumber", "doubleValue")
        }
        FieldType::Boolean => deser_bool(field, &ident, json, &node),
        FieldType::Array(inner) => deser_array(ir, field, inner, &ident, json, &node),
        FieldType::Ref(id) => {
            let cls = naming::type_ident(symbol_name(ir, *id), Language::Java, &Default::default());
            deser_ref(field, &cls, &ident, json, &node)
        }
    }
}

fn deser_string(field: &Field, ident: &str, json: &str, node: &str) -> String {
    let mut out = format!("      String {ident} = null;\n");
    out.push_str(&format!("      JsonNode {node} = root.get(\"{json}\");\n"));
    if field.required && !field.nullable {
        out.push_str(&format!("      if ({node} == null || {node}.isNull()) {{\n        errs.add(new Violation(\"{json}\", \"required\"));\n      }} else if (!{node}.isTextual()) {{\n        errs.add(new Violation(\"{json}\", \"expected string\"));\n      }} else {{\n        {ident} = {node}.asText();\n      }}\n"));
    } else if field.required && field.nullable {
        out.push_str(&format!("      if ({node} == null) {{\n        errs.add(new Violation(\"{json}\", \"required\"));\n      }} else if (!{node}.isNull()) {{\n        if (!{node}.isTextual()) {{\n          errs.add(new Violation(\"{json}\", \"expected string\"));\n        }} else {{\n          {ident} = {node}.asText();\n        }}\n      }}\n"));
    } else if !field.nullable {
        out.push_str(&format!("      if ({node} != null) {{\n        if ({node}.isNull()) {{\n          errs.add(new Violation(\"{json}\", \"explicit null not allowed\"));\n        }} else if (!{node}.isTextual()) {{\n          errs.add(new Violation(\"{json}\", \"expected string\"));\n        }} else {{\n          {ident} = {node}.asText();\n        }}\n      }}\n"));
    } else {
        out.push_str(&format!("      if ({node} != null && !{node}.isNull()) {{\n        if (!{node}.isTextual()) {{\n          errs.add(new Violation(\"{json}\", \"expected string\"));\n        }} else {{\n          {ident} = {node}.asText();\n        }}\n      }}\n"));
    }
    out
}

fn deser_integer(field: &Field, ident: &str, json: &str, node: &str) -> String {
    let mut out = format!("      Long {ident} = null;\n");
    out.push_str(&format!("      JsonNode {node} = root.get(\"{json}\");\n"));
    if field.required && !field.nullable {
        out.push_str(&format!("      if ({node} == null || {node}.isNull()) {{\n        errs.add(new Violation(\"{json}\", \"required\"));\n      }} else {{\n        {ident} = SpecNumbers.specLong({node}, \"{json}\", errs);\n      }}\n"));
    } else if !field.nullable {
        out.push_str(&format!("      if ({node} != null) {{\n        if ({node}.isNull()) {{\n          errs.add(new Violation(\"{json}\", \"explicit null not allowed\"));\n        }} else {{\n          {ident} = SpecNumbers.specLong({node}, \"{json}\", errs);\n        }}\n      }}\n"));
    } else {
        out.push_str(&format!("      if ({node} != null && !{node}.isNull()) {{\n        {ident} = SpecNumbers.specLong({node}, \"{json}\", errs);\n      }}\n"));
    }
    out
}

fn deser_generic_number(
    field: &Field,
    ident: &str,
    json: &str,
    node: &str,
    ty: &str,
    check: &str,
    getter: &str,
) -> String {
    let mut out = format!("      {ty} {ident} = null;\n");
    out.push_str(&format!("      JsonNode {node} = root.get(\"{json}\");\n"));
    let assign = format!("{ident} = {node}.{getter}();");
    if field.required && !field.nullable {
        out.push_str(&format!("      if ({node} == null || {node}.isNull()) {{\n        errs.add(new Violation(\"{json}\", \"required\"));\n      }} else if (!{node}.{check}()) {{\n        errs.add(new Violation(\"{json}\", \"expected number\"));\n      }} else {{\n        {assign}\n      }}\n"));
    } else {
        out.push_str(&format!("      if ({node} != null && !{node}.isNull()) {{\n        if (!{node}.{check}()) {{\n          errs.add(new Violation(\"{json}\", \"expected number\"));\n        }} else {{\n          {assign}\n        }}\n      }}\n"));
    }
    out
}

fn deser_bool(field: &Field, ident: &str, json: &str, node: &str) -> String {
    let mut out = format!("      Boolean {ident} = null;\n");
    out.push_str(&format!("      JsonNode {node} = root.get(\"{json}\");\n"));
    if field.required && !field.nullable {
        out.push_str(&format!("      if ({node} == null || {node}.isNull()) {{\n        errs.add(new Violation(\"{json}\", \"required\"));\n      }} else if (!{node}.isBoolean()) {{\n        errs.add(new Violation(\"{json}\", \"expected boolean\"));\n      }} else {{\n        {ident} = {node}.asBoolean();\n      }}\n"));
    } else {
        out.push_str(&format!("      if ({node} != null && !{node}.isNull()) {{\n        if (!{node}.isBoolean()) {{\n          errs.add(new Violation(\"{json}\", \"expected boolean\"));\n        }} else {{\n          {ident} = {node}.asBoolean();\n        }}\n      }}\n"));
    }
    out
}

fn deser_array(
    ir: &IR<Kind>,
    _field: &Field,
    inner: &FieldType,
    ident: &str,
    json: &str,
    node: &str,
) -> String {
    let elem_ty = java_type(ir, inner);
    let mut out = format!("      List<{elem_ty}> {ident} = null;\n");
    out.push_str(&format!("      JsonNode {node} = root.get(\"{json}\");\n"));
    out.push_str(&format!("      if ({node} != null && !{node}.isNull()) {{\n"));
    out.push_str(&format!("        if (!{node}.isArray()) {{\n          errs.add(new Violation(\"{json}\", \"expected array\"));\n        }} else {{\n"));
    out.push_str(&format!("          {ident} = new ArrayList<>();\n"));
    out.push_str(&format!("          for (int i = 0; i < {node}.size(); i++) {{\n            JsonNode item = {node}.get(i);\n"));
    match inner {
        FieldType::String => {
            out.push_str(&format!("            if (!item.isTextual()) {{\n              errs.add(new Violation(\"{json}[\" + i + \"]\", \"expected string\"));\n            }} else {{\n              {ident}.add(item.asText());\n            }}\n"));
        }
        _ => {
            out.push_str(&format!("            {ident}.add(ctx.readTreeAsValue(item, {elem_ty}.class));\n"));
        }
    }
    out.push_str("          }\n        }\n      }\n");
    out
}

fn deser_ref(field: &Field, cls: &str, ident: &str, json: &str, node: &str) -> String {
    let mut out = format!("      {cls} {ident} = null;\n");
    out.push_str(&format!("      JsonNode {node} = root.get(\"{json}\");\n"));
    let body = format!(
        "        try {{\n          {ident} = ctx.readTreeAsValue({node}, {cls}.class);\n        }} catch (ValidationException nested) {{\n          for (Violation v : nested.getViolations()) {{\n            errs.add(new Violation(\"{json}.\" + v.getPath(), v.getReason()));\n          }}\n        }}\n"
    );
    if field.required && !field.nullable {
        out.push_str(&format!("      if ({node} == null || {node}.isNull()) {{\n        errs.add(new Violation(\"{json}\", \"required\"));\n      }} else {{\n{body}      }}\n"));
    } else {
        out.push_str(&format!("      if ({node} != null && !{node}.isNull()) {{\n{body}      }}\n"));
    }
    out
}

fn record_serializer(ir: &IR<Kind>, name: &str, record: &Record, open: bool) -> String {
    let mut out = String::new();
    out.push_str(&format!("  public static final class Serializer extends JsonSerializer<{name}> {{\n"));
    out.push_str("    @Override\n");
    out.push_str(&format!("    public void serialize({name} v, JsonGenerator gen, SerializerProvider sp) throws IOException {{\n"));
    out.push_str("      List<Violation> errs = new ArrayList<>();\n");
    for field in &record.fields {
        if field_class(field).is_some() {
            continue;
        }
        if field.required && !field.nullable {
            out.push_str(&format!("      if (v.{} == null) {{\n        errs.add(new Violation(\"{}\", \"required\"));\n      }}\n", field_ident(field), field.json_name));
        }
    }
    out.push_str("      if (!errs.isEmpty()) {\n        throw new ValidationException(null, errs);\n      }\n\n");
    out.push_str("      gen.writeStartObject();\n");
    for field in &record.fields {
        out.push_str(&ser_field(ir, field));
    }
    if open {
        out.push_str("      for (Map.Entry<String, Object> e : v.additionalProperties.entrySet()) {\n");
        out.push_str("        gen.writeFieldName(e.getKey());\n        sp.defaultSerializeValue(e.getValue(), gen);\n      }\n");
    }
    out.push_str("      gen.writeEndObject();\n");
    out.push_str("    }\n  }\n");
    out
}

fn ser_field(ir: &IR<Kind>, field: &Field) -> String {
    let ident = field_ident(field);
    let json = &field.json_name;

    if field_class(field).is_some() {
        return format!("      gen.writeStringField(\"{json}\", v.{ident}.getValue());\n");
    }

    match &field.ty {
        FieldType::String => {
            if field.required && field.nullable {
                format!("      if (v.{ident} == null) {{\n        gen.writeNullField(\"{json}\");\n      }} else {{\n        gen.writeStringField(\"{json}\", v.{ident});\n      }}\n")
            } else if field.required {
                format!("      gen.writeStringField(\"{json}\", v.{ident});\n")
            } else {
                format!("      if (v.{ident} != null) {{\n        gen.writeStringField(\"{json}\", v.{ident});\n      }}\n")
            }
        }
        FieldType::Integer | FieldType::Number => {
            if field.required && !field.nullable {
                format!("      gen.writeNumberField(\"{json}\", v.{ident});\n")
            } else {
                format!("      if (v.{ident} != null) {{\n        gen.writeNumberField(\"{json}\", v.{ident});\n      }}\n")
            }
        }
        FieldType::Boolean => {
            if field.required && !field.nullable {
                format!("      gen.writeBooleanField(\"{json}\", v.{ident});\n")
            } else {
                format!("      if (v.{ident} != null) {{\n        gen.writeBooleanField(\"{json}\", v.{ident});\n      }}\n")
            }
        }
        FieldType::Array(inner) => {
            let _ = ir;
            let body = match inner.as_ref() {
                FieldType::String => format!("        for (String m : v.{ident}) {{\n          gen.writeString(m);\n        }}\n"),
                _ => format!("        for (Object m : v.{ident}) {{\n          sp.defaultSerializeValue(m, gen);\n        }}\n"),
            };
            format!("      if (v.{ident} != null) {{\n        gen.writeArrayFieldStart(\"{json}\");\n{body}        gen.writeEndArray();\n      }}\n")
        }
        FieldType::Ref(_) => {
            let inner = format!("        gen.writeFieldName(\"{json}\");\n        sp.defaultSerializeValue(v.{ident}, gen);\n");
            if field.required && !field.nullable {
                inner
            } else {
                format!("      if (v.{ident} != null) {{\n{inner}      }}\n")
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Typed map wrapper.
// ---------------------------------------------------------------------------

fn render_map(pkg: &str, name: &str, map: &MapType) -> String {
    let value_ty = "String";
    let max = map.max_properties;
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');
    out.push_str(&format!("package {pkg};\n\n"));
    out.push_str(&map_imports());
    out.push('\n');
    push_doc(&mut out, map.docs.as_deref(), "");
    out.push_str("@NullMarked\n");
    out.push_str(&format!("@JsonDeserialize(using = {name}.Deserializer.class)\n"));
    out.push_str(&format!("@JsonSerialize(using = {name}.Serializer.class)\n"));
    out.push_str(&format!("public final class {name} {{\n"));
    if let Some(max) = max {
        out.push_str(&format!("  private static final int MAX_PROPERTIES = {max};\n\n"));
    }
    out.push_str(&format!("  private final Map<String, {value_ty}> additionalProperties;\n\n"));
    out.push_str(&format!("  public {name}(Map<String, {value_ty}> additionalProperties) {{\n    this.additionalProperties = additionalProperties;\n  }}\n\n"));
    out.push_str(&format!("  public Map<String, {value_ty}> getAdditionalProperties() {{\n    return Collections.unmodifiableMap(additionalProperties);\n  }}\n\n"));

    out.push_str(&format!("  public static final class Deserializer extends JsonDeserializer<{name}> {{\n"));
    out.push_str("    @Override\n");
    out.push_str(&format!("    public {name} deserialize(JsonParser p, DeserializationContext ctx) throws IOException {{\n"));
    out.push_str("      JsonNode root = p.readValueAsTree();\n      List<Violation> errs = new ArrayList<>();\n");
    out.push_str(&format!("      Map<String, {value_ty}> map = new LinkedHashMap<>();\n"));
    out.push_str("      Iterator<Map.Entry<String, JsonNode>> it = root.fields();\n");
    out.push_str("      while (it.hasNext()) {\n        Map.Entry<String, JsonNode> e = it.next();\n        JsonNode val = e.getValue();\n");
    out.push_str("        if (!val.isTextual()) {\n          errs.add(new Violation(e.getKey(), \"expected string\"));\n        } else {\n          map.put(e.getKey(), val.asText());\n        }\n      }\n");
    if let Some(max) = max {
        out.push_str(&format!("      if (map.size() > MAX_PROPERTIES) {{\n        errs.add(new Violation(\"\", \"maxProperties: at most {max} entries\"));\n      }}\n"));
    }
    out.push_str("      if (!errs.isEmpty()) {\n        throw new ValidationException(p, errs);\n      }\n");
    out.push_str(&format!("      return new {name}(map);\n    }}\n  }}\n\n"));

    out.push_str(&format!("  public static final class Serializer extends JsonSerializer<{name}> {{\n"));
    out.push_str("    @Override\n");
    out.push_str(&format!("    public void serialize({name} v, JsonGenerator gen, SerializerProvider sp) throws IOException {{\n"));
    if let Some(max) = max {
        out.push_str(&format!("      if (v.additionalProperties.size() > MAX_PROPERTIES) {{\n        throw new ValidationException(\n            null,\n            List.of(new Violation(\"\", \"maxProperties: at most {max} entries\")));\n      }}\n"));
    }
    out.push_str("      gen.writeStartObject();\n");
    out.push_str(&format!("      for (Map.Entry<String, {value_ty}> e : v.additionalProperties.entrySet()) {{\n        gen.writeStringField(e.getKey(), e.getValue());\n      }}\n"));
    out.push_str("      gen.writeEndObject();\n    }\n  }\n");
    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------------
// Service interface.
// ---------------------------------------------------------------------------

fn render_service(ir: &IR<Kind>, pkg: &str, svc: &Service) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');
    out.push_str(&format!("package {pkg};\n\n"));
    out.push_str("import io.nexusrpc.Operation;\nimport io.nexusrpc.Service;\nimport org.jspecify.annotations.NullMarked;\n\n");
    push_doc(&mut out, svc.docs.as_deref(), "");
    out.push_str("@NullMarked\n");
    out.push_str(&format!("@Service(name = \"{}\")\n", svc.wire_name));
    let name = naming::type_ident(svc.name.as_str(), Language::Java, &Default::default());
    out.push_str(&format!("public interface {name} {{\n"));
    for op in &svc.operations {
        push_doc(&mut out, op.docs.as_deref(), "  ");
        out.push_str(&format!("  @Operation(name = \"{}\")\n", op.wire_name));
        let method = naming::field_ident(op.name.as_str(), Language::Java, &Default::default());
        let ret = op
            .output
            .map(|id| naming::type_ident(symbol_name(ir, id), Language::Java, &Default::default()))
            .unwrap_or_else(|| "void".to_string());
        match op.input {
            Some(id) => {
                let input =
                    naming::type_ident(symbol_name(ir, id), Language::Java, &Default::default());
                out.push_str(&format!("  {ret} {method}({input} input);\n\n"));
            }
            None => out.push_str(&format!("  {ret} {method}();\n\n")),
        }
    }
    while out.ends_with("\n\n") {
        out.pop();
    }
    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------------
// Imports & doc helpers.
// ---------------------------------------------------------------------------

fn model_imports(record: &Record, open: bool) -> String {
    let mut imports = vec![
        "com.fasterxml.jackson.core.JsonGenerator",
        "com.fasterxml.jackson.core.JsonParser",
        "com.fasterxml.jackson.databind.DeserializationContext",
        "com.fasterxml.jackson.databind.JsonDeserializer",
        "com.fasterxml.jackson.databind.JsonNode",
        "com.fasterxml.jackson.databind.JsonSerializer",
        "com.fasterxml.jackson.databind.SerializerProvider",
        "com.fasterxml.jackson.databind.annotation.JsonDeserialize",
        "com.fasterxml.jackson.databind.annotation.JsonSerialize",
        "java.io.IOException",
        "java.util.ArrayList",
        "java.util.Iterator",
        "java.util.List",
        "java.util.Objects",
        "org.jspecify.annotations.NullMarked",
        "org.jspecify.annotations.Nullable",
    ];
    let has_const = record.fields.iter().any(|f| field_class(f).is_some());
    if has_const {
        imports.push("com.fasterxml.jackson.annotation.JsonCreator");
        imports.push("com.fasterxml.jackson.annotation.JsonValue");
    }
    if open {
        imports.push("java.util.Collections");
        imports.push("java.util.LinkedHashMap");
        imports.push("java.util.Map");
    }
    imports.sort();
    imports.iter().map(|i| format!("import {i};\n")).collect()
}

fn map_imports() -> String {
    let mut imports = vec![
        "com.fasterxml.jackson.core.JsonGenerator",
        "com.fasterxml.jackson.core.JsonParser",
        "com.fasterxml.jackson.databind.DeserializationContext",
        "com.fasterxml.jackson.databind.JsonDeserializer",
        "com.fasterxml.jackson.databind.JsonNode",
        "com.fasterxml.jackson.databind.JsonSerializer",
        "com.fasterxml.jackson.databind.SerializerProvider",
        "com.fasterxml.jackson.databind.annotation.JsonDeserialize",
        "com.fasterxml.jackson.databind.annotation.JsonSerialize",
        "java.io.IOException",
        "java.util.ArrayList",
        "java.util.Collections",
        "java.util.Iterator",
        "java.util.LinkedHashMap",
        "java.util.List",
        "java.util.Map",
        "org.jspecify.annotations.NullMarked",
    ];
    imports.sort();
    imports.iter().map(|i| format!("import {i};\n")).collect()
}

fn push_doc(out: &mut String, docs: Option<&str>, indent: &str) {
    let Some(docs) = docs else {
        return;
    };
    let docs = docs.trim();
    if docs.is_empty() {
        return;
    }
    out.push_str(&format!("{indent}/** {docs} */\n"));
}

fn pascal(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

// ---------------------------------------------------------------------------
// Shared boilerplate (fixed strings, package substituted).
// ---------------------------------------------------------------------------

fn validation_exception(pkg: &str) -> String {
    format!(
        r#"{HEADER}
package {pkg};

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.JsonMappingException;
import java.util.Collections;
import java.util.List;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * Aggregated validation failure thrown by a generated collecting
 * (de)serializer. Holds every {{@link Violation}} found while binding or
 * emitting a single payload.
 */
@NullMarked
public final class ValidationException extends JsonMappingException {{
  private final List<Violation> violations;

  public ValidationException(@Nullable JsonParser p, List<Violation> violations) {{
    super(p, summarize(violations));
    this.violations = Collections.unmodifiableList(violations);
  }}

  public List<Violation> getViolations() {{
    return violations;
  }}

  private static String summarize(List<Violation> violations) {{
    StringBuilder sb = new StringBuilder(violations.size() + " validation error(s):");
    for (Violation v : violations) {{
      sb.append("\n  ").append(v);
    }}
    return sb.toString();
  }}
}}
"#
    )
}

fn violation(pkg: &str) -> String {
    format!(
        r#"{HEADER}
package {pkg};

import org.jspecify.annotations.NullMarked;

/**
 * A single constraint violation, carrying the JSON-pointer-style path to the
 * offending member and a human-readable reason.
 */
@NullMarked
public final class Violation {{
  private final String path;
  private final String reason;

  public Violation(String path, String reason) {{
    this.path = path;
    this.reason = reason;
  }}

  public String getPath() {{
    return path;
  }}

  public String getReason() {{
    return reason;
  }}

  @Override
  public String toString() {{
    return path + ": " + reason;
  }}
}}
"#
    )
}

fn spec_numbers(pkg: &str) -> String {
    format!(
        r#"{HEADER}
package {pkg};

import com.fasterxml.jackson.databind.JsonNode;
import java.math.BigDecimal;
import java.util.List;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * Spec-strict numeric helpers shared by every generated collecting
 * deserializer.
 */
@NullMarked
final class SpecNumbers {{
  private SpecNumbers() {{}}

  /** Cross-language integer cap: 2^53 - 1 (== JS Number.MAX_SAFE_INTEGER). */
  static final long CAP = 9007199254740991L;

  static @Nullable Long specLong(JsonNode n, String path, List<Violation> errs) {{
    if (!n.isNumber()) {{
      errs.add(new Violation(path, "expected integer"));
      return null;
    }}
    BigDecimal d = n.decimalValue();
    if (d.stripTrailingZeros().scale() > 0) {{
      errs.add(new Violation(path, "not an integer"));
      return null;
    }}
    if (d.abs().compareTo(BigDecimal.valueOf(CAP)) > 0) {{
      errs.add(new Violation(path, "integer exceeds +/-(2^53-1) cap"));
      return null;
    }}
    return d.longValueExact();
  }}
}}
"#
    )
}
