//! Emit-tier types: the placement key and emitted files.
//!
//! These are computed per language by an [`Emitter`](crate::Emitter). `module`
//! is the placement key that drives which file a symbol lands in;
//! [`EmittedFile`] is one rendered file, including its import block (each
//! emitter renders its own imports via the per-language
//! [`render`](crate::render) helpers).

use std::path::PathBuf;

// `Module` is defined here (not in `ir`) because placement is an emit-tier
// concern — it is computed by the emitter, not produced by the loader.

/// A placement key: which logical module/file group a symbol belongs to.
///
/// `module` comparison drives placement (same module => same file). For a
/// first-party symbol this is the target module path; for a **foreign**
/// reference (a type that lives in a module generated by some other tool) it is
/// the foreign module.
#[derive(Clone, Debug, Eq, PartialEq, Hash, Ord, PartialOrd)]
pub struct Module(pub String);

impl Module {
    pub fn new(path: impl Into<String>) -> Self {
        Self(path.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// One rendered file produced by an emitter.
///
/// The emitter owns file layout (which files, what's in each) and renders each
/// file's `body` in full, including its import block. [`assemble`](crate::assemble)
/// collects the files by path and chooses the output layout.
#[derive(Clone, Debug)]
pub struct EmittedFile {
    /// Output-relative path for this file.
    pub path: PathBuf,
    /// The fully rendered file contents, including any import block.
    pub body: String,
}
