# Generated by nexus-api-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

from . import service as _service
from . import models
from .operations.signal_with_start_workflow_execution import (
    signal_with_start_workflow_execution,
)

__all__ = [
    "models",
    "signal_with_start_workflow_execution",
    "__nexus_operation_registry__",
]


__nexus_operation_registry__ = {
    (
        "WorkflowService",
        "SignalWithStartWorkflowExecution",
    ): _service.WorkflowService.signal_with_start_workflow_execution,
}
