# Generated by nexus-api-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

from . import service as _service
from . import models
from ._resources import User
from .operations.get_user import get_user
from ._resources.user import update_email
from ._resources.user import rename
from ._resources.user import deactivate

__all__ = [
    "models",
    "User",
    "deactivate",
    "get_user",
    "rename",
    "update_email",
    "__nexus_operation_registry__",
]


__nexus_operation_registry__ = {
    (
        "TypeShowcase",
        "GetUser",
    ): _service.TypeShowcase.get_user,
    (
        "TypeShowcase",
        "UpdateEmail",
    ): _service.TypeShowcase.update_email,
    (
        "TypeShowcase",
        "Rename",
    ): _service.TypeShowcase.rename,
    (
        "TypeShowcase",
        "Deactivate",
    ): _service.TypeShowcase.deactivate,
}
