use heck::{ToLowerCamelCase, ToUpperCamelCase};
use indexmap::IndexMap;
use prost_types::FieldDescriptorProto;

use crate::SupportFiles;
use crate::api_plan::{
    ApiPlan, PlannedEnum, PlannedField, PlannedFieldKind, PlannedFieldRole, PlannedMessageType,
    PlannedOperation, PlannedOperationResourceFieldBinding, PlannedOperationResourceReturn,
    PlannedResource, PlannedResourceMethodBindingSpec, PlannedScalarType, PlannedSourcedField,
    PlannedTypeInfo, PlannedValueType, relative_descriptor_name, service_client_name,
};
use crate::error::Result;
use crate::generator::{GeneratedFiles, ModelCapabilities};
use crate::resources::{RequestPlan, ResolvedResourceBindingSource, render_request_plan};

const GENERATED_HEADER: &str = "// Generated by nexus-api-gen. DO NOT EDIT!";
const TYPESCRIPT_SUPPORT_MARKER: &str = "// Included from support.$typescript";

pub(crate) fn generate(api_plan: &ApiPlan, support: &SupportFiles) -> Result<GeneratedFiles> {
    let mut enums = IndexMap::new();
    let mut models = IndexMap::new();
    let mut uses_long = false;
    let services = api_plan
        .services
        .iter()
        .map(|service| {
            let client_name = service_client_name(&service.name);
            let operations = service
                .operations
                .iter()
                .map(|operation| {
                    resolve_operation(operation, api_plan, &mut enums, &mut models, &mut uses_long)
                })
                .collect::<Result<Vec<_>>>()?;

            Ok(RenderedService {
                name: service.name.as_str(),
                endpoint: service.endpoint.clone(),
                client_name,
                operations,
                resources: service.resources.clone(),
            })
        })
        .collect::<Result<Vec<_>>>()?;

    Ok(GeneratedFiles::single_file(render_module(
        enums.values().collect::<Vec<_>>().as_slice(),
        models.values().collect::<Vec<_>>().as_slice(),
        &services,
        uses_long,
        support.typescript.as_deref(),
    )))
}

fn generated_model_type_parameters(
    generated_model: &crate::spec::GeneratedModelSpec,
) -> Vec<RenderedTypeParameter> {
    if generated_model.is_empty() {
        return Vec::new();
    }

    let mut type_parameters = generated_model
        .functions
        .iter()
        .map(|(field_name, function)| {
            let generated_name = generated_model
                .field_name_override(field_name)
                .unwrap_or(field_name);
            let type_parameter_name = function_type_parameter_name(generated_name);
            let constraint = function_constraint(&function.result_type);
            (
                !function.primary,
                generated_name.to_string(),
                RenderedTypeParameter {
                    name: type_parameter_name,
                    constraint: constraint.clone(),
                    default: constraint,
                },
            )
        })
        .collect::<Vec<_>>();

    type_parameters.extend(generated_model.with_arguments.iter().map(
        |(field_name, with_arguments)| {
            let generated_name = generated_model
                .field_name_override(field_name)
                .unwrap_or(field_name);
            let constraint = with_arguments.value_type.clone();
            (
                true,
                generated_name.to_string(),
                RenderedTypeParameter {
                    name: with_arguments_type_parameter_name(generated_name),
                    constraint: constraint.clone(),
                    default: constraint,
                },
            )
        },
    ));

    type_parameters.sort_by(|left, right| left.0.cmp(&right.0).then_with(|| left.1.cmp(&right.1)));
    type_parameters
        .into_iter()
        .map(|(_, _, type_parameter)| type_parameter)
        .collect()
}

fn function_type_parameter_name(field_name: &str) -> String {
    format!(
        "{}Fn",
        function_type_parameter_stem(field_name).to_upper_camel_case()
    )
}

fn with_arguments_type_parameter_name(field_name: &str) -> String {
    format!(
        "{}Value",
        function_type_parameter_stem(field_name).to_upper_camel_case()
    )
}

fn function_type_parameter_stem(field_name: &str) -> &str {
    field_name
        .strip_suffix("Type")
        .or_else(|| field_name.strip_suffix("Name"))
        .unwrap_or(field_name)
}

fn function_constraint(result_annotation: &str) -> String {
    format!("(...args: any[]) => {result_annotation}")
}

fn generic_model_annotation(model_name: &str, type_parameters: &[RenderedTypeParameter]) -> String {
    if type_parameters.is_empty() {
        model_name.to_string()
    } else {
        format!(
            "{}<{}>",
            model_name,
            type_parameters
                .iter()
                .map(|type_parameter| type_parameter.name.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

#[derive(Debug)]
struct RenderedService<'a> {
    name: &'a str,
    endpoint: String,
    client_name: String,
    operations: Vec<RenderedOperation<'a>>,
    resources: Vec<PlannedResource>,
}

#[derive(Debug)]
struct RenderedOperation<'a> {
    name: &'a str,
    attr_name: String,
    input_proto_ref: String,
    output_proto_ref: String,
    input_type_parameters: Vec<RenderedTypeParameter>,
    input_annotation: String,
    input_to_proto_expr: String,
    output_annotation: String,
    output_transform_expr: Option<String>,
    output_resource_return: Option<PlannedOperationResourceReturn>,
}

#[derive(Debug)]
struct RenderedEnum {
    name: String,
    values: Vec<RenderedEnumValue>,
}

#[derive(Debug)]
struct RenderedEnumValue {
    name: String,
    number: i32,
}

#[derive(Debug)]
struct RenderedModel {
    name: String,
    proto_ref: String,
    capabilities: ModelCapabilities,
    type_parameters: Vec<RenderedTypeParameter>,
    fields: Vec<RenderedField>,
    sourced_fields: Vec<RenderedSourcedField>,
    functions: Vec<RenderedFunctionField>,
    with_arguments: Vec<RenderedWithArgumentsField>,
}

#[derive(Debug)]
struct RenderedField {
    name: String,
    proto_name: String,
    annotation: String,
    optional: bool,
    from_proto_expr: String,
    to_proto_expr: String,
}

#[derive(Debug)]
struct RenderedSourcedField {
    name: String,
    to_proto_expr: String,
}

#[derive(Debug, Clone)]
struct RenderedTypeParameter {
    name: String,
    constraint: String,
    default: String,
}

#[derive(Debug, Clone)]
struct RenderedFunctionField {
    callable_field_name: String,
    args_field_name: String,
    primary: bool,
    type_parameter_name: String,
}

#[derive(Debug, Clone)]
struct RenderedWithArgumentsField {
    value_field_name: String,
    args_field_name: String,
    type_parameter_name: String,
    args_type_expression: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ResolvedFieldKind {
    Scalar,
    Message,
    Enum,
    Unknown,
}

#[derive(Debug, Clone)]
struct ResolvedFieldType {
    annotation: String,
    kind: ResolvedFieldKind,
    uses_long: bool,
    message_conversion: Option<MessageValueConversion>,
    enum_conversion: Option<EnumValueConversion>,
}

#[derive(Debug, Clone)]
enum MessageValueConversionKind {
    GeneratedModel {
        model_name: String,
    },
    Override {
        from_proto: String,
        to_proto: String,
    },
}

#[derive(Debug, Clone)]
struct MessageValueConversion {
    annotation: String,
    kind: MessageValueConversionKind,
}

impl MessageValueConversion {
    fn from_proto_expr(&self, proto_expr: &str) -> String {
        match &self.kind {
            MessageValueConversionKind::GeneratedModel { model_name } => {
                format!("{model_name}.fromProto({proto_expr})")
            }
            MessageValueConversionKind::Override { from_proto, .. } => {
                format!("{from_proto}({proto_expr})")
            }
        }
    }

    fn to_proto_expr(&self, value_expr: &str) -> String {
        match &self.kind {
            MessageValueConversionKind::GeneratedModel { model_name } => {
                format!("{model_name}.toProto({value_expr}) ?? {{}}")
            }
            MessageValueConversionKind::Override { to_proto, .. } => {
                format!("{to_proto}({value_expr})")
            }
        }
    }
}

#[derive(Debug, Clone)]
struct EnumValueConversion {
    from_proto: String,
    to_proto: String,
}

impl EnumValueConversion {
    fn from_proto_expr(&self, proto_expr: &str) -> String {
        format!("{}({proto_expr})", self.from_proto)
    }

    fn to_proto_expr(&self, value_expr: &str) -> String {
        format!("{}({value_expr})", self.to_proto)
    }
}

fn typescript_default_from_proto_name(name: &str) -> String {
    format!(
        "{}FromProto",
        name.rsplit('.')
            .next()
            .expect("converter name source should have a final segment")
            .to_lower_camel_case()
    )
}

fn typescript_default_to_proto_name(name: &str) -> String {
    format!(
        "{}ToProto",
        name.rsplit('.')
            .next()
            .expect("converter name source should have a final segment")
            .to_lower_camel_case()
    )
}

fn resolve_operation<'a>(
    operation: &'a PlannedOperation,
    api_plan: &ApiPlan,
    enums: &mut IndexMap<String, RenderedEnum>,
    models: &mut IndexMap<String, RenderedModel>,
    uses_long: &mut bool,
) -> Result<RenderedOperation<'a>> {
    let input_conversion =
        resolve_message_value_conversion(&operation.input, api_plan, enums, models, uses_long);
    let output_transform = operation.output_transform.as_ref();
    let output_resource_return = operation.output_resource_return.clone();
    if output_transform.is_none() && output_resource_return.is_none() {
        let _output_conversion =
            resolve_message_value_conversion(&operation.output, api_plan, enums, models, uses_long);
    }
    let input_type_parameters = models
        .get(&operation.input.info.full_name)
        .map(|model| model.type_parameters.clone())
        .unwrap_or_default();
    let input_annotation = if matches!(
        input_conversion.kind,
        MessageValueConversionKind::GeneratedModel { .. }
    ) {
        generic_model_annotation(&input_conversion.annotation, &input_type_parameters)
    } else {
        input_conversion.annotation.clone()
    };

    Ok(RenderedOperation {
        name: operation.name.as_str(),
        attr_name: typescript_ident(&operation.name.to_lower_camel_case()),
        input_proto_ref: message_typescript_interface_ref(&operation.input.info),
        output_proto_ref: message_typescript_interface_ref(&operation.output.info),
        input_type_parameters,
        input_annotation,
        input_to_proto_expr: input_conversion.to_proto_expr("request"),
        output_annotation: output_transform
            .map(|transform| transform.type_name.clone())
            .or_else(|| {
                output_resource_return
                    .as_ref()
                    .map(|resource| resource.resource_type_name.clone())
            })
            .unwrap_or_else(|| message_typescript_interface_ref(&operation.output.info)),
        output_transform_expr: output_transform.map(|transform| transform.transform.clone()),
        output_resource_return,
    })
}

fn resolve_message_value_conversion(
    message: &PlannedMessageType,
    api_plan: &ApiPlan,
    enums: &mut IndexMap<String, RenderedEnum>,
    models: &mut IndexMap<String, RenderedModel>,
    uses_long: &mut bool,
) -> MessageValueConversion {
    if let Some(language_override) = &message.replacement {
        return MessageValueConversion {
            annotation: language_override.type_name.clone(),
            kind: MessageValueConversionKind::Override {
                from_proto: language_override
                    .from_proto
                    .clone()
                    .unwrap_or_else(|| typescript_default_from_proto_name(&message.info.full_name)),
                to_proto: language_override
                    .to_proto
                    .clone()
                    .unwrap_or_else(|| typescript_default_to_proto_name(&message.info.full_name)),
            },
        };
    }

    ensure_rendered_model(message, api_plan, enums, models, uses_long);
    MessageValueConversion {
        annotation: models
            .get(&message.info.full_name)
            .expect("planned model should be rendered")
            .name
            .clone(),
        kind: MessageValueConversionKind::GeneratedModel {
            model_name: message.model_name.clone(),
        },
    }
}

fn ensure_rendered_model(
    message: &PlannedMessageType,
    api_plan: &ApiPlan,
    enums: &mut IndexMap<String, RenderedEnum>,
    models: &mut IndexMap<String, RenderedModel>,
    uses_long: &mut bool,
) {
    let planned_model = api_plan
        .models
        .get(&message.info.full_name)
        .expect("planned model should exist");

    if models.contains_key(&message.info.full_name) {
        return;
    }

    models.insert(
        message.info.full_name.clone(),
        RenderedModel {
            name: planned_model.name.clone(),
            proto_ref: message_typescript_interface_ref(&planned_model.info),
            capabilities: planned_model.capabilities,
            type_parameters: generated_model_type_parameters(&planned_model.generated_model),
            fields: Vec::new(),
            sourced_fields: Vec::new(),
            functions: Vec::new(),
            with_arguments: Vec::new(),
        },
    );

    let fields = planned_model
        .fields
        .iter()
        .map(|field| build_field(field, api_plan, enums, models, uses_long))
        .collect();

    let sourced_fields = planned_model
        .sourced_fields
        .iter()
        .map(|field| build_sourced_field(field, api_plan, enums, models, uses_long))
        .collect();

    models
        .get_mut(&message.info.full_name)
        .expect("model should be inserted before recursive field resolution")
        .fields = fields;
    models
        .get_mut(&message.info.full_name)
        .expect("model should be inserted before recursive field resolution")
        .sourced_fields = sourced_fields;
    models
        .get_mut(&message.info.full_name)
        .expect("model should be inserted before recursive field resolution")
        .functions = Some(&planned_model.generated_model)
        .map(|generated_model| {
            generated_model
                .functions
                .iter()
                .map(|(field_name, function)| RenderedFunctionField {
                    callable_field_name: generated_model
                        .field_name_override(field_name)
                        .map(typescript_generated_field_name)
                        .unwrap_or_else(|| typescript_ident(&field_name.to_lower_camel_case())),
                    args_field_name: generated_model
                        .field_name_override(&function.args_field)
                        .map(typescript_generated_field_name)
                        .unwrap_or_else(|| {
                            typescript_ident(&function.args_field.to_lower_camel_case())
                        }),
                    primary: function.primary,
                    type_parameter_name: function_type_parameter_name(
                        generated_model
                            .field_name_override(field_name)
                            .unwrap_or(field_name),
                    ),
                })
                .collect()
        })
        .unwrap_or_default();
    models
        .get_mut(&message.info.full_name)
        .expect("model should be inserted before recursive field resolution")
        .with_arguments = Some(&planned_model.generated_model)
        .map(|generated_model| {
            generated_model
                .with_arguments
                .iter()
                .map(|(field_name, with_arguments)| RenderedWithArgumentsField {
                    value_field_name: generated_model
                        .field_name_override(field_name)
                        .map(typescript_generated_field_name)
                        .unwrap_or_else(|| typescript_ident(&field_name.to_lower_camel_case())),
                    args_field_name: generated_model
                        .field_name_override(&with_arguments.args_field)
                        .map(typescript_generated_field_name)
                        .unwrap_or_else(|| {
                            typescript_ident(&with_arguments.args_field.to_lower_camel_case())
                        }),
                    type_parameter_name: {
                        let generated_field_name = generated_model
                            .field_name_override(field_name)
                            .unwrap_or(field_name);
                        with_arguments_type_parameter_name(generated_field_name)
                    },
                    args_type_expression: {
                        let generated_field_name = generated_model
                            .field_name_override(field_name)
                            .unwrap_or(field_name);
                        with_arguments_args_type_expression(
                            &with_arguments.args_type,
                            &with_arguments_type_parameter_name(generated_field_name),
                        )
                    },
                })
                .collect()
        })
        .unwrap_or_default();
}

fn ensure_rendered_enum(planned_enum: &PlannedEnum, enums: &mut IndexMap<String, RenderedEnum>) {
    enums
        .entry(planned_enum.info.full_name.clone())
        .or_insert_with(|| RenderedEnum {
            name: planned_enum.name.clone(),
            values: planned_enum
                .values
                .iter()
                .map(|value| RenderedEnumValue {
                    name: value.name.clone(),
                    number: value.number,
                })
                .collect(),
        });
}

fn build_field(
    field: &PlannedField,
    api_plan: &ApiPlan,
    enums: &mut IndexMap<String, RenderedEnum>,
    models: &mut IndexMap<String, RenderedModel>,
    uses_long: &mut bool,
) -> RenderedField {
    let generated_field_name = typescript_generated_field_name(&field.authored_name);
    let proto_field_name = typescript_generated_field_name(&field.proto_name);

    if let PlannedFieldKind::Map { value, .. } = &field.kind {
        let value_type = resolve_planned_value_type(value, api_plan, enums, models, uses_long);
        *uses_long |= value_type.uses_long;
        return RenderedField {
            name: generated_field_name.clone(),
            proto_name: proto_field_name.clone(),
            annotation: typescript_field_annotation(
                field,
                format!("Record<string, {}>", value_type.annotation),
            ),
            optional: true,
            from_proto_expr: map_value_from_proto_expr(&value_type, &proto_field_name),
            to_proto_expr: map_value_to_proto_expr(&value_type, &generated_field_name),
        };
    }

    let (resolved_type, repeated) = match &field.kind {
        PlannedFieldKind::Singular(value) => (
            resolve_planned_value_type(value, api_plan, enums, models, uses_long),
            false,
        ),
        PlannedFieldKind::Repeated(value) => (
            resolve_planned_value_type(value, api_plan, enums, models, uses_long),
            true,
        ),
        PlannedFieldKind::Map { .. } => unreachable!("handled above"),
    };
    *uses_long |= resolved_type.uses_long;
    let owner_name = field.owner_name.clone();

    if let PlannedFieldRole::Function(function_field) = &field.role
        && let Some(converter) = function_field.converter.as_deref()
    {
        return RenderedField {
            name: generated_field_name.clone(),
            proto_name: proto_field_name.clone(),
            annotation: typescript_field_annotation(field, resolved_type.annotation.clone()),
            optional: !field.required,
            from_proto_expr: if field.required {
                required_from_proto_expr(
                    &resolved_type,
                    &owner_name,
                    &proto_field_name,
                    &generated_field_name,
                    field,
                )
            } else {
                optional_from_proto_expr(&resolved_type, &proto_field_name)
            },
            to_proto_expr: if field.required {
                required_function_to_proto_expr(&owner_name, &generated_field_name, converter)
            } else {
                optional_function_to_proto_expr(&generated_field_name, converter)
            },
        };
    }

    if let PlannedFieldRole::WithArguments(with_arguments) = &field.role {
        return RenderedField {
            name: generated_field_name.clone(),
            proto_name: proto_field_name.clone(),
            annotation: typescript_field_annotation(field, resolved_type.annotation.clone()),
            optional: !field.required,
            from_proto_expr: if field.required {
                required_from_proto_expr(
                    &resolved_type,
                    &owner_name,
                    &proto_field_name,
                    &generated_field_name,
                    field,
                )
            } else {
                optional_from_proto_expr(&resolved_type, &proto_field_name)
            },
            to_proto_expr: if field.required {
                required_with_arguments_to_proto_expr(
                    &resolved_type,
                    &owner_name,
                    &generated_field_name,
                    &with_arguments.name_expr,
                )
            } else {
                optional_with_arguments_to_proto_expr(
                    &resolved_type,
                    &generated_field_name,
                    &with_arguments.name_expr,
                )
            },
        };
    }

    if matches!(
        field.role,
        PlannedFieldRole::FunctionArgs | PlannedFieldRole::WithArgumentsArgs
    ) {
        return RenderedField {
            name: generated_field_name.clone(),
            proto_name: proto_field_name.clone(),
            annotation: resolved_type.annotation.clone(),
            optional: true,
            from_proto_expr: optional_from_proto_expr(&resolved_type, &proto_field_name),
            to_proto_expr: optional_function_args_to_proto_expr(
                &resolved_type,
                &generated_field_name,
            ),
        };
    }

    if repeated {
        return RenderedField {
            name: generated_field_name.clone(),
            proto_name: proto_field_name.clone(),
            annotation: typescript_field_annotation(
                field,
                format!("{}[]", resolved_type.annotation),
            ),
            optional: true,
            from_proto_expr: repeated_from_proto_expr(&resolved_type, &proto_field_name),
            to_proto_expr: repeated_to_proto_expr(&resolved_type, &generated_field_name),
        };
    }

    if field.required {
        return RenderedField {
            name: generated_field_name.clone(),
            proto_name: proto_field_name.clone(),
            annotation: typescript_field_annotation(field, resolved_type.annotation.clone()),
            optional: false,
            from_proto_expr: required_from_proto_expr(
                &resolved_type,
                &owner_name,
                &proto_field_name,
                &generated_field_name,
                field,
            ),
            to_proto_expr: required_to_proto_expr(
                &resolved_type,
                &owner_name,
                &generated_field_name,
            ),
        };
    }

    RenderedField {
        name: generated_field_name.clone(),
        proto_name: proto_field_name.clone(),
        annotation: typescript_field_annotation(field, resolved_type.annotation.clone()),
        optional: true,
        from_proto_expr: optional_from_proto_expr(&resolved_type, &proto_field_name),
        to_proto_expr: optional_to_proto_expr(&resolved_type, &generated_field_name),
    }
}

fn build_sourced_field(
    field: &PlannedSourcedField,
    api_plan: &ApiPlan,
    enums: &mut IndexMap<String, RenderedEnum>,
    models: &mut IndexMap<String, RenderedModel>,
    uses_long: &mut bool,
) -> RenderedSourcedField {
    let field_name = typescript_generated_field_name(&field.proto_name);

    if let PlannedFieldKind::Map { value, .. } = &field.kind {
        let value_type = resolve_planned_value_type(value, api_plan, enums, models, uses_long);
        *uses_long |= value_type.uses_long;
        return RenderedSourcedField {
            name: field_name.clone(),
            to_proto_expr: map_value_to_proto_expr_from_expr(&value_type, &field.source_expr),
        };
    }

    let (resolved_type, repeated) = match &field.kind {
        PlannedFieldKind::Singular(value) => (
            resolve_planned_value_type(value, api_plan, enums, models, uses_long),
            false,
        ),
        PlannedFieldKind::Repeated(value) => (
            resolve_planned_value_type(value, api_plan, enums, models, uses_long),
            true,
        ),
        PlannedFieldKind::Map { .. } => unreachable!("handled above"),
    };
    *uses_long |= resolved_type.uses_long;

    if repeated {
        return RenderedSourcedField {
            name: field_name.clone(),
            to_proto_expr: repeated_to_proto_expr_from_expr(&resolved_type, &field.source_expr),
        };
    }

    RenderedSourcedField {
        name: field_name,
        to_proto_expr: optional_to_proto_expr_from_expr(&resolved_type, &field.source_expr),
    }
}

fn typescript_field_annotation(field: &PlannedField, default_annotation: String) -> String {
    let annotation = field
        .annotation_override
        .clone()
        .unwrap_or(default_annotation);
    if !field.required && annotation.ends_with(" | undefined") {
        annotation
            .strip_suffix(" | undefined")
            .expect("suffix check should guarantee success")
            .to_string()
    } else {
        annotation
    }
}

fn resolve_planned_value_type(
    value_type: &PlannedValueType,
    api_plan: &ApiPlan,
    enums: &mut IndexMap<String, RenderedEnum>,
    models: &mut IndexMap<String, RenderedModel>,
    uses_long: &mut bool,
) -> ResolvedFieldType {
    match value_type {
        PlannedValueType::Scalar(PlannedScalarType::Float | PlannedScalarType::Int32) => {
            ResolvedFieldType {
                annotation: "number".to_string(),
                kind: ResolvedFieldKind::Scalar,
                uses_long: false,
                message_conversion: None,
                enum_conversion: None,
            }
        }
        PlannedValueType::Scalar(PlannedScalarType::Int64) => {
            *uses_long = true;
            ResolvedFieldType {
                annotation: "Long".to_string(),
                kind: ResolvedFieldKind::Scalar,
                uses_long: true,
                message_conversion: None,
                enum_conversion: None,
            }
        }
        PlannedValueType::Scalar(PlannedScalarType::Bool) => ResolvedFieldType {
            annotation: "boolean".to_string(),
            kind: ResolvedFieldKind::Scalar,
            uses_long: false,
            message_conversion: None,
            enum_conversion: None,
        },
        PlannedValueType::Scalar(PlannedScalarType::String) => ResolvedFieldType {
            annotation: "string".to_string(),
            kind: ResolvedFieldKind::Scalar,
            uses_long: false,
            message_conversion: None,
            enum_conversion: None,
        },
        PlannedValueType::Scalar(PlannedScalarType::Bytes) => ResolvedFieldType {
            annotation: "Uint8Array".to_string(),
            kind: ResolvedFieldKind::Scalar,
            uses_long: false,
            message_conversion: None,
            enum_conversion: None,
        },
        PlannedValueType::Enum(enum_type) => {
            if let Some(replacement) = &enum_type.replacement {
                ResolvedFieldType {
                    annotation: replacement.type_name.clone(),
                    kind: ResolvedFieldKind::Enum,
                    uses_long: false,
                    message_conversion: None,
                    enum_conversion: enum_type.info.as_ref().map(|info| EnumValueConversion {
                        from_proto: replacement
                            .from_proto
                            .clone()
                            .unwrap_or_else(|| typescript_default_from_proto_name(&info.full_name)),
                        to_proto: replacement
                            .to_proto
                            .clone()
                            .unwrap_or_else(|| typescript_default_to_proto_name(&info.full_name)),
                    }),
                }
            } else if let (Some(info), Some(name)) = (&enum_type.info, &enum_type.name) {
                if let Some(planned_enum) = api_plan.enums.get(&info.full_name) {
                    ensure_rendered_enum(planned_enum, enums);
                }
                ResolvedFieldType {
                    annotation: name.clone(),
                    kind: ResolvedFieldKind::Enum,
                    uses_long: false,
                    message_conversion: None,
                    enum_conversion: None,
                }
            } else {
                ResolvedFieldType {
                    annotation: "number".to_string(),
                    kind: ResolvedFieldKind::Enum,
                    uses_long: false,
                    message_conversion: None,
                    enum_conversion: None,
                }
            }
        }
        PlannedValueType::Message(message_type) => {
            let conversion = if let Some(replacement) = &message_type.replacement {
                MessageValueConversion {
                    annotation: replacement.type_name.clone(),
                    kind: MessageValueConversionKind::Override {
                        from_proto: replacement.from_proto.clone().unwrap_or_else(|| {
                            typescript_default_from_proto_name(&message_type.info.full_name)
                        }),
                        to_proto: replacement.to_proto.clone().unwrap_or_else(|| {
                            typescript_default_to_proto_name(&message_type.info.full_name)
                        }),
                    },
                }
            } else {
                ensure_rendered_model(message_type, api_plan, enums, models, uses_long);
                let model = models
                    .get(&message_type.info.full_name)
                    .expect("planned model should be rendered");
                MessageValueConversion {
                    annotation: model.name.clone(),
                    kind: MessageValueConversionKind::GeneratedModel {
                        model_name: message_type.model_name.clone(),
                    },
                }
            };
            ResolvedFieldType {
                annotation: conversion.annotation.clone(),
                kind: ResolvedFieldKind::Message,
                uses_long: false,
                message_conversion: Some(conversion),
                enum_conversion: None,
            }
        }
        PlannedValueType::Unknown => ResolvedFieldType {
            annotation: "unknown".to_string(),
            kind: ResolvedFieldKind::Unknown,
            uses_long: false,
            message_conversion: None,
            enum_conversion: None,
        },
    }
}

fn repeated_from_proto_expr(resolved_type: &ResolvedFieldType, field_name: &str) -> String {
    match resolved_type.kind {
        ResolvedFieldKind::Message => format!(
            "proto.{field_name}?.map((value: any) => {}!)",
            resolved_type
                .message_conversion
                .as_ref()
                .expect("message conversion should be present")
                .from_proto_expr("value")
        ),
        ResolvedFieldKind::Enum => format!(
            "proto.{field_name}?.map((value: any) => {})",
            enum_from_proto_expr(resolved_type, "value")
        ),
        _ => format!("proto.{field_name}?.slice()"),
    }
}

fn repeated_to_proto_expr(resolved_type: &ResolvedFieldType, field_name: &str) -> String {
    repeated_to_proto_expr_from_expr(resolved_type, &format!("model.{field_name}"))
}

fn repeated_to_proto_expr_from_expr(resolved_type: &ResolvedFieldType, value_expr: &str) -> String {
    match resolved_type.kind {
        ResolvedFieldKind::Message => format!(
            "{value_expr}?.map((value) => {})",
            resolved_type
                .message_conversion
                .as_ref()
                .expect("message conversion should be present")
                .to_proto_expr("value")
        ),
        ResolvedFieldKind::Enum => format!(
            "{value_expr}?.map((value) => {})",
            enum_to_proto_expr(resolved_type, "value")
        ),
        _ => format!("{value_expr}?.slice()"),
    }
}

fn map_value_from_proto_expr(map_value_type: &ResolvedFieldType, field_name: &str) -> String {
    let value_expr = match map_value_type.kind {
        ResolvedFieldKind::Message => map_value_type
            .message_conversion
            .as_ref()
            .expect("message conversion should be present")
            .from_proto_expr("value"),
        ResolvedFieldKind::Enum => enum_from_proto_expr(map_value_type, "value"),
        _ => format!("value as {}", map_value_type.annotation),
    };
    format!(
        "proto.{field_name} == null ? undefined : (Object.fromEntries(Object.entries(proto.{field_name} as Record<string, any>).map(([key, value]: [string, any]) => [key, {value_expr}])) as Record<string, {}>)",
        map_value_type.annotation
    )
}

fn map_value_to_proto_expr(map_value_type: &ResolvedFieldType, field_name: &str) -> String {
    map_value_to_proto_expr_from_expr(map_value_type, &format!("model.{field_name}"))
}

fn map_value_to_proto_expr_from_expr(
    map_value_type: &ResolvedFieldType,
    value_expr: &str,
) -> String {
    let mapped_value_expr = match map_value_type.kind {
        ResolvedFieldKind::Message => map_value_type
            .message_conversion
            .as_ref()
            .expect("message conversion should be present")
            .to_proto_expr("value"),
        ResolvedFieldKind::Enum => enum_to_proto_expr(map_value_type, "value"),
        _ => "value".to_string(),
    };
    format!(
        "{value_expr} == null ? undefined : Object.fromEntries(Object.entries({value_expr} as Record<string, any>).map(([key, value]: [string, any]) => [key, {mapped_value_expr}]))"
    )
}

fn required_from_proto_expr(
    resolved_type: &ResolvedFieldType,
    owner_name: &str,
    proto_field_name: &str,
    generated_field_name: &str,
    field: &PlannedField,
) -> String {
    let proto_value_expr = if field.has_presence {
        format!("proto.{proto_field_name}")
    } else if matches!(
        &field.kind,
        PlannedFieldKind::Singular(PlannedValueType::Scalar(PlannedScalarType::String))
    ) {
        format!("proto.{proto_field_name} === '' ? undefined : proto.{proto_field_name}")
    } else if matches!(
        &field.kind,
        PlannedFieldKind::Singular(PlannedValueType::Scalar(PlannedScalarType::Bytes))
    ) {
        format!(
            "proto.{proto_field_name} == null || proto.{proto_field_name}.length === 0 ? undefined : proto.{proto_field_name}"
        )
    } else {
        format!("proto.{proto_field_name} ?? undefined")
    };
    let required_proto_expr =
        required_field_expr(&proto_value_expr, owner_name, generated_field_name);

    match resolved_type.kind {
        ResolvedFieldKind::Message => required_field_expr(
            &resolved_type
                .message_conversion
                .as_ref()
                .expect("message conversion should be present")
                .from_proto_expr(&required_proto_expr),
            owner_name,
            generated_field_name,
        ),
        ResolvedFieldKind::Enum => required_field_expr(
            &enum_from_proto_expr(resolved_type, &required_proto_expr),
            owner_name,
            generated_field_name,
        ),
        _ => required_proto_expr,
    }
}

fn required_to_proto_expr(
    resolved_type: &ResolvedFieldType,
    owner_name: &str,
    field_name: &str,
) -> String {
    let required_value =
        required_field_expr(&format!("model.{field_name}"), owner_name, field_name);
    match resolved_type.kind {
        ResolvedFieldKind::Message => resolved_type
            .message_conversion
            .as_ref()
            .expect("message conversion should be present")
            .to_proto_expr(&required_value),
        ResolvedFieldKind::Enum => enum_to_proto_expr(resolved_type, &required_value),
        _ => required_value,
    }
}

fn optional_from_proto_expr(resolved_type: &ResolvedFieldType, field_name: &str) -> String {
    match resolved_type.kind {
        ResolvedFieldKind::Message => format!(
            "proto.{field_name} == null ? undefined : {}",
            resolved_type
                .message_conversion
                .as_ref()
                .expect("message conversion should be present")
                .from_proto_expr(&format!("proto.{field_name}"))
        ),
        ResolvedFieldKind::Enum => format!(
            "proto.{field_name} == null ? undefined : {}",
            enum_from_proto_expr(resolved_type, &format!("proto.{field_name}"))
        ),
        _ => format!("proto.{field_name} ?? undefined"),
    }
}

fn optional_to_proto_expr(resolved_type: &ResolvedFieldType, field_name: &str) -> String {
    optional_to_proto_expr_from_expr(resolved_type, &format!("model.{field_name}"))
}

fn optional_to_proto_expr_from_expr(resolved_type: &ResolvedFieldType, value_expr: &str) -> String {
    match resolved_type.kind {
        ResolvedFieldKind::Message => format!(
            "{value_expr} == null ? undefined : {}",
            resolved_type
                .message_conversion
                .as_ref()
                .expect("message conversion should be present")
                .to_proto_expr(value_expr)
        ),
        ResolvedFieldKind::Enum => format!(
            "{value_expr} == null ? undefined : {}",
            enum_to_proto_expr(resolved_type, value_expr)
        ),
        _ => value_expr.to_string(),
    }
}

fn required_function_to_proto_expr(owner_name: &str, field_name: &str, converter: &str) -> String {
    let required_value =
        required_field_expr(&format!("model.{field_name}"), owner_name, field_name);
    format!("{converter}({required_value})")
}

fn optional_function_to_proto_expr(field_name: &str, converter: &str) -> String {
    let value_expr = format!("model.{field_name}");
    format!(
        "{value_expr} == null ? undefined : {}",
        format!("{converter}({value_expr})")
    )
}

fn required_with_arguments_to_proto_expr(
    resolved_type: &ResolvedFieldType,
    owner_name: &str,
    field_name: &str,
    name_expr_template: &str,
) -> String {
    let required_value =
        required_field_expr(&format!("model.{field_name}"), owner_name, field_name);
    function_value_to_proto_expr(
        resolved_type,
        &with_arguments_name_expr(name_expr_template, &required_value),
    )
}

fn optional_with_arguments_to_proto_expr(
    resolved_type: &ResolvedFieldType,
    field_name: &str,
    name_expr_template: &str,
) -> String {
    let value_expr = format!("model.{field_name}");
    format!(
        "{value_expr} == null ? undefined : {}",
        function_value_to_proto_expr(
            resolved_type,
            &with_arguments_name_expr(name_expr_template, &value_expr),
        )
    )
}

fn function_value_to_proto_expr(resolved_type: &ResolvedFieldType, name_expr: &str) -> String {
    match resolved_type.kind {
        ResolvedFieldKind::Message => match &resolved_type
            .message_conversion
            .as_ref()
            .expect("message conversion should be present")
            .kind
        {
            MessageValueConversionKind::GeneratedModel { model_name } => {
                format!("{model_name}.toProto({{ name: {name_expr} }}) ?? {{}}")
            }
            MessageValueConversionKind::Override { to_proto, .. } => {
                format!("{to_proto}({name_expr})")
            }
        },
        _ => name_expr.to_string(),
    }
}

fn with_arguments_name_expr(name_expr_template: &str, value_expr: &str) -> String {
    format!(
        "((value) => typeof value === 'string' ? value : ({}))({value_expr})",
        name_expr_template,
    )
}

fn optional_function_args_to_proto_expr(
    resolved_type: &ResolvedFieldType,
    field_name: &str,
) -> String {
    if let Some(message_conversion) = &resolved_type.message_conversion {
        if let MessageValueConversionKind::Override { .. } = message_conversion.kind {
            return optional_to_proto_expr_from_expr(resolved_type, &format!("model.{field_name}"));
        }
    }

    format!("_RequestArgsToPayloads(model.{field_name})")
}

fn enum_from_proto_expr(resolved_type: &ResolvedFieldType, expr: &str) -> String {
    if let Some(enum_conversion) = &resolved_type.enum_conversion {
        enum_conversion.from_proto_expr(expr)
    } else {
        format!("{expr} as {}", resolved_type.annotation)
    }
}

fn enum_to_proto_expr(resolved_type: &ResolvedFieldType, expr: &str) -> String {
    if let Some(enum_conversion) = &resolved_type.enum_conversion {
        enum_conversion.to_proto_expr(expr)
    } else {
        format!("{expr} as number")
    }
}

fn message_typescript_interface_ref(type_info: &PlannedTypeInfo) -> String {
    let relative_name = relative_descriptor_name(&type_info.full_name, &type_info.package);
    let mut parts = relative_name.split('.').collect::<Vec<_>>();
    let leaf = parts
        .pop()
        .expect("descriptor names should not be empty")
        .to_string();
    if parts.is_empty() {
        format!("{}.I{leaf}", type_info.package)
    } else {
        format!("{}.{}.I{leaf}", type_info.package, parts.join("."))
    }
}

fn render_module(
    enums: &[&RenderedEnum],
    models: &[&RenderedModel],
    services: &[RenderedService<'_>],
    uses_long: bool,
    support_source: Option<&str>,
) -> String {
    let default_imports = [
        "import * as common from '@temporalio/common';",
        "import * as nexus from 'nexus-rpc';",
        "import type Long from 'long';",
        "import type { google, temporal } from '@temporalio/proto';",
        "import * as workflow from '@temporalio/workflow';",
    ];

    let mut output = String::new();
    output.push_str(GENERATED_HEADER);
    output.push_str("\n\n");
    output.push_str(default_imports[0]);
    output.push('\n');
    output.push_str(default_imports[1]);
    output.push('\n');
    if uses_long {
        output.push_str(default_imports[2]);
        output.push('\n');
    }
    output.push_str(default_imports[3]);
    output.push('\n');
    output.push_str(default_imports[4]);
    output.push('\n');

    if let Some(support_source) = support_source.filter(|source| !source.trim().is_empty()) {
        output.push('\n');
        output.push_str(TYPESCRIPT_SUPPORT_MARKER);
        output.push('\n');
        output.push_str(support_source);
        if !support_source.ends_with('\n') {
            output.push('\n');
        }
    }

    output.push_str("\n");
    output.push_str("function requiredField<T>(\n");
    output.push_str("  value: T | null | undefined,\n");
    output.push_str("  owner: string,\n");
    output.push_str("  field: string,\n");
    output.push_str("): T {\n");
    output.push_str("  if (value == null) {\n");
    output.push_str("    throw new Error(`missing required field ${owner}.${field}`);\n");
    output.push_str("  }\n");
    output.push_str("  return value;\n");
    output.push_str("}\n");

    let uses_invocation_models = models
        .iter()
        .any(|model| !model.functions.is_empty() || !model.with_arguments.is_empty());
    if uses_invocation_models {
        output.push('\n');
        render_function_type_helpers(&mut output);
        output.push('\n');
        render_function_runtime_helpers(&mut output);
    }
    if !enums.is_empty() {
        output.push('\n');
        for enumeration in enums {
            render_enum(&mut output, enumeration);
            output.push('\n');
        }
    }

    if !models.is_empty() {
        output.push('\n');
        for model in models {
            render_model(&mut output, model);
            output.push('\n');
        }
    }

    let resources = services
        .iter()
        .flat_map(|service| {
            service
                .resources
                .iter()
                .map(move |resource| (resource, service))
        })
        .collect::<Vec<_>>();
    if !resources.is_empty() {
        output.push('\n');
        for (resource, service) in resources {
            render_resource(&mut output, resource, service);
            output.push('\n');
        }
    }

    for (index, service) in services.iter().enumerate() {
        if index > 0 || !services.is_empty() {
            output.push('\n');
        }
        render_service(&mut output, service);
    }

    output
}

fn render_enum(output: &mut String, enumeration: &RenderedEnum) {
    output.push_str("export enum ");
    output.push_str(&enumeration.name);
    output.push_str(" {\n");
    if enumeration.values.is_empty() {
        output.push_str("}\n");
        return;
    }
    for value in &enumeration.values {
        output.push_str("  ");
        output.push_str(&value.name);
        output.push_str(" = ");
        output.push_str(&value.number.to_string());
        output.push_str(",\n");
    }
    output.push_str("}\n");
}

fn render_function_type_helpers(output: &mut String) {
    output.push_str("type _RequestWithFunctionField<\n");
    output.push_str("  Fn extends (...args: any[]) => any,\n");
    output.push_str("  Base,\n");
    output.push_str("  Field extends string,\n");
    output.push_str("  ArgsField extends string,\n");
    output.push_str("> =\n");
    output.push_str(
        "  | (Base & { [K in Field]: string } & { [K in ArgsField]?: ReadonlyArray<unknown> })\n",
    );
    output.push_str("  | (Base & { [K in Field]: Fn } & (Parameters<Fn> extends [any, ...any[]]\n");
    output.push_str("      ? { [K in ArgsField]: Parameters<Fn> | Readonly<Parameters<Fn>> }\n");
    output
        .push_str("      : { [K in ArgsField]?: Parameters<Fn> | Readonly<Parameters<Fn>> }));\n");
    output.push_str("\n");
    output.push_str("type _RequestWithArgumentsField<\n");
    output.push_str("  Value,\n");
    output.push_str("  Args extends any[],\n");
    output.push_str("  Base,\n");
    output.push_str("  Field extends string,\n");
    output.push_str("  ArgsField extends string,\n");
    output.push_str("> =\n");
    output.push_str(
        "  | (Base & { [K in Field]: string } & { [K in ArgsField]?: ReadonlyArray<unknown> })\n",
    );
    output.push_str("  | (Base & { [K in Field]: Value } & (Args extends [any, ...any[]]\n");
    output.push_str("      ? { [K in ArgsField]: Args | Readonly<Args> }\n");
    output.push_str("      : { [K in ArgsField]?: Args | Readonly<Args> }));\n");
}

fn render_function_runtime_helpers(output: &mut String) {
    output.push_str("function _RequestArgsToPayloads(\n");
    output.push_str("  args: ReadonlyArray<unknown> | undefined,\n");
    output.push_str("): temporal.api.common.v1.IPayloads | undefined {\n");
    output.push_str("  if (args == null) {\n");
    output.push_str("    return undefined;\n");
    output.push_str("  }\n");
    output.push_str(
        "  const payloads = common.toPayloads(common.defaultPayloadConverter, ...args);\n",
    );
    output.push_str("  return payloads == null ? undefined : { payloads };\n");
    output.push_str("}\n");
}

fn render_type_parameter_list(type_parameters: &[RenderedTypeParameter]) -> String {
    if type_parameters.is_empty() {
        return String::new();
    }

    let params = type_parameters
        .iter()
        .map(|type_parameter| {
            format!(
                "{} extends {} = {}",
                type_parameter.name, type_parameter.constraint, type_parameter.default
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("<{params}>")
}

fn render_named_generic_function_start(
    output: &mut String,
    name: &str,
    type_parameters: &[RenderedTypeParameter],
    indent: usize,
) {
    let indent_str = " ".repeat(indent);
    output.push_str(name);
    output.push_str("<\n");
    for type_parameter in type_parameters {
        output.push_str(&indent_str);
        output.push_str("  ");
        output.push_str(&type_parameter.name);
        output.push_str(" extends ");
        output.push_str(&type_parameter.constraint);
        output.push_str(" = ");
        output.push_str(&type_parameter.default);
        output.push_str(",\n");
    }
    output.push_str(&indent_str);
    output.push_str(">(\n");
}

fn render_function_model_composition(model: &RenderedModel, base_name: &str) -> String {
    let mut composition = base_name.to_string();
    let mut invocations = model
        .functions
        .iter()
        .map(RenderedInvocationField::Function)
        .chain(
            model
                .with_arguments
                .iter()
                .map(RenderedInvocationField::WithArguments),
        )
        .collect::<Vec<_>>();
    invocations.sort_by(|left, right| {
        left.sort_key()
            .cmp(&right.sort_key())
            .then_with(|| left.field_name().cmp(right.field_name()))
    });

    for invocation in invocations {
        composition = match invocation {
            RenderedInvocationField::Function(function) => format!(
                "_RequestWithFunctionField<{}, {}, {}, {}>",
                function.type_parameter_name,
                composition,
                typescript_string_literal(&function.callable_field_name),
                typescript_string_literal(&function.args_field_name),
            ),
            RenderedInvocationField::WithArguments(with_arguments) => format!(
                "_RequestWithArgumentsField<{}, {}, {}, {}, {}>",
                with_arguments.type_parameter_name,
                with_arguments.args_type_expression,
                composition,
                typescript_string_literal(&with_arguments.value_field_name),
                typescript_string_literal(&with_arguments.args_field_name),
            ),
        };
    }
    composition
}

#[derive(Clone, Copy)]
enum RenderedInvocationField<'a> {
    Function(&'a RenderedFunctionField),
    WithArguments(&'a RenderedWithArgumentsField),
}

impl<'a> RenderedInvocationField<'a> {
    fn sort_key(self) -> (u8, bool) {
        match self {
            Self::Function(function) => (0, !function.primary),
            Self::WithArguments(_) => (1, true),
        }
    }

    fn field_name(self) -> &'a str {
        match self {
            Self::Function(function) => &function.callable_field_name,
            Self::WithArguments(with_arguments) => &with_arguments.value_field_name,
        }
    }
}

fn with_arguments_args_type_expression(
    args_type_template: &str,
    type_parameter_name: &str,
) -> String {
    args_type_template.replace("Value", type_parameter_name)
}

fn render_model(output: &mut String, model: &RenderedModel) {
    if model.functions.is_empty() && model.with_arguments.is_empty() {
        output.push_str("export interface ");
        output.push_str(&model.name);
        output.push_str(" {\n");
        for field in &model.fields {
            output.push_str("  ");
            output.push_str(&field.name);
            if field.optional {
                output.push('?');
            }
            output.push_str(": ");
            output.push_str(&field.annotation);
            output.push_str(";\n");
        }
        output.push_str("}\n\n");
    } else {
        let function_fields = model
            .functions
            .iter()
            .map(|function| function.callable_field_name.as_str())
            .chain(
                model
                    .with_arguments
                    .iter()
                    .map(|with_arguments| with_arguments.value_field_name.as_str()),
            )
            .collect::<Vec<_>>();
        let args_fields = model
            .functions
            .iter()
            .map(|function| function.args_field_name.as_str())
            .chain(
                model
                    .with_arguments
                    .iter()
                    .map(|with_arguments| with_arguments.args_field_name.as_str()),
            )
            .collect::<Vec<_>>();
        let base_name = format!("{}Base", model.name);

        output.push_str("type ");
        output.push_str(&base_name);
        output.push_str(" = {\n");
        for field in &model.fields {
            if function_fields.contains(&field.name.as_str())
                || args_fields.contains(&field.name.as_str())
            {
                continue;
            }
            output.push_str("  ");
            output.push_str(&field.name);
            if field.optional {
                output.push('?');
            }
            output.push_str(": ");
            output.push_str(&field.annotation);
            output.push_str(";\n");
        }
        output.push_str("};\n\n");

        output.push_str("export type ");
        output.push_str(&model.name);
        output.push_str(&render_type_parameter_list(&model.type_parameters));
        output.push_str(" = ");
        output.push_str(&render_function_model_composition(model, &base_name));
        output.push_str(";\n\n");
    }
    output.push_str("export const ");
    output.push_str(&model.name);
    output.push_str(" = {\n");
    let mut wrote_method = false;
    if model.capabilities.from_proto {
        output.push_str("  fromProto(\n");
        output.push_str("    proto: ");
        output.push_str(&model.proto_ref);
        output.push_str(" | null | undefined,\n");
        output.push_str("  ): ");
        output.push_str(&model.name);
        output.push_str(" | undefined {\n");
        output.push_str("    if (proto == null) {\n");
        output.push_str("      return undefined;\n");
        output.push_str("    }\n");
        if model.fields.is_empty() {
            output.push_str("    return {};\n");
        } else {
            output.push_str("    return {\n");
            for field in &model.fields {
                output.push_str("      ");
                output.push_str(&field.name);
                output.push_str(": ");
                output.push_str(&field.from_proto_expr);
                output.push_str(",\n");
            }
            output.push_str("    };\n");
        }
        output.push_str("  }");
        wrote_method = true;
    }
    if model.capabilities.to_proto {
        if wrote_method {
            output.push_str(",\n\n");
        }
        if model.type_parameters.is_empty() {
            output.push_str("  toProto(\n");
            output.push_str("    model: ");
            output.push_str(&model.name);
            output.push_str(" | null | undefined,\n");
        } else {
            render_named_generic_function_start(output, "  toProto", &model.type_parameters, 4);
            output.push_str("    model: ");
            output.push_str(&generic_model_annotation(
                &model.name,
                &model.type_parameters,
            ));
            output.push_str(" | null | undefined,\n");
        }
        output.push_str("  ): ");
        output.push_str(&model.proto_ref);
        output.push_str(" | undefined {\n");
        output.push_str("    if (model == null) {\n");
        output.push_str("      return undefined;\n");
        output.push_str("    }\n");
        if model.fields.is_empty() && model.sourced_fields.is_empty() {
            output.push_str("    return {};\n");
        } else {
            output.push_str("    return {\n");
            for field in &model.fields {
                output.push_str("      ");
                output.push_str(&field.proto_name);
                output.push_str(": ");
                output.push_str(&field.to_proto_expr);
                output.push_str(",\n");
            }
            for field in &model.sourced_fields {
                output.push_str("      ");
                output.push_str(&field.name);
                output.push_str(": ");
                output.push_str(&field.to_proto_expr);
                output.push_str(",\n");
            }
            output.push_str("    };\n");
        }
        output.push_str("  }");
    }
    output.push('\n');
    output.push_str("};\n");
}

fn render_service(output: &mut String, service: &RenderedService<'_>) {
    output.push_str("export const ");
    output.push_str(service.name);
    output.push_str(" = nexus.service('");
    output.push_str(service.name);
    output.push_str("', {\n");
    for operation in &service.operations {
        output.push_str("  ");
        output.push_str(&operation.attr_name);
        output.push_str(": nexus.operation<\n");
        output.push_str("    ");
        output.push_str(&operation.input_proto_ref);
        output.push_str(",\n");
        output.push_str("    ");
        output.push_str(&operation.output_proto_ref);
        output.push('\n');
        output.push_str("  >({ name: ");
        output.push_str(&typescript_string_literal(operation.name));
        output.push_str(" }),\n");
    }
    output.push_str("});\n\n");

    output.push_str("export class ");
    output.push_str(&service.client_name);
    output.push_str(" {\n");
    output.push_str("  public readonly client: workflow.NexusServiceClient<typeof ");
    output.push_str(service.name);
    output.push_str(">;\n\n");
    output.push_str("  public constructor() {\n");
    output.push_str("    this.client = workflow.createNexusServiceClient({\n");
    output.push_str("      service: ");
    output.push_str(service.name);
    output.push_str(",\n");
    output.push_str("      endpoint: ");
    output.push_str(&typescript_string_literal(&service.endpoint));
    output.push_str(",\n");
    output.push_str("    });\n");
    output.push_str("  }\n");

    if service.operations.is_empty() {
        output.push('\n');
        output.push_str("}\n");
        return;
    }

    for operation in &service.operations {
        output.push('\n');
        render_operation_client_methods(output, service.name, operation);
    }

    output.push_str("}\n");
}

fn render_resource(output: &mut String, resource: &PlannedResource, service: &RenderedService<'_>) {
    output.push_str("export class ");
    output.push_str(&resource.type_name);
    output.push_str(" {\n");
    output.push_str("  public constructor(\n");
    output.push_str("    private readonly client: ");
    output.push_str(&service.client_name);
    output.push_str(",\n");
    for field in &resource.fields {
        output.push_str("    public readonly ");
        output.push_str(&typescript_generated_field_name(&field.name));
        output.push_str(": ");
        output.push_str(&field.annotation);
        output.push_str(",\n");
    }
    output.push_str("  ) {}\n");

    if resource.methods.is_empty() {
        output.push_str("}\n");
        return;
    }

    for method in &resource.methods {
        let result_annotation = method.result_annotation.as_deref().unwrap_or("void");
        output.push('\n');
        output.push_str("  public async ");
        output.push_str(&typescript_generated_field_name(&method.name));
        output.push_str("(\n");
        for param in &method.params {
            output.push_str("    ");
            output.push_str(&typescript_generated_field_name(&param.name));
            if param.optional {
                output.push('?');
            }
            output.push_str(": ");
            output.push_str(&param.annotation);
            output.push_str(",\n");
        }
        output.push_str("  ): Promise<");
        output.push_str(result_annotation);
        output.push_str("> {\n");
        match &method.binding {
            PlannedResourceMethodBindingSpec::Operation {
                operation_name,
                request_plan,
                direct_return,
            } => {
                let operation = service
                    .operations
                    .iter()
                    .find(|operation| operation.name == operation_name)
                    .expect("bound operation should exist on the resource service");
                output.push_str("    const request = ");
                output.push_str(&render_request_plan_typescript(request_plan));
                output.push_str(";\n");
                let request_to_proto_expr =
                    operation_input_to_proto_expr_for_resource_method(operation);
                if *direct_return {
                    output.push_str("    const requestProto = ");
                    output.push_str(&request_to_proto_expr);
                    output.push_str(";\n");
                    output
                        .push_str("    const handle = await this.client.client.startOperation(\n");
                    output.push_str("      ");
                    output.push_str(service.name);
                    output.push_str(".operations.");
                    output.push_str(&operation.attr_name);
                    output.push_str(",\n");
                    output.push_str("      requestProto,\n");
                    output.push_str("    );\n");
                    if let Some(transform_expr) = &operation.output_transform_expr {
                        output.push_str("    const result = await handle.result();\n");
                        if result_annotation == "void" {
                            output.push_str("    ");
                            output.push_str(transform_expr);
                            output.push_str(";\n");
                        } else {
                            output.push_str("    return ");
                            output.push_str(transform_expr);
                            output.push_str(";\n");
                        }
                    } else if let Some(resource_return) = &operation.output_resource_return {
                        output.push_str("    const result = await handle.result();\n");
                        if result_annotation == "void" {
                            output.push_str("    new ");
                            output.push_str(&resource_return.resource_type_name);
                            output.push_str("(\n");
                        } else {
                            output.push_str("    return new ");
                            output.push_str(&resource_return.resource_type_name);
                            output.push_str("(\n");
                        }
                        output.push_str("      this.client,\n");
                        for binding in &resource_return.bindings {
                            output.push_str("      ");
                            output.push_str(&resource_return_binding_expr_typescript(binding));
                            output.push_str(",\n");
                        }
                        output.push_str("    );\n");
                    }
                } else {
                    output
                        .push_str("    const handle = await this.client.client.startOperation(\n");
                    output.push_str("      ");
                    output.push_str(service.name);
                    output.push_str(".operations.");
                    output.push_str(&operation.attr_name);
                    output.push_str(",\n");
                    output.push_str("      ");
                    output.push_str(&request_to_proto_expr);
                    output.push_str(",\n");
                    output.push_str("    );\n");
                    if result_annotation == "void" {
                        output.push_str("    await handle.result();\n");
                    } else {
                        output.push_str("    return await handle.result();\n");
                    }
                }
            }
            PlannedResourceMethodBindingSpec::Stub => {
                output.push_str("    throw new Error(");
                output.push_str(&typescript_string_literal(&format!(
                    "{}.{} is not yet implemented",
                    resource.name,
                    typescript_generated_field_name(&method.name)
                )));
                output.push_str(");\n");
            }
        }
        output.push_str("  }\n");
    }

    output.push_str("}\n");
}

fn render_request_plan_typescript(plan: &RequestPlan) -> String {
    render_request_plan(
        plan,
        typescript_generated_field_name,
        |name, value| format!("{name}: {value}"),
        |_message_name, fields| {
            if fields.is_empty() {
                "{}".to_string()
            } else {
                format!("{{ {} }}", fields.join(", "))
            }
        },
        |name| format!("this.{}", typescript_generated_field_name(name)),
        typescript_generated_field_name,
    )
}

fn resource_return_binding_expr_typescript(
    binding: &PlannedOperationResourceFieldBinding,
) -> String {
    match &binding.source {
        ResolvedResourceBindingSource::RequestField {
            field_name,
            proto_field_name,
            hidden,
        } => {
            if *hidden {
                let expr = format!(
                    "requestProto.{}",
                    typescript_generated_field_name(proto_field_name)
                );
                if binding.optional {
                    format!("{expr} ?? undefined")
                } else {
                    format!(
                        "requiredField({expr}, {}, {})",
                        typescript_string_literal("resource"),
                        typescript_string_literal(&typescript_generated_field_name(
                            &binding.field_name
                        )),
                    )
                }
            } else {
                format!("request.{}", typescript_generated_field_name(field_name))
            }
        }
        ResolvedResourceBindingSource::ResultField {
            proto_field_name, ..
        } => {
            let expr = format!(
                "result.{}",
                typescript_generated_field_name(proto_field_name)
            );
            if binding.optional {
                format!("{expr} ?? undefined")
            } else {
                format!(
                    "requiredField({expr}, {}, {})",
                    typescript_string_literal("resource"),
                    typescript_string_literal(&typescript_generated_field_name(
                        &binding.field_name
                    )),
                )
            }
        }
    }
}

fn operation_input_to_proto_expr_for_resource_method(operation: &RenderedOperation<'_>) -> String {
    operation
        .input_to_proto_expr
        .replacen("request", "(request as any)", 1)
}

fn render_operation_client_methods(
    output: &mut String,
    service_name: &str,
    operation: &RenderedOperation<'_>,
) {
    let returns_direct =
        operation.output_transform_expr.is_some() || operation.output_resource_return.is_some();
    if operation.input_type_parameters.is_empty() {
        output.push_str("  public async ");
        output.push_str(&operation.attr_name);
        output.push_str("(\n");
    } else {
        render_named_generic_function_start(
            output,
            &format!("  public async {}", operation.attr_name),
            &operation.input_type_parameters,
            2,
        );
    }
    output.push_str("    request: ");
    output.push_str(&operation.input_annotation);
    output.push_str(",\n");
    if returns_direct {
        output.push_str("  ): Promise<");
        output.push_str(&operation.output_annotation);
        output.push_str("> {\n");
    } else {
        output.push_str("  ): Promise<workflow.NexusOperationHandle<");
        output.push_str(&operation.output_annotation);
        output.push_str(">> {\n");
        output.push_str("    return await this.client.startOperation(\n");
        output.push_str("      ");
        output.push_str(service_name);
        output.push_str(".operations.");
        output.push_str(&operation.attr_name);
        output.push_str(",\n");
        output.push_str("      ");
        output.push_str(&operation.input_to_proto_expr);
        output.push_str(",\n");
        output.push_str("    );\n");
    }
    if returns_direct {
        output.push_str("    const requestProto = ");
        output.push_str(&operation.input_to_proto_expr);
        output.push_str(";\n");
        output.push_str("    const handle = await this.client.startOperation(\n");
        output.push_str("      ");
        output.push_str(service_name);
        output.push_str(".operations.");
        output.push_str(&operation.attr_name);
        output.push_str(",\n");
        output.push_str("      requestProto,\n");
        output.push_str("    );\n");
    }
    if let Some(transform_expr) = &operation.output_transform_expr {
        output.push_str("    const result = await handle.result();\n");
        output.push_str("    return ");
        output.push_str(transform_expr);
        output.push_str(";\n");
    } else if let Some(resource_return) = &operation.output_resource_return {
        output.push_str("    const result = await handle.result();\n");
        output.push_str("    return new ");
        output.push_str(&resource_return.resource_type_name);
        output.push_str("(\n");
        output.push_str("      this,\n");
        for binding in &resource_return.bindings {
            output.push_str("      ");
            output.push_str(&resource_return_binding_expr_typescript(binding));
            output.push_str(",\n");
        }
        output.push_str("    );\n");
    }
    output.push_str("  }\n");
}

fn required_field_expr(value_expr: &str, owner_name: &str, field_name: &str) -> String {
    format!(
        "requiredField({value_expr}, {}, {})",
        typescript_string_literal(owner_name),
        typescript_string_literal(field_name)
    )
}

pub(crate) fn field_name(field: &FieldDescriptorProto, explicit_name: Option<&str>) -> String {
    match explicit_name {
        Some(name) => typescript_generated_field_name(name),
        None => {
            let name = field
                .json_name
                .as_deref()
                .or_else(|| field.name.as_deref())
                .expect("descriptor fields should be named");
            typescript_ident(name)
        }
    }
}

fn typescript_ident(name: &str) -> String {
    if is_typescript_keyword(name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

fn typescript_generated_field_name(name: &str) -> String {
    typescript_ident(&name.to_lower_camel_case())
}

fn typescript_string_literal(value: &str) -> String {
    format!("{value:?}")
}

fn is_typescript_keyword(name: &str) -> bool {
    matches!(
        name,
        "break"
            | "case"
            | "catch"
            | "class"
            | "const"
            | "continue"
            | "debugger"
            | "default"
            | "delete"
            | "do"
            | "else"
            | "enum"
            | "export"
            | "extends"
            | "false"
            | "finally"
            | "for"
            | "function"
            | "if"
            | "import"
            | "in"
            | "instanceof"
            | "new"
            | "null"
            | "return"
            | "super"
            | "switch"
            | "this"
            | "throw"
            | "true"
            | "try"
            | "typeof"
            | "var"
            | "void"
            | "while"
            | "with"
            | "yield"
            | "as"
            | "implements"
            | "interface"
            | "let"
            | "package"
            | "private"
            | "protected"
            | "public"
            | "static"
    )
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::PathBuf;
    use std::process::Command;
    use std::time::{SystemTime, UNIX_EPOCH};

    use super::TYPESCRIPT_SUPPORT_MARKER;
    use crate::SupportFiles;
    use crate::descriptors::DescriptorIndex;
    use crate::generator::generate_source;
    use crate::language::Language;
    use crate::spec::ApiSpec;

    fn sample_input_path(root: &std::path::Path) -> PathBuf {
        root.join("examples/inputs/workflow-service.wit")
    }

    fn sample_typescript_output_path(root: &std::path::Path) -> PathBuf {
        root.join("examples/typescript/workflow-service/output.ts")
    }

    fn sample_support_files(root: &std::path::Path) -> SupportFiles {
        SupportFiles {
            typescript: Some(
                fs::read_to_string(
                    root.join("builtins/nexus-temporal-types/typescript/model_overrides.ts"),
                )
                .unwrap(),
            ),
            ..SupportFiles::default()
        }
    }

    fn ensure_typescript_dependencies(root: &std::path::Path) {
        let example_dir = root.join("examples/typescript");
        if example_dir.join("node_modules").exists() {
            return;
        }

        let status = Command::new("npm")
            .current_dir(&example_dir)
            .args(["install", "--no-fund", "--no-audit"])
            .status()
            .unwrap();
        assert!(status.success());
    }

    fn format_typescript_output(root: &std::path::Path, output: &str) -> String {
        ensure_typescript_dependencies(root);
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let temp_path = std::env::temp_dir().join(format!("nexus-api-gen-typescript-{unique}.ts"));
        fs::write(&temp_path, output).unwrap();
        let status = Command::new("npm")
            .current_dir(root.join("examples/typescript"))
            .args([
                "exec",
                "--",
                "prettier",
                "--write",
                temp_path.to_str().unwrap(),
            ])
            .status()
            .unwrap();
        assert!(status.success());
        let formatted = fs::read_to_string(&temp_path).unwrap();
        fs::remove_file(temp_path).unwrap();
        formatted
    }

    #[test]
    fn renders_sample_output() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let spec =
            ApiSpec::load_for_language(Language::TypeScript, &sample_input_path(&root)).unwrap();
        let descriptors =
            DescriptorIndex::load(&root.join("examples/descriptors/temporal_api.bin")).unwrap();
        let support = sample_support_files(&root);
        let output = generate_source(Language::TypeScript, &spec, &descriptors, &support).unwrap();
        let output = format_typescript_output(&root, &output);
        let expected = std::fs::read_to_string(sample_typescript_output_path(&root)).unwrap();

        assert_eq!(output, expected);
    }

    #[test]
    fn renders_required_fields_and_custom_message_types() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let spec =
            ApiSpec::load_for_language(Language::TypeScript, &sample_input_path(&root)).unwrap();
        let descriptors =
            DescriptorIndex::load(&root.join("examples/descriptors/temporal_api.bin")).unwrap();
        let support = sample_support_files(&root);
        let output = generate_source(Language::TypeScript, &spec, &descriptors, &support).unwrap();

        assert!(output.contains(TYPESCRIPT_SUPPORT_MARKER));
        assert!(output.contains("export function retryPolicyFromProto("));
        assert!(output.contains("type _RequestWithFunctionField<"));
        assert!(output.contains("type _RequestWithArgumentsField<"));
        assert!(output.contains("type SignalWithStartWorkflowExecutionRequestBase = {"));
        assert!(output.contains("export type SignalWithStartWorkflowExecutionRequest<"));
        assert!(output.contains(
            "WorkflowFn extends (...args: any[]) => Promise<any> = (...args: any[]) => Promise<any>,"
        ));
        assert!(output.contains(
            "SignalValue extends workflow.SignalDefinition<any[]> = workflow.SignalDefinition<any[]>"
        ));
        assert!(output.contains("> = _RequestWithArgumentsField<"));
        assert!(output.contains(
            "SignalValue extends workflow.SignalDefinition<infer Args, any> ? Args : never"
        ));
        assert!(output.contains(
            "_RequestWithFunctionField<WorkflowFn, SignalWithStartWorkflowExecutionRequestBase, \"workflow\", \"input\">"
        ));
        assert!(output.contains("workflowId: string;"));
        assert!(output.contains("taskQueue: string;"));
        assert!(output.contains("workflowRunTimeout?: common.Duration;"));
        assert!(output.contains("workflowIdReusePolicy?: common.WorkflowIdReusePolicy;"));
        assert!(output.contains("workflowIdConflictPolicy?: common.WorkflowIdConflictPolicy;"));
        assert!(output.contains("memo?: Record<string, unknown>;"));
        assert!(output.contains(
            "searchAttributes?: common.TypedSearchAttributes | common.SearchAttributes;"
        ));
        assert!(output.contains("versioningOverride?: common.VersioningOverride;"));
        assert!(output.contains("priority?: common.Priority;"));
        assert!(!output.contains("signal: string;"));
        assert!(!output.contains("namespace?: string;"));
        assert!(output.contains("namespace: workflow.workflowInfo().namespace,"));
        assert!(output.contains("retryPolicy: common.RetryPolicy;"));
        assert!(output.contains("workflowType: workflowTypeToProto("));
        assert!(output.contains("workflow_function_name("));
        assert!(output.contains("input: _RequestArgsToPayloads(model.input),"));
        assert!(output.contains("signalInput: _RequestArgsToPayloads(model.signalInput),"));
        assert!(output.contains(
            "signalName: ((value) => typeof value === 'string' ? value : (value.name))("
        ));
        assert!(output.contains("workflowType: workflowTypeToProto("));
        assert!(output.contains("taskQueue: taskQueueToProto("));
        assert!(output.contains(
            "workflowRunTimeout: model.workflowRunTimeout == null ? undefined : durationToProto(model.workflowRunTimeout),"
        ));
        assert!(output.contains("memo: model.memo == null ? undefined : memoToProto(model.memo),"));
        assert!(output.contains(
            "searchAttributes: model.searchAttributes == null ? undefined : searchAttributesToProto(model.searchAttributes),"
        ));
        assert!(output.contains(
            "priority: model.priority == null ? undefined : priorityToProto(model.priority),"
        ));
        assert!(output.contains(
            "versioningOverride: model.versioningOverride == null ? undefined : versioningOverrideToProto(model.versioningOverride),"
        ));
        assert!(output.contains("export function taskQueueFromProto("));
        assert!(output.contains("export function taskQueueToProto("));
        assert!(output.contains(
            "): temporal.api.workflowservice.v1.ISignalWithStartWorkflowExecutionRequest | undefined {"
        ));
        assert!(output.contains("requiredField(model.retryPolicy"));
        assert!(output.contains("request: common.RetryPolicy"));
        assert!(output.contains("retryPolicyToProto(request)"));
        assert!(!output.contains("header?:"));
        assert!(!output.contains("export interface Header"));
        assert!(!output.contains("export interface WorkflowType"));
        assert!(!output.contains("export interface TaskQueue"));
        assert!(!output.contains("export interface Duration"));
        assert!(!output.contains("export interface Memo"));
        assert!(!output.contains("export interface SearchAttributes"));
        assert!(!output.contains("export interface Priority"));
        assert!(!output.contains("export interface VersioningOverride"));
        assert!(!output.contains("SignalWithStartWorkflowExecutionRequest = {\n  fromProto("));
        assert!(!output.contains("SignalWithStartWorkflowExecutionRequest.fromProto"));
        assert!(!output.contains("export interface SignalWithStartWorkflowExecutionRequest {"));
        assert!(!output.contains("export interface RetryPolicy"));
        assert!(!output.contains("export enum WorkflowIdReusePolicy"));
        assert!(!output.contains("export enum WorkflowIdConflictPolicy"));
        assert!(!output.contains("signalWithStartWorkflow("));
        assert!(output.contains("public async signalWithStartWorkflowExecution<"));
        assert!(output.contains(
            "request: SignalWithStartWorkflowExecutionRequest<WorkflowFn, SignalValue>,"
        ));
        assert!(!output.contains("from './model_overrides.ts'"));
    }

    #[test]
    fn renders_typescript_enum_overrides() {
        let wit = r#"
package temporal:nexus@1.0.0;

world system {
  export workflow-service;
}

/// @nexus.endpoint "__temporal_system"
interface workflow-service {
  use nexus:temporal-types/model@1.0.0.{workflow-id-reuse-policy};

  /// @nexus.proto "temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionRequest"
  record signal-with-start-workflow-execution-request {
    workflow-id: string,
    workflow-id-reuse-policy: option<workflow-id-reuse-policy>,
  }

  /// @nexus.proto "temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse"
  record signal-with-start-workflow-execution-response {
    run-id: option<string>,
  }

  signal-with-start-workflow-execution: func(
    request: signal-with-start-workflow-execution-request,
  ) -> signal-with-start-workflow-execution-response;
}
"#;
        let spec =
            ApiSpec::parse_for_language(Language::TypeScript, wit, PathBuf::from("inline.wit"))
                .unwrap();
        let descriptors = DescriptorIndex::load(
            &PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("examples/descriptors/temporal_api.bin"),
        )
        .unwrap();
        let output = generate_source(
            Language::TypeScript,
            &spec,
            &descriptors,
            &SupportFiles::default(),
        )
        .unwrap();

        assert!(output.contains("workflowIdReusePolicy?: common.WorkflowIdReusePolicy;"));
        assert!(output.contains(
            "workflowIdReusePolicy: model.workflowIdReusePolicy == null ? undefined : workflowIdReusePolicyToProto(model.workflowIdReusePolicy)"
        ));
        assert!(!output.contains("export enum WorkflowIdReusePolicy"));
    }

    #[test]
    fn rejects_missing_service_endpoint() {
        let wit = r#"
package temporal:nexus@1.0.0;

world system {
  export example-service;
}

interface example-service {
  /// @nexus.proto "temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionRequest"
  record example-request {
    workflow-id: string,
  }

  /// @nexus.proto "temporal.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse"
  record example-response {
    run-id: option<string>,
  }

  example-operation: func(request: example-request) -> example-response;
}
"#;
        let spec =
            ApiSpec::parse_for_language(Language::TypeScript, wit, PathBuf::from("inline.wit"))
                .unwrap();
        let descriptors = DescriptorIndex::load(
            &PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("examples/descriptors/temporal_api.bin"),
        )
        .unwrap();

        let error = generate_source(
            Language::TypeScript,
            &spec,
            &descriptors,
            &SupportFiles::default(),
        )
        .unwrap_err();
        assert_eq!(
            error.to_string(),
            "service `ExampleService` is missing an endpoint"
        );
    }
}
