# Generated by nexus-api-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

import collections.abc
import typing
import typing_extensions
from temporalio import workflow

from ..service import WorkflowService
from ..models import StartWorkflowExecutionRequest
from .._resources import StartedWorkflow


def _nexus_normalize_function_args(
    value: object | tuple[object, ...] | None,
) -> tuple[object, ...] | None:
    if value is None:
        return None
    if isinstance(value, tuple):
        return typing.cast(tuple[object, ...], value)
    return (value,)


FirstWorkflowArg = typing.TypeVar("FirstWorkflowArg")
RemainingWorkflowArgs = typing_extensions.TypeVarTuple("RemainingWorkflowArgs")


async def _start_workflow(
    request: StartWorkflowExecutionRequest,
) -> StartedWorkflow:
    request_proto = request.to_proto()
    nexus_client: workflow.NexusClient[WorkflowService] = workflow.create_nexus_client(
        service=WorkflowService,
        endpoint="__temporal_system",
    )
    handle = await nexus_client.start_operation(
        WorkflowService.start_workflow,
        request_proto,
    )
    result = await handle
    return StartedWorkflow(
        namespace=request_proto.namespace,
        workflow_id=request.workflow_id,
        run_id=result.run_id or None,
    )


@typing.overload
async def start_workflow(
    *,
    workflow_id: str,
    workflow: str,
    task_queue: str,
    input: tuple[typing.Any, ...] | None = ...,
) -> StartedWorkflow: ...


@typing.overload
async def start_workflow(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[[typing.Any], collections.abc.Awaitable[object]],
    task_queue: str,
) -> StartedWorkflow: ...


@typing.overload
async def start_workflow(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg], collections.abc.Awaitable[object]
    ],
    task_queue: str,
    input: FirstWorkflowArg,
) -> StartedWorkflow: ...


@typing.overload
async def start_workflow(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
        collections.abc.Awaitable[object],
    ],
    task_queue: str,
    input: tuple[FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
) -> StartedWorkflow: ...


async def start_workflow(
    *,
    workflow_id: str,
    workflow: str | collections.abc.Callable[..., collections.abc.Awaitable[object]],
    task_queue: str,
    input: object | tuple[object, ...] | None = None,
) -> StartedWorkflow:
    normalized_input = _nexus_normalize_function_args(input)
    request = StartWorkflowExecutionRequest(
        workflow_id=workflow_id,
        workflow=workflow,
        task_queue=task_queue,
        input=normalized_input,
    )
    return await _start_workflow(request)
