# Generated by nexgen. DO NOT EDIT!

from __future__ import annotations

import typing
import pydantic

from ..._definitions import (
    SpecInt,
    _emit_set_fields,
    _reject_explicit_null,
)


class BlockStyle(pydantic.BaseModel):
    """Non-cyclic helper; stays in the content_block module. All members optional."""

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        strict=True, populate_by_name=True, validate_assignment=True, extra="forbid"
    )

    bold: bool | None = pydantic.Field(default=None)

    indent: SpecInt | None = pydantic.Field(default=None, ge=0)

    @pydantic.field_validator("bold", "indent", mode="after")
    @classmethod
    def _reject_null(cls, value: object) -> object:
        return _reject_explicit_null(value)

    @pydantic.model_serializer(mode="wrap")
    def _serialize(
        self,
        handler: typing.Callable[[pydantic.BaseModel], typing.Any],
    ) -> dict[str, object]:
        return _emit_set_fields(self, handler)
