# Generated by nexgen. DO NOT EDIT!

from __future__ import annotations

import typing
import pydantic

from ..._definitions import (
    SpecInt,
    _emit_set_fields,
    _reject_explicit_null,
)


class PageMeta(pydantic.BaseModel):
    """Non-cyclic helper. Referenced only by Page, references nothing recursive, so it
    stays in the content_page module even though Page is hoisted.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        strict=True, populate_by_name=True, validate_assignment=True, extra="forbid"
    )

    author: str = pydantic.Field()

    word_count: SpecInt | None = pydantic.Field(default=None, alias="wordCount")

    @pydantic.field_validator("word_count", mode="after")
    @classmethod
    def _reject_null(cls, value: object) -> object:
        return _reject_explicit_null(value)

    @pydantic.model_serializer(mode="wrap")
    def _serialize(
        self,
        handler: typing.Callable[[pydantic.BaseModel], typing.Any],
    ) -> dict[str, object]:
        return _emit_set_fields(self, handler)
