# Generated by nexus-api-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

import collections.abc
import dataclasses
import typing
import temporalio.api.common.v1.message_pb2
import temporalio.api.workflowservice.v1.request_response_pb2

from ._support import (
    payloads_to_proto,
    task_queue_to_proto,
    workflow_namespace,
    workflow_type_to_proto,
)


@dataclasses.dataclass(slots=True)
class StartWorkflowExecutionRequest:
    workflow_id: str
    workflow: str | collections.abc.Callable[..., collections.abc.Awaitable[typing.Any]]
    task_queue: str
    input: tuple[typing.Any, ...] | None = None

    def to_proto(
        self,
    ) -> temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionRequest:
        message = temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionRequest()
        message.workflow_id = self.workflow_id
        message.workflow_type.CopyFrom(workflow_type_to_proto(self.workflow))
        message.task_queue.CopyFrom(task_queue_to_proto(self.task_queue))
        if self.input is not None:
            message.input.CopyFrom(payloads_to_proto(self.input))
        message.namespace = workflow_namespace()
        return message


@dataclasses.dataclass(slots=True)
class RequestCancelWorkflowExecutionRequest:
    workflow_execution: WorkflowExecution
    reason: str | None = None

    def to_proto(
        self,
    ) -> temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionRequest:
        message = temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionRequest()
        message.workflow_execution.CopyFrom(self.workflow_execution.to_proto())
        if self.reason is not None:
            message.reason = self.reason
        message.namespace = workflow_namespace()
        return message


@dataclasses.dataclass(slots=True)
class WorkflowExecution:
    workflow_id: str
    run_id: str | None = None

    @classmethod
    def from_proto(
        cls,
        proto: temporalio.api.common.v1.message_pb2.WorkflowExecution,
    ) -> WorkflowExecution:
        if not proto.workflow_id:
            raise ValueError("missing required field WorkflowExecution.workflow_id")
        workflow_id = proto.workflow_id
        return cls(
            workflow_id=workflow_id,
            run_id=proto.run_id,
        )

    def to_proto(self) -> temporalio.api.common.v1.message_pb2.WorkflowExecution:
        message = temporalio.api.common.v1.message_pb2.WorkflowExecution()
        message.workflow_id = self.workflow_id
        if self.run_id is not None:
            message.run_id = self.run_id
        return message


@dataclasses.dataclass(slots=True)
class RequestCancelWorkflowExecutionResponse:
    @classmethod
    def from_proto(
        cls,
        _proto: temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionResponse,
    ) -> RequestCancelWorkflowExecutionResponse:
        return cls()

    def to_proto(
        self,
    ) -> temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionResponse:
        message = temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionResponse()
        return message
