# Generated by nexus-api-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

from nexusrpc import Operation, service

import temporalio.api.activity.v1.message_pb2
import temporalio.api.common.v1.message_pb2
import temporalio.api.workflowservice.v1.request_response_pb2


@service
class WorkflowService:
    signal_with_start_workflow_execution: Operation[
        temporalio.api.workflowservice.v1.request_response_pb2.SignalWithStartWorkflowExecutionRequest,
        temporalio.api.workflowservice.v1.request_response_pb2.SignalWithStartWorkflowExecutionResponse,
    ] = Operation(name="SignalWithStartWorkflowExecution")

    retry_policy_operation: Operation[
        temporalio.api.common.v1.message_pb2.RetryPolicy,
        temporalio.api.common.v1.message_pb2.RetryPolicy,
    ] = Operation(name="RetryPolicyOperation")

    activity_options_operation: Operation[
        temporalio.api.activity.v1.message_pb2.ActivityOptions,
        temporalio.api.activity.v1.message_pb2.ActivityOptions,
    ] = Operation(name="ActivityOptionsOperation")
