# Generated by nexus-api-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

import collections.abc
import dataclasses
import typing
import typing_extensions
from datetime import timedelta
from temporalio import workflow
import temporalio.api.workflowservice.v1.request_response_pb2

from ..service import WorkflowService
from ..models import (
    RequestCancelWorkflowExecutionRequest,
    StartWorkflowExecutionRequest,
    WorkflowExecution,
)


def _nexus_normalize_function_args(
    value: object | tuple[object, ...] | None,
) -> tuple[object, ...] | None:
    if value is None:
        return None
    if isinstance(value, tuple):
        return typing.cast(tuple[object, ...], value)
    return (value,)


FirstWorkflowArg = typing.TypeVar("FirstWorkflowArg")
RemainingWorkflowArgs = typing_extensions.TypeVarTuple("RemainingWorkflowArgs")


@dataclasses.dataclass
class StartedWorkflow:
    namespace: str
    workflow_id: str
    run_id: str | None

    async def cancel(
        self,
        reason: str | None = None,
    ) -> None:
        request = RequestCancelWorkflowExecutionRequest(
            workflow_execution=WorkflowExecution(
                workflow_id=self.workflow_id, run_id=self.run_id
            ),
            reason=reason,
        )
        handle = await _cancel_workflow(request)
        await handle

    async def restart_workflow(
        self,
        workflow: str
        | collections.abc.Callable[..., collections.abc.Awaitable[object]],
        task_queue: str,
    ) -> StartedWorkflow:
        request = StartWorkflowExecutionRequest(
            workflow_id=self.workflow_id,
            workflow=workflow,
            task_queue=task_queue,
        )
        return await _restart_workflow(request)

    async def get_result(
        self,
    ) -> collections.abc.Sequence[typing.Any]:
        raise NotImplementedError("started-workflow.get_result is not yet implemented")


async def _cancel_workflow(
    request: RequestCancelWorkflowExecutionRequest,
) -> workflow.NexusOperationHandle[
    temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionResponse,
]:
    nexus_client: workflow.NexusClient[WorkflowService] = workflow.create_nexus_client(
        service=WorkflowService,
        endpoint="__temporal_system",
    )
    return await nexus_client.start_operation(
        WorkflowService.cancel_workflow,
        request.to_proto(),
    )


async def cancel_workflow(
    *,
    workflow_execution: WorkflowExecution,
    reason: str | None = None,
) -> workflow.NexusOperationHandle[
    temporalio.api.workflowservice.v1.request_response_pb2.RequestCancelWorkflowExecutionResponse,
]:
    request = RequestCancelWorkflowExecutionRequest(
        workflow_execution=workflow_execution,
        reason=reason,
    )
    return await _cancel_workflow(request)


async def _restart_workflow(
    request: StartWorkflowExecutionRequest,
) -> StartedWorkflow:
    request_proto = request.to_proto()
    nexus_client: workflow.NexusClient[WorkflowService] = workflow.create_nexus_client(
        service=WorkflowService,
        endpoint="__temporal_system",
    )
    handle = await nexus_client.start_operation(
        WorkflowService.restart_workflow,
        request_proto,
    )
    result = await handle
    return StartedWorkflow(
        namespace=request_proto.namespace,
        workflow_id=request.workflow_id,
        run_id=result.run_id or None,
    )


@typing.overload
async def restart_workflow(
    *,
    workflow_id: str,
    workflow: str,
    task_queue: str,
    input: tuple[typing.Any, ...] | None = ...,
    workflow_start_delay: timedelta | None = ...,
) -> StartedWorkflow: ...


@typing.overload
async def restart_workflow(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[[typing.Any], collections.abc.Awaitable[object]],
    task_queue: str,
    workflow_start_delay: timedelta | None = ...,
) -> StartedWorkflow: ...


@typing.overload
async def restart_workflow(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg], collections.abc.Awaitable[object]
    ],
    task_queue: str,
    input: FirstWorkflowArg,
    workflow_start_delay: timedelta | None = ...,
) -> StartedWorkflow: ...


@typing.overload
async def restart_workflow(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
        collections.abc.Awaitable[object],
    ],
    task_queue: str,
    input: tuple[FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
    workflow_start_delay: timedelta | None = ...,
) -> StartedWorkflow: ...


async def restart_workflow(
    *,
    workflow_id: str,
    workflow: str | collections.abc.Callable[..., collections.abc.Awaitable[object]],
    task_queue: str,
    input: object | tuple[object, ...] | None = None,
    workflow_start_delay: timedelta | None = None,
) -> StartedWorkflow:
    normalized_input = _nexus_normalize_function_args(input)
    request = StartWorkflowExecutionRequest(
        workflow_id=workflow_id,
        workflow=workflow,
        task_queue=task_queue,
        input=normalized_input,
        workflow_start_delay=workflow_start_delay,
    )
    return await _restart_workflow(request)
