# Generated by nexus-api-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

import dataclasses
import nexus_api_gen_runtime


@dataclasses.dataclass(slots=True)
class GetUserRequest:
    user_id: str


@dataclasses.dataclass(slots=True)
class UpdateEmailRequest:
    user_id: str
    email: str


nexus_api_gen_runtime.register_nexus_type(
    GetUserRequest, "user-service.get-user-request"
)
nexus_api_gen_runtime.register_nexus_type(
    UpdateEmailRequest, "user-service.update-email-request"
)
