# Generated by nexus-api-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

import dataclasses


@dataclasses.dataclass(slots=True)
class GetUserRequest:
    user_id: str


@dataclasses.dataclass(slots=True)
class UpdateEmailRequest:
    email: str
    user_id: str
