/// @nexus.support
///   python="support.py"
///   typescript="support.ts"
package temporal:nexus@1.0.0;

world system {
  export workflow-service;
}

/// @nexus.endpoint "__temporal_system"
interface workflow-service {
  use nexus:temporal-types/model@1.0.0.{task-queue, workflow-function};

  /// @nexus.proto "temporal.api.common.v1.WorkflowExecution"
  record workflow-execution {
    workflow-id: string,
    run-id: option<string>,
  }

  /// @nexus.proto "temporal.api.workflowservice.v1.StartWorkflowExecutionRequest"
  record start-workflow-request {
    /// @nexus.proto-field "workflow_type"
    workflow: workflow-function,
    workflow-id: string,
    task-queue: task-queue,
    /// @nexus.source
    ///   python="workflow.info().namespace"
    ///   typescript="workflow.workflowInfo().namespace"
    namespace: option<string>,
  }

  /// @nexus.proto "temporal.api.workflowservice.v1.StartWorkflowExecutionResponse"
  record start-workflow-response {
    run-id: option<string>,
    started: option<bool>,
  }

  /// @nexus.proto "temporal.api.workflowservice.v1.RequestCancelWorkflowExecutionRequest"
  record cancel-workflow-request {
    /// @nexus.source
    ///   python="workflow.info().namespace"
    ///   typescript="workflow.workflowInfo().namespace"
    namespace: option<string>,
    workflow-execution: workflow-execution,
    reason: option<string>,
  }

  /// @nexus.proto "temporal.api.workflowservice.v1.RequestCancelWorkflowExecutionResponse"
  record cancel-workflow-response {
  }

  /// @nexus.output-transform
  ///   python-type="StartedWorkflowHandle[typing.Any]"
  ///   python="started_workflow_handle_from_proto(request.workflow_id, result.run_id)"
  ///   typescript-type="StartedWorkflowHandle"
  ///   typescript="startedWorkflowHandleFromProto(request.workflowId, result.runId ?? undefined)"
  start-workflow: func(request: start-workflow-request) -> start-workflow-response;

  cancel-workflow: func(request: cancel-workflow-request) -> cancel-workflow-response;
}
