// Generated by nexus-api-gen. DO NOT EDIT!

import * as common from "@temporalio/common";
import * as nexus from "nexus-rpc";
import type { google, temporal } from "@temporalio/proto";
import * as workflow from "@temporalio/workflow";

// Included from support.$typescript
export function retryPolicyFromProto(
  proto: temporal.api.common.v1.IRetryPolicy,
): common.RetryPolicy {
  return common.decompileRetryPolicy(proto) ?? {};
}

export function retryPolicyToProto(
  retryPolicy: common.RetryPolicy,
): temporal.api.common.v1.IRetryPolicy {
  return common.compileRetryPolicy(retryPolicy);
}

export function workflowTypeFromProto(
  proto: temporal.api.common.v1.IWorkflowType,
): string | common.Workflow {
  return proto.name ?? "";
}

export function workflowTypeToProto(
  workflowType: string | common.Workflow,
): temporal.api.common.v1.IWorkflowType {
  return { name: workflow_function_name(workflowType) };
}

export function workflow_function_name(
  value: string | common.Workflow,
): string {
  return typeof value === "string" ? value : common.extractWorkflowType(value);
}

export function signal_function_to_proto(
  value: string | workflow.SignalDefinition<any[]>,
): string {
  return typeof value === "string" ? value : value.name;
}

export function taskQueueFromProto(
  proto: temporal.api.taskqueue.v1.ITaskQueue,
): string {
  return proto.name ?? "";
}

export function taskQueueToProto(
  taskQueue: string,
): temporal.api.taskqueue.v1.ITaskQueue {
  return { name: taskQueue };
}

export function payloadFromProto(
  payload: temporal.api.common.v1.IPayload,
): common.Payload {
  return payload;
}

export function payloadToProto(
  payload: common.Payload,
): temporal.api.common.v1.IPayload {
  return payload;
}

export function memoFromProto(
  proto: temporal.api.common.v1.IMemo,
): Record<string, unknown> {
  return (
    common.mapFromPayloads(
      common.defaultPayloadConverter,
      proto.fields ?? undefined,
    ) ?? {}
  );
}

export function memoToProto(
  memo: Record<string, unknown>,
): temporal.api.common.v1.IMemo {
  return {
    fields: common.mapToPayloads(common.defaultPayloadConverter, memo),
  };
}

export function durationFromProto(
  proto: google.protobuf.IDuration,
): common.Duration {
  return common.optionalTsToMs(proto)!;
}

export function durationToProto(
  duration: common.Duration,
): google.protobuf.IDuration {
  return common.msToTs(duration);
}

function typedSearchAttributePayload(
  value: unknown,
  type: common.SearchAttributeType,
): common.Payload {
  const payload = common.defaultPayloadConverter.toPayload(value);
  payload.metadata ??= {};
  payload.metadata.type = common.u8(
    common.TypedSearchAttributes.toMetadataType(type),
  );
  return payload;
}

function isValidSearchAttributeValue(
  type: common.SearchAttributeType,
  value: unknown,
): boolean {
  switch (type) {
    case common.SearchAttributeType.TEXT:
    case common.SearchAttributeType.KEYWORD:
      return typeof value === "string";
    case common.SearchAttributeType.INT:
      return Number.isInteger(value);
    case common.SearchAttributeType.DOUBLE:
      return typeof value === "number";
    case common.SearchAttributeType.BOOL:
      return typeof value === "boolean";
    case common.SearchAttributeType.DATETIME:
      return value instanceof Date;
    case common.SearchAttributeType.KEYWORD_LIST:
      return (
        Array.isArray(value) && value.every((item) => typeof item === "string")
      );
    default:
      return false;
  }
}

function typedSearchAttributePairFromPayload(
  name: string,
  payload: common.Payload,
): common.SearchAttributePair | undefined {
  const metadataType = payload.metadata?.type;
  if (metadataType == null) {
    return undefined;
  }
  const type = common.TypedSearchAttributes.toSearchAttributeType(
    common.str(metadataType),
  );
  if (type == null) {
    return undefined;
  }
  let value: unknown = common.defaultPayloadConverter.fromPayload(payload);
  if (
    type !== common.SearchAttributeType.KEYWORD_LIST &&
    Array.isArray(value)
  ) {
    if (value.length !== 1) {
      return undefined;
    }
    value = value[0];
  }
  if (type === common.SearchAttributeType.DATETIME && value != null) {
    value = new Date(value as string);
  }
  if (!isValidSearchAttributeValue(type, value)) {
    return undefined;
  }
  return {
    key: { name, type },
    value,
  } as common.SearchAttributePair;
}

export function searchAttributesFromProto(
  proto: temporal.api.common.v1.ISearchAttributes,
): common.TypedSearchAttributes | common.SearchAttributes {
  const indexedFields = proto.indexedFields ?? {};
  const typedPairs: common.SearchAttributePair[] = [];
  for (const [name, payload] of Object.entries(indexedFields)) {
    const pair = typedSearchAttributePairFromPayload(name, payload);
    if (pair == null) {
      const decoded =
        common.mapFromPayloads(common.defaultPayloadConverter, indexedFields) ??
        {};
      return Object.fromEntries(
        Object.entries(decoded).flatMap(([key, value]) => {
          if (value == null) {
            return [];
          }
          if (Array.isArray(value)) {
            return value.length === 0 ? [] : [[key, value]];
          }
          return [[key, [value]]];
        }),
      ) as common.SearchAttributes;
    }
    typedPairs.push(pair);
  }
  return new common.TypedSearchAttributes(typedPairs);
}

export function searchAttributesToProto(
  searchAttributes: common.TypedSearchAttributes | common.SearchAttributes,
): temporal.api.common.v1.ISearchAttributes {
  if (searchAttributes instanceof common.TypedSearchAttributes) {
    return {
      indexedFields: Object.fromEntries(
        searchAttributes
          .getAll()
          .map((pair): [string, common.Payload] => [
            pair.key.name,
            typedSearchAttributePayload(pair.value, pair.key.type),
          ]),
      ),
    };
  }
  return {
    indexedFields: common.mapToPayloads(
      common.defaultPayloadConverter,
      searchAttributes,
    ),
  };
}

export function priorityFromProto(
  proto: temporal.api.common.v1.IPriority,
): common.Priority {
  return common.decodePriority(proto);
}

export function priorityToProto(
  priority: common.Priority,
): temporal.api.common.v1.IPriority {
  return common.compilePriority(priority);
}

const VERSIONING_BEHAVIOR_PINNED = 1;
const VERSIONING_BEHAVIOR_AUTO_UPGRADE = 2;
const PINNED_OVERRIDE_BEHAVIOR_PINNED = 1;

export function versioningOverrideFromProto(
  proto: temporal.api.workflow.v1.IVersioningOverride,
): common.VersioningOverride | undefined {
  if (
    proto.autoUpgrade ||
    proto.behavior === VERSIONING_BEHAVIOR_AUTO_UPGRADE
  ) {
    return "AUTO_UPGRADE";
  }
  const pinnedVersion = proto.pinned?.version;
  if (pinnedVersion?.deploymentName != null && pinnedVersion.buildId != null) {
    return {
      pinnedTo: {
        deploymentName: pinnedVersion.deploymentName,
        buildId: pinnedVersion.buildId,
      },
    };
  }
  if (
    proto.deployment?.seriesName != null &&
    proto.deployment.buildId != null
  ) {
    return {
      pinnedTo: {
        deploymentName: proto.deployment.seriesName,
        buildId: proto.deployment.buildId,
      },
    };
  }
  return undefined;
}

export function versioningOverrideToProto(
  versioningOverride: common.VersioningOverride,
): temporal.api.workflow.v1.IVersioningOverride {
  if (versioningOverride === "AUTO_UPGRADE") {
    return {
      behavior: VERSIONING_BEHAVIOR_AUTO_UPGRADE,
      autoUpgrade: true,
    };
  }
  return {
    behavior: VERSIONING_BEHAVIOR_PINNED,
    pinnedVersion: common.toCanonicalString(versioningOverride.pinnedTo),
    pinned: {
      behavior: PINNED_OVERRIDE_BEHAVIOR_PINNED,
      version: {
        deploymentName: versioningOverride.pinnedTo.deploymentName,
        buildId: versioningOverride.pinnedTo.buildId,
      },
    },
  };
}

export function workflowIdReusePolicyFromProto(
  policy: temporal.api.enums.v1.WorkflowIdReusePolicy,
): common.WorkflowIdReusePolicy | undefined {
  return common.decodeWorkflowIdReusePolicy(policy);
}

export function workflowIdReusePolicyToProto(
  policy: common.WorkflowIdReusePolicy,
): temporal.api.enums.v1.WorkflowIdReusePolicy | undefined {
  return common.encodeWorkflowIdReusePolicy(policy);
}

export function workflowIdConflictPolicyFromProto(
  policy: temporal.api.enums.v1.WorkflowIdConflictPolicy,
): common.WorkflowIdConflictPolicy | undefined {
  return common.decodeWorkflowIdConflictPolicy(policy);
}

export function workflowIdConflictPolicyToProto(
  policy: common.WorkflowIdConflictPolicy,
): temporal.api.enums.v1.WorkflowIdConflictPolicy | undefined {
  return common.encodeWorkflowIdConflictPolicy(policy);
}

function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

type _RequestWithFunctionField<
  Fn extends (...args: any[]) => any,
  Base,
  Field extends string,
  ArgsField extends string,
> =
  | (Base & { [K in Field]: string } & {
      [K in ArgsField]?: ReadonlyArray<unknown>;
    })
  | (Base & { [K in Field]: Fn } & (Parameters<Fn> extends [any, ...any[]]
        ? { [K in ArgsField]: Parameters<Fn> | Readonly<Parameters<Fn>> }
        : { [K in ArgsField]?: Parameters<Fn> | Readonly<Parameters<Fn>> }));

type _RequestWithArgumentsField<
  Value,
  Args extends any[],
  Base,
  Field extends string,
  ArgsField extends string,
> =
  | (Base & { [K in Field]: string } & {
      [K in ArgsField]?: ReadonlyArray<unknown>;
    })
  | (Base & { [K in Field]: Value } & (Args extends [any, ...any[]]
        ? { [K in ArgsField]: Args | Readonly<Args> }
        : { [K in ArgsField]?: Args | Readonly<Args> }));

function _RequestArgsToPayloads(
  args: ReadonlyArray<unknown> | undefined,
): temporal.api.common.v1.IPayloads | undefined {
  if (args == null) {
    return undefined;
  }
  const payloads = common.toPayloads(common.defaultPayloadConverter, ...args);
  return payloads == null ? undefined : { payloads };
}

type SignalWithStartWorkflowExecutionRequestBase = {
  workflowId: string;
  taskQueue: string;
  workflowExecutionTimeout?: common.Duration;
  workflowRunTimeout?: common.Duration;
  workflowTaskTimeout?: common.Duration;
  identity?: string;
  requestId?: string;
  workflowIdReusePolicy?: common.WorkflowIdReusePolicy;
  workflowIdConflictPolicy?: common.WorkflowIdConflictPolicy;
  retryPolicy?: common.RetryPolicy;
  cronSchedule?: string;
  memo?: Record<string, unknown>;
  searchAttributes?: common.TypedSearchAttributes | common.SearchAttributes;
  userMetadata?: UserMetadata;
  versioningOverride?: common.VersioningOverride;
  priority?: common.Priority;
};

export type SignalWithStartWorkflowExecutionRequest<
  WorkflowFn extends (...args: any[]) => Promise<any> = (
    ...args: any[]
  ) => Promise<any>,
  SignalValue extends workflow.SignalDefinition<any[]> =
    workflow.SignalDefinition<any[]>,
> = _RequestWithArgumentsField<
  SignalValue,
  SignalValue extends workflow.SignalDefinition<infer Args, any> ? Args : never,
  _RequestWithFunctionField<
    WorkflowFn,
    SignalWithStartWorkflowExecutionRequestBase,
    "workflow",
    "input"
  >,
  "signal",
  "signalInput"
>;

export const SignalWithStartWorkflowExecutionRequest = {
  toProto<
    WorkflowFn extends (...args: any[]) => Promise<any> = (
      ...args: any[]
    ) => Promise<any>,
    SignalValue extends workflow.SignalDefinition<any[]> =
      workflow.SignalDefinition<any[]>,
  >(
    model:
      | SignalWithStartWorkflowExecutionRequest<WorkflowFn, SignalValue>
      | null
      | undefined,
  ):
    | temporal.api.workflowservice.v1.ISignalWithStartWorkflowExecutionRequest
    | undefined {
    if (model == null) {
      return undefined;
    }
    return {
      workflowId: requiredField(
        model.workflowId,
        "SignalWithStartWorkflowExecutionRequest",
        "workflowId",
      ),
      workflowType: workflowTypeToProto(
        requiredField(
          model.workflow,
          "SignalWithStartWorkflowExecutionRequest",
          "workflow",
        ),
      ),
      taskQueue: taskQueueToProto(
        requiredField(
          model.taskQueue,
          "SignalWithStartWorkflowExecutionRequest",
          "taskQueue",
        ),
      ),
      input: _RequestArgsToPayloads(model.input),
      workflowExecutionTimeout:
        model.workflowExecutionTimeout == null
          ? undefined
          : durationToProto(model.workflowExecutionTimeout),
      workflowRunTimeout:
        model.workflowRunTimeout == null
          ? undefined
          : durationToProto(model.workflowRunTimeout),
      workflowTaskTimeout:
        model.workflowTaskTimeout == null
          ? undefined
          : durationToProto(model.workflowTaskTimeout),
      identity: model.identity,
      requestId: model.requestId,
      workflowIdReusePolicy:
        model.workflowIdReusePolicy == null
          ? undefined
          : workflowIdReusePolicyToProto(model.workflowIdReusePolicy),
      workflowIdConflictPolicy:
        model.workflowIdConflictPolicy == null
          ? undefined
          : workflowIdConflictPolicyToProto(model.workflowIdConflictPolicy),
      signalName: ((value) => (typeof value === "string" ? value : value.name))(
        requiredField(
          model.signal,
          "SignalWithStartWorkflowExecutionRequest",
          "signal",
        ),
      ),
      signalInput: _RequestArgsToPayloads(model.signalInput),
      retryPolicy:
        model.retryPolicy == null
          ? undefined
          : retryPolicyToProto(model.retryPolicy),
      cronSchedule: model.cronSchedule,
      memo: model.memo == null ? undefined : memoToProto(model.memo),
      searchAttributes:
        model.searchAttributes == null
          ? undefined
          : searchAttributesToProto(model.searchAttributes),
      userMetadata:
        model.userMetadata == null
          ? undefined
          : (UserMetadata.toProto(model.userMetadata) ?? {}),
      versioningOverride:
        model.versioningOverride == null
          ? undefined
          : versioningOverrideToProto(model.versioningOverride),
      priority:
        model.priority == null ? undefined : priorityToProto(model.priority),
      namespace: workflow.workflowInfo().namespace,
    };
  },
};

export interface Payloads {
  payloads?: common.Payload[];
}

export const Payloads = {
  fromProto(
    proto: temporal.api.common.v1.IPayloads | null | undefined,
  ): Payloads | undefined {
    if (proto == null) {
      return undefined;
    }
    return {
      payloads: proto.payloads?.map((value: any) => payloadFromProto(value)!),
    };
  },

  toProto(
    model: Payloads | null | undefined,
  ): temporal.api.common.v1.IPayloads | undefined {
    if (model == null) {
      return undefined;
    }
    return {
      payloads: model.payloads?.map((value) => payloadToProto(value)),
    };
  },
};

export interface UserMetadata {
  staticSummary?: common.Payload;
  staticDetails?: common.Payload;
}

export const UserMetadata = {
  fromProto(
    proto: temporal.api.sdk.v1.IUserMetadata | null | undefined,
  ): UserMetadata | undefined {
    if (proto == null) {
      return undefined;
    }
    return {
      staticSummary:
        proto.summary == null ? undefined : payloadFromProto(proto.summary),
      staticDetails:
        proto.details == null ? undefined : payloadFromProto(proto.details),
    };
  },

  toProto(
    model: UserMetadata | null | undefined,
  ): temporal.api.sdk.v1.IUserMetadata | undefined {
    if (model == null) {
      return undefined;
    }
    return {
      summary:
        model.staticSummary == null
          ? undefined
          : payloadToProto(model.staticSummary),
      details:
        model.staticDetails == null
          ? undefined
          : payloadToProto(model.staticDetails),
    };
  },
};

export interface ActivityOptions {
  taskQueue?: string;
  scheduleToCloseTimeout?: common.Duration;
  retryPolicy: common.RetryPolicy;
  priority?: common.Priority;
}

export const ActivityOptions = {
  fromProto(
    proto: temporal.api.activity.v1.IActivityOptions | null | undefined,
  ): ActivityOptions | undefined {
    if (proto == null) {
      return undefined;
    }
    return {
      taskQueue:
        proto.taskQueue == null
          ? undefined
          : taskQueueFromProto(proto.taskQueue),
      scheduleToCloseTimeout:
        proto.scheduleToCloseTimeout == null
          ? undefined
          : durationFromProto(proto.scheduleToCloseTimeout),
      retryPolicy: requiredField(
        retryPolicyFromProto(
          requiredField(proto.retryPolicy, "ActivityOptions", "retryPolicy"),
        ),
        "ActivityOptions",
        "retryPolicy",
      ),
      priority:
        proto.priority == null ? undefined : priorityFromProto(proto.priority),
    };
  },

  toProto(
    model: ActivityOptions | null | undefined,
  ): temporal.api.activity.v1.IActivityOptions | undefined {
    if (model == null) {
      return undefined;
    }
    return {
      taskQueue:
        model.taskQueue == null ? undefined : taskQueueToProto(model.taskQueue),
      scheduleToCloseTimeout:
        model.scheduleToCloseTimeout == null
          ? undefined
          : durationToProto(model.scheduleToCloseTimeout),
      retryPolicy: retryPolicyToProto(
        requiredField(model.retryPolicy, "ActivityOptions", "retryPolicy"),
      ),
      priority:
        model.priority == null ? undefined : priorityToProto(model.priority),
    };
  },
};

export const WorkflowService = nexus.service("WorkflowService", {
  signalWithStartWorkflowExecution: nexus.operation<
    temporal.api.workflowservice.v1.ISignalWithStartWorkflowExecutionRequest,
    temporal.api.workflowservice.v1.ISignalWithStartWorkflowExecutionResponse
  >({ name: "SignalWithStartWorkflowExecution" }),
  retryPolicyOperation: nexus.operation<
    temporal.api.common.v1.IRetryPolicy,
    temporal.api.common.v1.IRetryPolicy
  >({ name: "RetryPolicyOperation" }),
  activityOptionsOperation: nexus.operation<
    temporal.api.activity.v1.IActivityOptions,
    temporal.api.activity.v1.IActivityOptions
  >({ name: "ActivityOptionsOperation" }),
});

export class WorkflowServiceClient {
  public readonly client: workflow.NexusServiceClient<typeof WorkflowService>;

  public constructor() {
    this.client = workflow.createNexusServiceClient({
      service: WorkflowService,
      endpoint: "__temporal_system",
    });
  }

  public async signalWithStartWorkflowExecution<
    WorkflowFn extends (...args: any[]) => Promise<any> = (
      ...args: any[]
    ) => Promise<any>,
    SignalValue extends workflow.SignalDefinition<any[]> =
      workflow.SignalDefinition<any[]>,
  >(
    request: SignalWithStartWorkflowExecutionRequest<WorkflowFn, SignalValue>,
  ): Promise<workflow.ExternalWorkflowHandle> {
    const requestProto =
      SignalWithStartWorkflowExecutionRequest.toProto(request) ?? {};
    const handle = await this.client.startOperation(
      WorkflowService.operations.signalWithStartWorkflowExecution,
      requestProto,
    );
    const result = await handle.result();
    return workflow.getExternalWorkflowHandle(
      request.workflowId,
      result.runId ?? undefined,
    );
  }

  public async retryPolicyOperation(
    request: common.RetryPolicy,
  ): Promise<
    workflow.NexusOperationHandle<temporal.api.common.v1.IRetryPolicy>
  > {
    return await this.client.startOperation(
      WorkflowService.operations.retryPolicyOperation,
      retryPolicyToProto(request),
    );
  }

  public async activityOptionsOperation(
    request: ActivityOptions,
  ): Promise<
    workflow.NexusOperationHandle<temporal.api.activity.v1.IActivityOptions>
  > {
    return await this.client.startOperation(
      WorkflowService.operations.activityOptionsOperation,
      ActivityOptions.toProto(request) ?? {},
    );
  }
}
