// Generated by nexus-rpc-gen. DO NOT EDIT!

import * as common from "@temporalio/common";
import * as nexus from "nexus-rpc";
import type { google, temporal } from "@temporalio/proto";
import * as workflow from "@temporalio/workflow";

// Included from support.$typescript
export function retryPolicyFromProto(
  proto: temporal.api.common.v1.IRetryPolicy,
): common.RetryPolicy {
  return common.decompileRetryPolicy(proto) ?? {};
}

export function retryPolicyToProto(
  retryPolicy: common.RetryPolicy,
): temporal.api.common.v1.IRetryPolicy {
  return common.compileRetryPolicy(retryPolicy);
}

export function workflowTypeFromProto(
  proto: temporal.api.common.v1.IWorkflowType,
): string | common.Workflow {
  return proto.name ?? "";
}

export function workflowTypeToProto(
  workflowType: string | common.Workflow,
): temporal.api.common.v1.IWorkflowType {
  return { name: common.extractWorkflowType(workflowType) };
}

export function taskQueueFromProto(
  proto: temporal.api.taskqueue.v1.ITaskQueue,
): string {
  return proto.name ?? "";
}

export function taskQueueToProto(
  taskQueue: string,
): temporal.api.taskqueue.v1.ITaskQueue {
  return { name: taskQueue };
}

export function payloadFromProto(
  payload: temporal.api.common.v1.IPayload,
): common.Payload {
  return payload;
}

export function payloadToProto(
  payload: common.Payload,
): temporal.api.common.v1.IPayload {
  return payload;
}

export function memoFromProto(
  proto: temporal.api.common.v1.IMemo,
): Record<string, unknown> {
  return (
    common.mapFromPayloads(
      common.defaultPayloadConverter,
      proto.fields ?? undefined,
    ) ?? {}
  );
}

export function memoToProto(
  memo: Record<string, unknown>,
): temporal.api.common.v1.IMemo {
  return {
    fields: common.mapToPayloads(common.defaultPayloadConverter, memo),
  };
}

export function durationFromProto(
  proto: google.protobuf.IDuration,
): common.Duration {
  return common.optionalTsToMs(proto)!;
}

export function durationToProto(
  duration: common.Duration,
): google.protobuf.IDuration {
  return common.msToTs(duration);
}

function typedSearchAttributePayload(
  value: unknown,
  type: common.SearchAttributeType,
): common.Payload {
  const payload = common.defaultPayloadConverter.toPayload(value);
  payload.metadata ??= {};
  payload.metadata.type = common.u8(
    common.TypedSearchAttributes.toMetadataType(type),
  );
  return payload;
}

function isValidSearchAttributeValue(
  type: common.SearchAttributeType,
  value: unknown,
): boolean {
  switch (type) {
    case common.SearchAttributeType.TEXT:
    case common.SearchAttributeType.KEYWORD:
      return typeof value === "string";
    case common.SearchAttributeType.INT:
      return Number.isInteger(value);
    case common.SearchAttributeType.DOUBLE:
      return typeof value === "number";
    case common.SearchAttributeType.BOOL:
      return typeof value === "boolean";
    case common.SearchAttributeType.DATETIME:
      return value instanceof Date;
    case common.SearchAttributeType.KEYWORD_LIST:
      return (
        Array.isArray(value) && value.every((item) => typeof item === "string")
      );
    default:
      return false;
  }
}

function typedSearchAttributePairFromPayload(
  name: string,
  payload: common.Payload,
): common.SearchAttributePair | undefined {
  const metadataType = payload.metadata?.type;
  if (metadataType == null) {
    return undefined;
  }
  const type = common.TypedSearchAttributes.toSearchAttributeType(
    common.str(metadataType),
  );
  if (type == null) {
    return undefined;
  }
  let value: unknown = common.defaultPayloadConverter.fromPayload(payload);
  if (
    type !== common.SearchAttributeType.KEYWORD_LIST &&
    Array.isArray(value)
  ) {
    if (value.length !== 1) {
      return undefined;
    }
    value = value[0];
  }
  if (type === common.SearchAttributeType.DATETIME && value != null) {
    value = new Date(value as string);
  }
  if (!isValidSearchAttributeValue(type, value)) {
    return undefined;
  }
  return {
    key: { name, type },
    value,
  } as common.SearchAttributePair;
}

export function searchAttributesFromProto(
  proto: temporal.api.common.v1.ISearchAttributes,
): common.TypedSearchAttributes | common.SearchAttributes {
  const indexedFields = proto.indexedFields ?? {};
  const typedPairs: common.SearchAttributePair[] = [];
  for (const [name, payload] of Object.entries(indexedFields)) {
    const pair = typedSearchAttributePairFromPayload(name, payload);
    if (pair == null) {
      const decoded =
        common.mapFromPayloads(common.defaultPayloadConverter, indexedFields) ??
        {};
      return Object.fromEntries(
        Object.entries(decoded).flatMap(([key, value]) => {
          if (value == null) {
            return [];
          }
          if (Array.isArray(value)) {
            return value.length === 0 ? [] : [[key, value]];
          }
          return [[key, [value]]];
        }),
      ) as common.SearchAttributes;
    }
    typedPairs.push(pair);
  }
  return new common.TypedSearchAttributes(typedPairs);
}

export function searchAttributesToProto(
  searchAttributes: common.TypedSearchAttributes | common.SearchAttributes,
): temporal.api.common.v1.ISearchAttributes {
  if (searchAttributes instanceof common.TypedSearchAttributes) {
    return {
      indexedFields: Object.fromEntries(
        searchAttributes
          .getAll()
          .map((pair): [string, common.Payload] => [
            pair.key.name,
            typedSearchAttributePayload(pair.value, pair.key.type),
          ]),
      ),
    };
  }
  return {
    indexedFields: common.mapToPayloads(
      common.defaultPayloadConverter,
      searchAttributes,
    ),
  };
}

export function priorityFromProto(
  proto: temporal.api.common.v1.IPriority,
): common.Priority {
  return common.decodePriority(proto);
}

export function priorityToProto(
  priority: common.Priority,
): temporal.api.common.v1.IPriority {
  return common.compilePriority(priority);
}

const VERSIONING_BEHAVIOR_PINNED = 1;
const VERSIONING_BEHAVIOR_AUTO_UPGRADE = 2;
const PINNED_OVERRIDE_BEHAVIOR_PINNED = 1;

export function versioningOverrideFromProto(
  proto: temporal.api.workflow.v1.IVersioningOverride,
): common.VersioningOverride | undefined {
  if (
    proto.autoUpgrade ||
    proto.behavior === VERSIONING_BEHAVIOR_AUTO_UPGRADE
  ) {
    return "AUTO_UPGRADE";
  }
  const pinnedVersion = proto.pinned?.version;
  if (pinnedVersion?.deploymentName != null && pinnedVersion.buildId != null) {
    return {
      pinnedTo: {
        deploymentName: pinnedVersion.deploymentName,
        buildId: pinnedVersion.buildId,
      },
    };
  }
  if (
    proto.deployment?.seriesName != null &&
    proto.deployment.buildId != null
  ) {
    return {
      pinnedTo: {
        deploymentName: proto.deployment.seriesName,
        buildId: proto.deployment.buildId,
      },
    };
  }
  return undefined;
}

export function versioningOverrideToProto(
  versioningOverride: common.VersioningOverride,
): temporal.api.workflow.v1.IVersioningOverride {
  if (versioningOverride === "AUTO_UPGRADE") {
    return {
      behavior: VERSIONING_BEHAVIOR_AUTO_UPGRADE,
      autoUpgrade: true,
    };
  }
  return {
    behavior: VERSIONING_BEHAVIOR_PINNED,
    pinnedVersion: common.toCanonicalString(versioningOverride.pinnedTo),
    pinned: {
      behavior: PINNED_OVERRIDE_BEHAVIOR_PINNED,
      version: {
        deploymentName: versioningOverride.pinnedTo.deploymentName,
        buildId: versioningOverride.pinnedTo.buildId,
      },
    },
  };
}

export function workflowIdReusePolicyFromProto(
  policy: temporal.api.enums.v1.WorkflowIdReusePolicy,
): common.WorkflowIdReusePolicy | undefined {
  return common.decodeWorkflowIdReusePolicy(policy);
}

export function workflowIdReusePolicyToProto(
  policy: common.WorkflowIdReusePolicy,
): temporal.api.enums.v1.WorkflowIdReusePolicy | undefined {
  return common.encodeWorkflowIdReusePolicy(policy);
}

export function workflowIdConflictPolicyFromProto(
  policy: temporal.api.enums.v1.WorkflowIdConflictPolicy,
): common.WorkflowIdConflictPolicy | undefined {
  return common.decodeWorkflowIdConflictPolicy(policy);
}

export function workflowIdConflictPolicyToProto(
  policy: common.WorkflowIdConflictPolicy,
): temporal.api.enums.v1.WorkflowIdConflictPolicy | undefined {
  return common.encodeWorkflowIdConflictPolicy(policy);
}

function requiredField<T>(
  value: T | null | undefined,
  owner: string,
  field: string,
): T {
  if (value == null) {
    throw new Error(`missing required field ${owner}.${field}`);
  }
  return value;
}

type _RequestWithFunctionField<
  Fn extends (...args: any[]) => any,
  Base,
  Field extends string,
  ArgsField extends string,
> =
  | (Base & { [K in Field]: string } & {
      [K in ArgsField]?: ReadonlyArray<unknown>;
    })
  | (Base & { [K in Field]: Fn } & (Parameters<Fn> extends [any, ...any[]]
        ? { [K in ArgsField]: Parameters<Fn> | Readonly<Parameters<Fn>> }
        : { [K in ArgsField]?: Parameters<Fn> | Readonly<Parameters<Fn>> }));

type _RequestWithArgumentsField<
  Value,
  Args extends any[],
  Base,
  Field extends string,
  ArgsField extends string,
> =
  | (Base & { [K in Field]: string } & {
      [K in ArgsField]?: ReadonlyArray<unknown>;
    })
  | (Base & { [K in Field]: Value } & (Args extends [any, ...any[]]
        ? { [K in ArgsField]: Args | Readonly<Args> }
        : { [K in ArgsField]?: Args | Readonly<Args> }));

function _RequestFunctionName<Fn extends (...args: any[]) => any>(
  value: string | Fn,
): string {
  if (typeof value === "string") {
    return value;
  }
  if (value.name) {
    return value.name;
  }
  throw new TypeError("Invalid request function: the function is anonymous");
}

function _RequestArgsToPayloads(
  args: ReadonlyArray<unknown> | undefined,
): temporal.api.common.v1.IPayloads | undefined {
  if (args == null) {
    return undefined;
  }
  const payloads = common.toPayloads(common.defaultPayloadConverter, ...args);
  return payloads == null ? undefined : { payloads };
}

type StartWorkflowExecutionRequestBase = {
  workflowId: string;
  taskQueue: string;
};

export type StartWorkflowExecutionRequest<
  WorkflowFn extends (...args: any[]) => Promise<any> = (
    ...args: any[]
  ) => Promise<any>,
> = _RequestWithFunctionField<
  WorkflowFn,
  StartWorkflowExecutionRequestBase,
  "workflow",
  "input"
>;

export const StartWorkflowExecutionRequest = {
  toProto<
    WorkflowFn extends (...args: any[]) => Promise<any> = (
      ...args: any[]
    ) => Promise<any>,
  >(
    model: StartWorkflowExecutionRequest<WorkflowFn> | null | undefined,
  ):
    | temporal.api.workflowservice.v1.IStartWorkflowExecutionRequest
    | undefined {
    if (model == null) {
      return undefined;
    }
    return {
      workflowId: requiredField(
        model.workflowId,
        "StartWorkflowExecutionRequest",
        "workflowId",
      ),
      workflowType: workflowTypeToProto(
        _RequestFunctionName(
          requiredField(
            model.workflow,
            "StartWorkflowExecutionRequest",
            "workflow",
          ),
        ),
      ),
      taskQueue: taskQueueToProto(
        requiredField(
          model.taskQueue,
          "StartWorkflowExecutionRequest",
          "taskQueue",
        ),
      ),
      input: _RequestArgsToPayloads(model.input),
      namespace: workflow.workflowInfo().namespace,
    };
  },
};

export interface Payloads {
  payloads?: common.Payload[];
}

export const Payloads = {
  fromProto(
    proto: temporal.api.common.v1.IPayloads | null | undefined,
  ): Payloads | undefined {
    if (proto == null) {
      return undefined;
    }
    return {
      payloads: proto.payloads?.map((value: any) => payloadFromProto(value)!),
    };
  },

  toProto(
    model: Payloads | null | undefined,
  ): temporal.api.common.v1.IPayloads | undefined {
    if (model == null) {
      return undefined;
    }
    return {
      payloads: model.payloads?.map((value) => payloadToProto(value)),
    };
  },
};

export interface RequestCancelWorkflowExecutionRequest {
  workflowExecution: WorkflowExecution;
  reason?: string;
}

export const RequestCancelWorkflowExecutionRequest = {
  toProto(
    model: RequestCancelWorkflowExecutionRequest | null | undefined,
  ):
    | temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionRequest
    | undefined {
    if (model == null) {
      return undefined;
    }
    return {
      workflowExecution:
        WorkflowExecution.toProto(
          requiredField(
            model.workflowExecution,
            "RequestCancelWorkflowExecutionRequest",
            "workflowExecution",
          ),
        ) ?? {},
      reason: model.reason,
      namespace: workflow.workflowInfo().namespace,
    };
  },
};

export interface WorkflowExecution {
  workflowId: string;
  runId?: string;
}

export const WorkflowExecution = {
  fromProto(
    proto: temporal.api.common.v1.IWorkflowExecution | null | undefined,
  ): WorkflowExecution | undefined {
    if (proto == null) {
      return undefined;
    }
    return {
      workflowId: requiredField(
        proto.workflowId === "" ? undefined : proto.workflowId,
        "WorkflowExecution",
        "workflowId",
      ),
      runId: proto.runId ?? undefined,
    };
  },

  toProto(
    model: WorkflowExecution | null | undefined,
  ): temporal.api.common.v1.IWorkflowExecution | undefined {
    if (model == null) {
      return undefined;
    }
    return {
      workflowId: requiredField(
        model.workflowId,
        "WorkflowExecution",
        "workflowId",
      ),
      runId: model.runId,
    };
  },
};

export interface RequestCancelWorkflowExecutionResponse {}

export const RequestCancelWorkflowExecutionResponse = {
  fromProto(
    proto:
      | temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionResponse
      | null
      | undefined,
  ): RequestCancelWorkflowExecutionResponse | undefined {
    if (proto == null) {
      return undefined;
    }
    return {};
  },

  toProto(
    model: RequestCancelWorkflowExecutionResponse | null | undefined,
  ):
    | temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionResponse
    | undefined {
    if (model == null) {
      return undefined;
    }
    return {};
  },
};

export class StartedWorkflow {
  public constructor(
    private readonly client: WorkflowServiceClient,
    public readonly namespace: string,
    public readonly workflowId: string,
    public readonly runId: string | undefined,
  ) {}

  public async cancel(reason?: string | undefined): Promise<void> {
    const request = {
      workflowExecution: { workflowId: this.workflowId, runId: this.runId },
      reason: reason,
    };
    const handle = await this.client.cancelWorkflow(request);
    await handle.result();
  }

  public async getResult(): Promise<common.Payload[]> {
    throw new Error("started-workflow.getResult is not yet implemented");
  }
}

export const WorkflowService = nexus.service("WorkflowService", {
  startWorkflow: nexus.operation<
    temporal.api.workflowservice.v1.IStartWorkflowExecutionRequest,
    temporal.api.workflowservice.v1.IStartWorkflowExecutionResponse
  >({ name: "StartWorkflow" }),
  cancelWorkflow: nexus.operation<
    temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionRequest,
    temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionResponse
  >({ name: "CancelWorkflow" }),
});

export class WorkflowServiceClient {
  private readonly client: workflow.NexusServiceClient<typeof WorkflowService>;

  public constructor() {
    this.client = workflow.createNexusServiceClient({
      service: WorkflowService,
      endpoint: "__temporal_system",
    });
  }

  public async startWorkflow<
    WorkflowFn extends (...args: any[]) => Promise<any> = (
      ...args: any[]
    ) => Promise<any>,
  >(
    request: StartWorkflowExecutionRequest<WorkflowFn>,
  ): Promise<StartedWorkflow> {
    const requestProto = StartWorkflowExecutionRequest.toProto(request) ?? {};
    const handle = await this.client.startOperation(
      WorkflowService.operations.startWorkflow,
      requestProto,
    );
    const result = await handle.result();
    return new StartedWorkflow(
      this,
      requiredField(requestProto.namespace, "resource", "namespace"),
      request.workflowId,
      result.runId ?? undefined,
    );
  }

  public async cancelWorkflow(
    request: RequestCancelWorkflowExecutionRequest,
  ): Promise<
    workflow.NexusOperationHandle<temporal.api.workflowservice.v1.IRequestCancelWorkflowExecutionResponse>
  > {
    return await this.client.startOperation(
      WorkflowService.operations.cancelWorkflow,
      RequestCancelWorkflowExecutionRequest.toProto(request) ?? {},
    );
  }
}
