# Generated by nexus-api-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

import collections.abc
import typing
import typing_extensions
from datetime import timedelta
from temporalio import workflow
import temporalio.api.workflowservice.v1.request_response_pb2

from ..models import StartWorkflowRequest
from .._resources import StartedWorkflow


def _nexus_normalize_function_args(
    value: object | tuple[object, ...] | list[typing.Any] | None,
) -> tuple[object, ...] | None:
    if value is None:
        return None
    if isinstance(value, (tuple, list)):
        return tuple(typing.cast(collections.abc.Iterable[object], value))
    return (value,)


_nexus_arg_unset = object()


FirstWorkflowArg = typing.TypeVar("FirstWorkflowArg")
SecondWorkflowArg = typing.TypeVar("SecondWorkflowArg")
RemainingWorkflowArgs = typing_extensions.TypeVarTuple("RemainingWorkflowArgs")


async def _start_workflow(
    request: StartWorkflowRequest,
) -> StartedWorkflow:
    request_proto = request.to_proto()
    nexus_client = workflow.create_nexus_client(
        service="WorkflowService",
        endpoint="temporal-system",
    )
    handle = await nexus_client.start_operation(
        operation="StartWorkflow",
        input=request_proto,
        output_type=temporalio.api.workflowservice.v1.request_response_pb2.StartWorkflowExecutionResponse,
    )
    result = await handle
    return StartedWorkflow(
        namespace=request_proto.namespace,
        workflow_id=request.workflow_id,
        run_id=result.run_id or None,
    )


@typing.overload
async def start_workflow(
    workflow: str,
    arg: object = ...,
    *,
    args: tuple[typing.Any, ...] | list[typing.Any] | None = ...,
    workflow_id: str,
    task_queue: str,
    workflow_start_delay: timedelta | None = ...,
) -> StartedWorkflow: ...


@typing.overload
async def start_workflow(
    workflow: collections.abc.Callable[[typing.Any], collections.abc.Awaitable[object]],
    *,
    workflow_id: str,
    task_queue: str,
    workflow_start_delay: timedelta | None = ...,
) -> StartedWorkflow: ...


@typing.overload
async def start_workflow(
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg], collections.abc.Awaitable[object]
    ],
    arg: FirstWorkflowArg,
    *,
    workflow_id: str,
    task_queue: str,
    workflow_start_delay: timedelta | None = ...,
) -> StartedWorkflow: ...


@typing.overload
async def start_workflow(
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg], collections.abc.Awaitable[object]
    ],
    *,
    args: tuple[FirstWorkflowArg],
    workflow_id: str,
    task_queue: str,
    workflow_start_delay: timedelta | None = ...,
) -> StartedWorkflow: ...


@typing.overload
async def start_workflow(
    workflow: collections.abc.Callable[
        [
            typing.Any,
            FirstWorkflowArg,
            SecondWorkflowArg,
            typing_extensions.Unpack[RemainingWorkflowArgs],
        ],
        collections.abc.Awaitable[object],
    ],
    *,
    args: tuple[
        FirstWorkflowArg,
        SecondWorkflowArg,
        typing_extensions.Unpack[RemainingWorkflowArgs],
    ],
    workflow_id: str,
    task_queue: str,
    workflow_start_delay: timedelta | None = ...,
) -> StartedWorkflow: ...


async def start_workflow(
    workflow: str | collections.abc.Callable[..., collections.abc.Awaitable[object]],
    arg: object = _nexus_arg_unset,
    *,
    args: object | tuple[object, ...] | list[typing.Any] | None = None,
    workflow_id: str,
    task_queue: str,
    workflow_start_delay: timedelta | None = None,
) -> StartedWorkflow:
    if arg is not _nexus_arg_unset and args is not None:
        raise TypeError("cannot specify both arg and args")
    normalized_args = (
        (arg,) if arg is not _nexus_arg_unset else _nexus_normalize_function_args(args)
    )
    request = StartWorkflowRequest(
        workflow=workflow,
        args=normalized_args,
        workflow_id=workflow_id,
        task_queue=task_queue,
        workflow_start_delay=workflow_start_delay,
    )
    return await _start_workflow(request)
