# Generated by nexus-rpc-gen. DO NOT EDIT!

from __future__ import annotations

import collections.abc
import dataclasses
import typing

from nexusrpc import Operation, service
from temporalio import workflow

import google.protobuf.duration_pb2
import temporalio.api.common.v1.message_pb2
import temporalio.api.enums.v1.workflow_pb2
import temporalio.api.sdk.v1.user_metadata_pb2
import temporalio.api.taskqueue.v1.message_pb2
import temporalio.api.workflow.v1.message_pb2
import temporalio.api.workflowservice.v1


@dataclasses.dataclass(slots=True)
class SignalWithStartWorkflowExecutionRequestModel:
    namespace: str | None = None
    workflow_id: str | None = None
    workflow_type: temporalio.api.common.v1.message_pb2.WorkflowType | None = None
    task_queue: temporalio.api.taskqueue.v1.message_pb2.TaskQueue | None = None
    input: temporalio.api.common.v1.message_pb2.Payloads | None = None
    workflow_execution_timeout: google.protobuf.duration_pb2.Duration | None = None
    workflow_run_timeout: google.protobuf.duration_pb2.Duration | None = None
    workflow_task_timeout: google.protobuf.duration_pb2.Duration | None = None
    identity: str | None = None
    request_id: str | None = None
    workflow_id_reuse_policy: temporalio.api.enums.v1.workflow_pb2.WorkflowIdReusePolicy.ValueType | None = None
    workflow_id_conflict_policy: temporalio.api.enums.v1.workflow_pb2.WorkflowIdConflictPolicy.ValueType | None = None
    signal_name: str | None = None
    signal_input: temporalio.api.common.v1.message_pb2.Payloads | None = None
    control: str | None = None
    retry_policy: temporalio.api.common.v1.message_pb2.RetryPolicy | None = None
    cron_schedule: str | None = None
    memo: temporalio.api.common.v1.message_pb2.Memo | None = None
    search_attributes: temporalio.api.common.v1.message_pb2.SearchAttributes | None = None
    header: temporalio.api.common.v1.message_pb2.Header | None = None
    workflow_start_delay: google.protobuf.duration_pb2.Duration | None = None
    user_metadata: temporalio.api.sdk.v1.user_metadata_pb2.UserMetadata | None = None
    links: list[temporalio.api.common.v1.message_pb2.Link] = dataclasses.field(default_factory=list)
    versioning_override: temporalio.api.workflow.v1.message_pb2.VersioningOverride | None = None
    priority: temporalio.api.common.v1.message_pb2.Priority | None = None

    @classmethod
    def from_proto(
        cls,
        proto: temporalio.api.workflowservice.v1.SignalWithStartWorkflowExecutionRequest,
    ) -> SignalWithStartWorkflowExecutionRequestModel:
        return cls(
            namespace=proto.namespace,
            workflow_id=proto.workflow_id,
            workflow_type=proto.workflow_type if proto.HasField("workflow_type") else None,
            task_queue=proto.task_queue if proto.HasField("task_queue") else None,
            input=proto.input if proto.HasField("input") else None,
            workflow_execution_timeout=proto.workflow_execution_timeout if proto.HasField("workflow_execution_timeout") else None,
            workflow_run_timeout=proto.workflow_run_timeout if proto.HasField("workflow_run_timeout") else None,
            workflow_task_timeout=proto.workflow_task_timeout if proto.HasField("workflow_task_timeout") else None,
            identity=proto.identity,
            request_id=proto.request_id,
            workflow_id_reuse_policy=proto.workflow_id_reuse_policy,
            workflow_id_conflict_policy=proto.workflow_id_conflict_policy,
            signal_name=proto.signal_name,
            signal_input=proto.signal_input if proto.HasField("signal_input") else None,
            control=proto.control,
            retry_policy=proto.retry_policy if proto.HasField("retry_policy") else None,
            cron_schedule=proto.cron_schedule,
            memo=proto.memo if proto.HasField("memo") else None,
            search_attributes=proto.search_attributes if proto.HasField("search_attributes") else None,
            header=proto.header if proto.HasField("header") else None,
            workflow_start_delay=proto.workflow_start_delay if proto.HasField("workflow_start_delay") else None,
            user_metadata=proto.user_metadata if proto.HasField("user_metadata") else None,
            links=list(proto.links),
            versioning_override=proto.versioning_override if proto.HasField("versioning_override") else None,
            priority=proto.priority if proto.HasField("priority") else None,
        )

    def to_proto(self) -> temporalio.api.workflowservice.v1.SignalWithStartWorkflowExecutionRequest:
        message = temporalio.api.workflowservice.v1.SignalWithStartWorkflowExecutionRequest()
        if self.namespace is not None:
            message.namespace = self.namespace
        if self.workflow_id is not None:
            message.workflow_id = self.workflow_id
        if self.workflow_type is not None:
            message.workflow_type.CopyFrom(self.workflow_type)
        if self.task_queue is not None:
            message.task_queue.CopyFrom(self.task_queue)
        if self.input is not None:
            message.input.CopyFrom(self.input)
        if self.workflow_execution_timeout is not None:
            message.workflow_execution_timeout.CopyFrom(self.workflow_execution_timeout)
        if self.workflow_run_timeout is not None:
            message.workflow_run_timeout.CopyFrom(self.workflow_run_timeout)
        if self.workflow_task_timeout is not None:
            message.workflow_task_timeout.CopyFrom(self.workflow_task_timeout)
        if self.identity is not None:
            message.identity = self.identity
        if self.request_id is not None:
            message.request_id = self.request_id
        if self.workflow_id_reuse_policy is not None:
            message.workflow_id_reuse_policy = self.workflow_id_reuse_policy
        if self.workflow_id_conflict_policy is not None:
            message.workflow_id_conflict_policy = self.workflow_id_conflict_policy
        if self.signal_name is not None:
            message.signal_name = self.signal_name
        if self.signal_input is not None:
            message.signal_input.CopyFrom(self.signal_input)
        if self.control is not None:
            message.control = self.control
        if self.retry_policy is not None:
            message.retry_policy.CopyFrom(self.retry_policy)
        if self.cron_schedule is not None:
            message.cron_schedule = self.cron_schedule
        if self.memo is not None:
            message.memo.CopyFrom(self.memo)
        if self.search_attributes is not None:
            message.search_attributes.CopyFrom(self.search_attributes)
        if self.header is not None:
            message.header.CopyFrom(self.header)
        if self.workflow_start_delay is not None:
            message.workflow_start_delay.CopyFrom(self.workflow_start_delay)
        if self.user_metadata is not None:
            message.user_metadata.CopyFrom(self.user_metadata)
        if self.links:
            for value in self.links:
                item = message.links.add()
                item.CopyFrom(value)
        if self.versioning_override is not None:
            message.versioning_override.CopyFrom(self.versioning_override)
        if self.priority is not None:
            message.priority.CopyFrom(self.priority)
        return message


@dataclasses.dataclass(slots=True)
class SignalWithStartWorkflowExecutionResponseModel:
    run_id: str | None = None
    started: bool | None = None

    @classmethod
    def from_proto(
        cls,
        proto: temporalio.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse,
    ) -> SignalWithStartWorkflowExecutionResponseModel:
        return cls(
            run_id=proto.run_id,
            started=proto.started,
        )

    def to_proto(self) -> temporalio.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse:
        message = temporalio.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse()
        if self.run_id is not None:
            message.run_id = self.run_id
        if self.started is not None:
            message.started = self.started
        return message


@service
class WorkflowService:
    signal_with_start_workflow_execution: Operation[
        temporalio.api.workflowservice.v1.SignalWithStartWorkflowExecutionRequest,
        temporalio.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse,
    ] = Operation(name="SignalWithStartWorkflowExecution")


class WorkflowServiceClient:
    def __init__(self) -> None:
        self._client: workflow.NexusClient[WorkflowService] = workflow.create_nexus_client(
            service=WorkflowService,
            endpoint="__temporal_system",
        )

    async def signal_with_start_workflow_execution(
        self,
        request: SignalWithStartWorkflowExecutionRequestModel,
    ) -> workflow.NexusOperationHandle[
        temporalio.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse,
    ]:
        return await self._client.start_operation(
            WorkflowService.signal_with_start_workflow_execution,
            request.to_proto(),
        )

    @staticmethod
    def signal_with_start_workflow_execution_response_from_proto(
        proto: temporalio.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse,
    ) -> SignalWithStartWorkflowExecutionResponseModel:
        return SignalWithStartWorkflowExecutionResponseModel.from_proto(proto)

    async def signal_with_start_workflow(
        self,
        workflow_id: str,
        *,
        signal: str | collections.abc.Callable[..., object],
        workflow: str | collections.abc.Callable[..., collections.abc.Awaitable[object]],
        retry_policy: temporalio.common.RetryPolicy | None = None,
    ) -> workflow.ExternalWorkflowHandle[object]:
        request = build_signal_with_start_workflow_request(
            workflow_id=workflow_id,
            signal=signal,
            workflow=workflow,
            retry_policy=retry_policy,
        )
        handle = await self.signal_with_start_workflow_execution(request)
        response_proto = await handle
        response = self.signal_with_start_workflow_execution_response_from_proto(response_proto)
        return signal_with_start_workflow_response_to_external_workflow_handle(
            request=request,
            response=response,
        )


__nexus_operation_registry__: dict[
    tuple[str, str], Operation[temporalio.api.workflowservice.v1.SignalWithStartWorkflowExecutionRequest, temporalio.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse]
] = {
    (
        "WorkflowService",
        "SignalWithStartWorkflowExecution",
    ): WorkflowService.signal_with_start_workflow_execution,
}


# Appended from --python-support
import temporalio.api.common.v1
import temporalio.api.taskqueue.v1
import temporalio.common


class _WorkflowDefinitionLike(typing.Protocol):
    name: str | None


class _SignalDefinitionLike(typing.Protocol):
    name: str | None


def _workflow_name(
    name_or_run_fn: str | collections.abc.Callable[..., collections.abc.Awaitable[object]],
) -> str:
    if isinstance(name_or_run_fn, str):
        return name_or_run_fn
    definition = typing.cast(
        _WorkflowDefinitionLike | None,
        getattr(name_or_run_fn, "__temporal_workflow_definition", None),
    )
    if definition is None:
        raise ValueError(
            "Workflow callable is missing Temporal workflow metadata; use a @workflow.run method from a @workflow.defn class."
        )
    if not definition.name:
        raise ValueError("Cannot use a dynamic workflow with SignalWithStartWorkflow")
    return definition.name


def _signal_name(name_or_fn: str | collections.abc.Callable[..., object]) -> str:
    if isinstance(name_or_fn, str):
        return name_or_fn
    definition = typing.cast(
        _SignalDefinitionLike | None,
        getattr(name_or_fn, "__temporal_signal_definition", None),
    )
    if definition is None:
        raise RuntimeError(
            "Signal callable is missing Temporal signal metadata; use a @workflow.signal method."
        )
    if not definition.name:
        raise RuntimeError("Cannot invoke a dynamic signal definition")
    return definition.name


def build_signal_with_start_workflow_request(
    *,
    workflow_id: str,
    signal: str | collections.abc.Callable[..., object],
    workflow: str | collections.abc.Callable[..., collections.abc.Awaitable[object]],
    retry_policy: temporalio.common.RetryPolicy | None,
) -> SignalWithStartWorkflowExecutionRequestModel:
    return SignalWithStartWorkflowExecutionRequestModel(
        namespace="default",
        workflow_id=workflow_id,
        workflow_type=temporalio.api.common.v1.WorkflowType(
            name=_workflow_name(workflow),
        ),
        task_queue=temporalio.api.taskqueue.v1.TaskQueue(name="default"),
        signal_name=_signal_name(signal),
        retry_policy=_retry_policy_to_proto(retry_policy),
    )


def _retry_policy_to_proto(
    retry_policy: temporalio.common.RetryPolicy | None,
) -> temporalio.api.common.v1.RetryPolicy | None:
    if retry_policy is None:
        return None

    proto = temporalio.api.common.v1.RetryPolicy()
    retry_policy.apply_to_proto(proto)
    return proto


def signal_with_start_workflow_response_to_external_workflow_handle(
    *,
    request: SignalWithStartWorkflowExecutionRequestModel,
    response: SignalWithStartWorkflowExecutionResponseModel,
) -> workflow.ExternalWorkflowHandle[object]:
    if request.workflow_id is None:
        raise ValueError("workflow_id must be set to build an ExternalWorkflowHandle")
    return typing.cast(
        workflow.ExternalWorkflowHandle[object],
        workflow.get_external_workflow_handle(
            request.workflow_id,
            run_id=response.run_id,
        ),
    )
