use std::collections::BTreeMap;

use heck::{ToLowerCamelCase, ToUpperCamelCase};
use indexmap::IndexMap;
use prost_types::FieldDescriptorProto;
use prost_types::field_descriptor_proto::{Label, Type};

use crate::SupportFiles;
use crate::descriptors::{DescriptorIndex, EnumMetadata, MessageMetadata};
use crate::error::{Error, Result};
use crate::generator::GeneratorBackend;
use crate::language::Language;
use crate::spec::{ApiMethodPropertyDefault, ApiMethodSpec, ApiSpec, Direction, OperationSpec};

const GENERATED_HEADER: &str = "// Generated by nexus-rpc-gen. DO NOT EDIT!";
const TYPESCRIPT_SUPPORT_MARKER: &str = "// Included from support.$typescriptFile";

pub struct TypeScriptBackend;

impl GeneratorBackend for TypeScriptBackend {
    fn language(&self) -> Language {
        Language::TypeScript
    }

    fn generate(
        &self,
        spec: &ApiSpec,
        descriptors: &DescriptorIndex,
        support: &SupportFiles,
    ) -> Result<String> {
        let requires_typescript_support = spec.services.iter().any(|service| {
            service
                .apis
                .iter()
                .any(|api| normalized_symbol(api.output.typescript_ref.as_deref()).is_some())
        });
        if requires_typescript_support && support.typescript.is_none() {
            return Err(Error::MissingTypeScriptSupport);
        }

        let mut enums = IndexMap::new();
        let mut models = IndexMap::new();
        let mut uses_long = false;
        let services = spec
            .services
            .iter()
            .map(|service| {
                let endpoint =
                    service
                        .endpoint
                        .as_deref()
                        .ok_or_else(|| Error::MissingServiceEndpoint {
                            service: service.name.clone(),
                        })?;
                let operations = service
                    .operations
                    .iter()
                    .map(|operation| {
                        resolve_operation(
                            &service.name,
                            operation,
                            descriptors,
                            &mut enums,
                            &mut models,
                            &mut uses_long,
                        )
                    })
                    .collect::<Result<Vec<_>>>()?;
                let operation_map: BTreeMap<&str, &RenderedOperation<'_>> = operations
                    .iter()
                    .map(|operation| (operation.name, operation))
                    .collect();
                let apis = service
                    .apis
                    .iter()
                    .filter(|api| normalized_symbol(api.output.typescript_ref.as_deref()).is_some())
                    .map(|api| resolve_api(&service.name, api, &operation_map))
                    .collect::<Result<Vec<_>>>()?;

                Ok(RenderedService {
                    name: service.name.as_str(),
                    endpoint: endpoint.to_string(),
                    client_name: format!("{}Client", service.name),
                    operations,
                    apis,
                })
            })
            .collect::<Result<Vec<_>>>()?;

        Ok(render_module(
            enums.values().collect::<Vec<_>>().as_slice(),
            models.values().collect::<Vec<_>>().as_slice(),
            &services,
            support.typescript.as_deref(),
            uses_long,
        ))
    }
}

#[derive(Debug)]
struct RenderedService<'a> {
    name: &'a str,
    endpoint: String,
    client_name: String,
    operations: Vec<RenderedOperation<'a>>,
    apis: Vec<RenderedApi>,
}

#[derive(Debug)]
struct RenderedOperation<'a> {
    name: &'a str,
    attr_name: String,
    input_type_name: String,
    output_type_name: String,
    input_proto_ref: String,
    output_proto_ref: String,
    input_model_name: String,
    output_model_name: String,
    input_fields: BTreeMap<String, String>,
}

#[derive(Debug)]
struct RenderedApi {
    attr_name: String,
    operation_attr_name: String,
    operation_output_model_name: String,
    output_ref: String,
    request_strategy: RenderedApiRequestStrategy,
    response_strategy: RenderedApiResponseStrategy,
    parameters: Vec<RenderedApiParameter>,
    options_type_name: Option<String>,
}

#[derive(Debug)]
struct RenderedApiParameter {
    name: String,
    local_name: String,
    property_name: String,
    type_name: Option<String>,
    typescript_converter: Option<String>,
    typescript_output_converter: Option<String>,
    annotation: String,
    default_expr: Option<String>,
    positional: bool,
}

#[derive(Debug)]
enum RenderedApiRequestStrategy {
    Converter(String),
    SinglePropertyConverter {
        parameter_name: String,
        converter: String,
    },
    ModelConstructor {
        model_name: String,
        fields: Vec<RenderedApiRequestField>,
    },
}

#[derive(Debug)]
struct RenderedApiRequestField {
    field_name: String,
    parameter_name: String,
    converter: Option<String>,
}

#[derive(Debug)]
enum RenderedApiResponseStrategy {
    Converter(String),
    SinglePropertyConverter(String),
}

#[derive(Debug)]
struct RenderedEnum {
    name: String,
    values: Vec<RenderedEnumValue>,
}

#[derive(Debug)]
struct RenderedEnumValue {
    name: String,
    number: i32,
}

#[derive(Debug)]
struct RenderedModel {
    name: String,
    fields: Vec<RenderedField>,
}

#[derive(Debug)]
struct RenderedField {
    name: String,
    annotation: String,
    from_proto_expr: String,
    to_proto_expr: String,
}

#[derive(Debug)]
struct MapFieldInfo {
    value_type: ResolvedFieldType,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ResolvedFieldKind {
    Scalar,
    Message,
    Enum,
    Unknown,
}

#[derive(Debug, Clone)]
struct ResolvedFieldType {
    annotation: String,
    kind: ResolvedFieldKind,
    uses_long: bool,
}

fn resolve_operation<'a>(
    service_name: &str,
    operation: &'a OperationSpec,
    descriptors: &DescriptorIndex,
    enums: &mut IndexMap<String, RenderedEnum>,
    models: &mut IndexMap<String, RenderedModel>,
    uses_long: &mut bool,
) -> Result<RenderedOperation<'a>> {
    let input_ref = required_typescript_ref(service_name, operation, Direction::Input)?;
    let output_ref = required_typescript_ref(service_name, operation, Direction::Output)?;

    let input_message = descriptors.resolve_typescript_ref(input_ref)?;
    let output_message = descriptors.resolve_typescript_ref(output_ref)?;

    ensure_model(input_message, descriptors, enums, models, uses_long);
    ensure_model(output_message, descriptors, enums, models, uses_long);

    Ok(RenderedOperation {
        name: operation.name.as_str(),
        attr_name: typescript_ident(&operation.name.to_lower_camel_case()),
        input_type_name: message_type_name(&input_message.full_name),
        output_type_name: message_type_name(&output_message.full_name),
        input_proto_ref: message_typescript_interface_ref(input_message),
        output_proto_ref: message_typescript_interface_ref(output_message),
        input_model_name: message_model_name(&input_message.full_name),
        output_model_name: message_model_name(&output_message.full_name),
        input_fields: input_message
            .descriptor
            .field
            .iter()
            .filter_map(|field| {
                Some((
                    field.name.as_deref()?.to_string(),
                    typescript_field_name(field),
                ))
            })
            .collect(),
    })
}

fn resolve_api(
    service_name: &str,
    api: &ApiMethodSpec,
    operations: &BTreeMap<&str, &RenderedOperation<'_>>,
) -> Result<RenderedApi> {
    if api.input.schema_type != "object" {
        return Err(Error::UnsupportedApiInputType {
            service: service_name.to_string(),
            api: api.name.clone(),
            input_type: api.input.schema_type.clone(),
        });
    }

    let operation =
        operations
            .get(api.operation.as_str())
            .ok_or_else(|| Error::UnknownApiOperation {
                service: service_name.to_string(),
                api: api.name.clone(),
                operation: api.operation.clone(),
            })?;
    let output_ref = api
        .output
        .typescript_ref
        .as_deref()
        .filter(|value| !value.trim().is_empty())
        .ok_or_else(|| Error::MissingApiOutputTypeScriptRef {
            service: service_name.to_string(),
            api: api.name.clone(),
        })?;

    let mut positional_required_parameters = Vec::new();
    let mut positional_defaulted_parameters = Vec::new();
    let mut option_parameters = Vec::new();
    for property in &api.input.properties {
        let typescript_parameter_name = property
            .typescript_name
            .as_deref()
            .unwrap_or(&property.name)
            .to_lower_camel_case();
        let annotation = property
            .typescript_type
            .clone()
            .or_else(|| property.schema_type.as_deref().map(api_property_annotation))
            .ok_or_else(|| Error::MissingApiInputPropertyType {
                service: service_name.to_string(),
                api: api.name.clone(),
                property: property.name.clone(),
            })?;
        let parameter = RenderedApiParameter {
            name: typescript_ident(&typescript_parameter_name),
            local_name: typescript_local_ident(&typescript_parameter_name),
            property_name: property.name.clone(),
            type_name: property.type_name.clone(),
            typescript_converter: property.typescript_converter.clone(),
            typescript_output_converter: property.typescript_output_converter.clone(),
            annotation,
            default_expr: property
                .typescript_default
                .clone()
                .or_else(|| property.default_value.as_ref().map(typescript_default_expr)),
            positional: property
                .typescript_positional
                .unwrap_or(property.positional),
        };
        match (parameter.positional, parameter.default_expr.is_some()) {
            (true, true) => positional_defaulted_parameters.push(parameter),
            (true, false) => positional_required_parameters.push(parameter),
            (false, _) => option_parameters.push(parameter),
        }
    }

    let mut parameters = Vec::new();
    parameters.extend(positional_required_parameters);
    parameters.extend(positional_defaulted_parameters);
    parameters.extend(option_parameters);

    let request_strategy = resolve_api_request_strategy(service_name, api, operation, &parameters)?;
    let response_strategy =
        resolve_api_response_strategy(service_name, api, operation, output_ref, &parameters)?;

    let has_option_parameters = parameters.iter().any(|parameter| !parameter.positional);

    Ok(RenderedApi {
        attr_name: typescript_ident(&api.name.to_lower_camel_case()),
        operation_attr_name: operation.attr_name.clone(),
        operation_output_model_name: operation.output_model_name.clone(),
        output_ref: output_ref.to_string(),
        request_strategy,
        response_strategy,
        parameters,
        options_type_name: if has_option_parameters {
            Some(format!(
                "{service_name}{}Options",
                api.name.to_upper_camel_case()
            ))
        } else {
            None
        },
    })
}

fn resolve_api_request_strategy(
    service_name: &str,
    api: &ApiMethodSpec,
    operation: &RenderedOperation<'_>,
    parameters: &[RenderedApiParameter],
) -> Result<RenderedApiRequestStrategy> {
    if let Some(converter) = normalized_symbol(api.input.typescript_converter.as_deref()) {
        return Ok(RenderedApiRequestStrategy::Converter(converter.to_string()));
    }

    if parameters.len() == 1 {
        let parameter = &parameters[0];
        if parameter
            .type_name
            .as_deref()
            .is_some_and(|type_name| type_name.eq_ignore_ascii_case(&operation.input_type_name))
        {
            if let Some(converter) = normalized_symbol(parameter.typescript_converter.as_deref()) {
                return Ok(RenderedApiRequestStrategy::SinglePropertyConverter {
                    parameter_name: parameter.local_name.clone(),
                    converter: converter.to_string(),
                });
            }
        }
    }

    if !parameters.is_empty()
        && parameters.iter().all(|parameter| {
            operation
                .input_fields
                .contains_key(&parameter.property_name)
        })
    {
        return Ok(RenderedApiRequestStrategy::ModelConstructor {
            model_name: operation.input_model_name.clone(),
            fields: parameters
                .iter()
                .map(|parameter| RenderedApiRequestField {
                    field_name: operation
                        .input_fields
                        .get(&parameter.property_name)
                        .expect("checked above")
                        .clone(),
                    parameter_name: parameter.local_name.clone(),
                    converter: normalized_symbol(parameter.typescript_converter.as_deref())
                        .map(str::to_string),
                })
                .collect(),
        });
    }

    Err(Error::MissingApiInputTypeScriptConverter {
        service: service_name.to_string(),
        api: api.name.clone(),
    })
}

fn resolve_api_response_strategy(
    service_name: &str,
    api: &ApiMethodSpec,
    operation: &RenderedOperation<'_>,
    output_ref: &str,
    parameters: &[RenderedApiParameter],
) -> Result<RenderedApiResponseStrategy> {
    if let Some(converter) = normalized_symbol(api.output.typescript_converter.as_deref()) {
        return Ok(RenderedApiResponseStrategy::Converter(
            converter.to_string(),
        ));
    }

    if parameters.len() == 1 {
        let parameter = &parameters[0];
        if parameter
            .type_name
            .as_deref()
            .is_some_and(|type_name| type_name.eq_ignore_ascii_case(&operation.output_type_name))
            && parameter.annotation == output_ref
        {
            if let Some(converter) =
                normalized_symbol(parameter.typescript_output_converter.as_deref())
            {
                return Ok(RenderedApiResponseStrategy::SinglePropertyConverter(
                    converter.to_string(),
                ));
            }
        }
    }

    Err(Error::MissingApiOutputTypeScriptConverter {
        service: service_name.to_string(),
        api: api.name.clone(),
    })
}

fn normalized_symbol(value: Option<&str>) -> Option<&str> {
    value.filter(|value| !value.trim().is_empty())
}

fn required_typescript_ref<'a>(
    service_name: &str,
    operation: &'a OperationSpec,
    direction: Direction,
) -> Result<&'a str> {
    operation
        .language_ref(Language::TypeScript, direction)
        .ok_or_else(|| Error::MissingLanguageRef {
            service: service_name.to_string(),
            operation: operation.name.clone(),
            language: Language::TypeScript,
            direction: direction.as_str(),
        })
}

fn ensure_model(
    message: &MessageMetadata,
    descriptors: &DescriptorIndex,
    enums: &mut IndexMap<String, RenderedEnum>,
    models: &mut IndexMap<String, RenderedModel>,
    uses_long: &mut bool,
) {
    if models.contains_key(&message.full_name) {
        return;
    }

    models.insert(
        message.full_name.clone(),
        RenderedModel {
            name: message_model_name(&message.full_name),
            fields: Vec::new(),
        },
    );

    let fields = message
        .descriptor
        .field
        .iter()
        .map(|field| build_field(field, descriptors, enums, models, uses_long))
        .collect();

    models
        .get_mut(&message.full_name)
        .expect("model should be inserted before recursive field resolution")
        .fields = fields;
}

fn ensure_enum(enumeration: &EnumMetadata, enums: &mut IndexMap<String, RenderedEnum>) {
    enums
        .entry(enumeration.full_name.clone())
        .or_insert_with(|| RenderedEnum {
            name: enum_name(&enumeration.full_name),
            values: enumeration
                .descriptor
                .value
                .iter()
                .filter_map(|value| {
                    Some(RenderedEnumValue {
                        name: value.name.as_deref()?.to_string(),
                        number: value.number?,
                    })
                })
                .collect(),
        });
}

fn build_field(
    field: &FieldDescriptorProto,
    descriptors: &DescriptorIndex,
    enums: &mut IndexMap<String, RenderedEnum>,
    models: &mut IndexMap<String, RenderedModel>,
    uses_long: &mut bool,
) -> RenderedField {
    let field_name = typescript_field_name(field);

    if let Some(map_info) = map_field_info(field, descriptors, enums, models, uses_long) {
        *uses_long |= map_info.value_type.uses_long;
        return RenderedField {
            name: field_name.clone(),
            annotation: format!("Record<string, {}>", map_info.value_type.annotation),
            from_proto_expr: map_value_from_proto_expr(&map_info.value_type, &field_name),
            to_proto_expr: map_value_to_proto_expr(&map_info.value_type, &field_name),
        };
    }

    let resolved_type = resolve_field_type(field, descriptors, enums, models, uses_long);
    *uses_long |= resolved_type.uses_long;
    let label = field_label(field);

    if label == Some(Label::Repeated) {
        return RenderedField {
            name: field_name.clone(),
            annotation: format!("{}[]", resolved_type.annotation),
            from_proto_expr: repeated_from_proto_expr(&resolved_type, &field_name),
            to_proto_expr: repeated_to_proto_expr(&resolved_type, &field_name),
        };
    }

    RenderedField {
        name: field_name.clone(),
        annotation: resolved_type.annotation.clone(),
        from_proto_expr: singular_from_proto_expr(&resolved_type, &field_name),
        to_proto_expr: singular_to_proto_expr(&resolved_type, &field_name),
    }
}

fn repeated_from_proto_expr(resolved_type: &ResolvedFieldType, field_name: &str) -> String {
    match resolved_type.kind {
        ResolvedFieldKind::Message => format!(
            "proto.{field_name}?.map((value: any) => {}.fromProto(value) ?? {{}})",
            resolved_type.annotation
        ),
        ResolvedFieldKind::Enum => format!(
            "proto.{field_name}?.map((value: any) => value as {})",
            resolved_type.annotation
        ),
        _ => format!("proto.{field_name}?.slice()"),
    }
}

fn repeated_to_proto_expr(resolved_type: &ResolvedFieldType, field_name: &str) -> String {
    match resolved_type.kind {
        ResolvedFieldKind::Message => format!(
            "model.{field_name}?.map((value) => {}.toProto(value) ?? {{}})",
            resolved_type.annotation
        ),
        ResolvedFieldKind::Enum => format!("model.{field_name}?.map((value) => value as number)"),
        _ => format!("model.{field_name}?.slice()"),
    }
}

fn map_value_from_proto_expr(map_value_type: &ResolvedFieldType, field_name: &str) -> String {
    let value_expr = match map_value_type.kind {
        ResolvedFieldKind::Message => {
            format!("{}.fromProto(value) ?? {{}}", map_value_type.annotation)
        }
        ResolvedFieldKind::Enum => format!("value as {}", map_value_type.annotation),
        _ => format!("value as {}", map_value_type.annotation),
    };
    format!(
        "proto.{field_name} == null ? undefined : (Object.fromEntries(Object.entries(proto.{field_name} as Record<string, any>).map(([key, value]: [string, any]) => [key, {value_expr}])) as Record<string, {}>)",
        map_value_type.annotation
    )
}

fn map_value_to_proto_expr(map_value_type: &ResolvedFieldType, field_name: &str) -> String {
    let value_expr = match map_value_type.kind {
        ResolvedFieldKind::Message => {
            format!("{}.toProto(value) ?? {{}}", map_value_type.annotation)
        }
        ResolvedFieldKind::Enum => "value as number".to_string(),
        _ => "value".to_string(),
    };
    format!(
        "model.{field_name} == null ? undefined : Object.fromEntries(Object.entries(model.{field_name} as Record<string, any>).map(([key, value]: [string, any]) => [key, {value_expr}]))"
    )
}

fn singular_from_proto_expr(resolved_type: &ResolvedFieldType, field_name: &str) -> String {
    match resolved_type.kind {
        ResolvedFieldKind::Message => {
            format!("{}.fromProto(proto.{field_name})", resolved_type.annotation)
        }
        ResolvedFieldKind::Enum => format!(
            "proto.{field_name} == null ? undefined : (proto.{field_name} as {})",
            resolved_type.annotation
        ),
        _ => format!("proto.{field_name} ?? undefined"),
    }
}

fn singular_to_proto_expr(resolved_type: &ResolvedFieldType, field_name: &str) -> String {
    match resolved_type.kind {
        ResolvedFieldKind::Message => {
            format!("{}.toProto(model.{field_name})", resolved_type.annotation)
        }
        ResolvedFieldKind::Enum => {
            format!("model.{field_name} == null ? undefined : (model.{field_name} as number)")
        }
        _ => format!("model.{field_name}"),
    }
}

fn map_field_info(
    field: &FieldDescriptorProto,
    descriptors: &DescriptorIndex,
    enums: &mut IndexMap<String, RenderedEnum>,
    models: &mut IndexMap<String, RenderedModel>,
    uses_long: &mut bool,
) -> Option<MapFieldInfo> {
    if field_label(field) != Some(Label::Repeated) || field_type(field) != Some(Type::Message) {
        return None;
    }

    let entry_name = field.type_name.as_deref()?.trim_start_matches('.');
    let entry = descriptors.message(entry_name)?;
    let is_map_entry = entry
        .descriptor
        .options
        .as_ref()
        .and_then(|options| options.map_entry)
        .unwrap_or(false);

    if !is_map_entry {
        return None;
    }

    let value_field = entry
        .descriptor
        .field
        .iter()
        .find(|field| field.name.as_deref() == Some("value"))?;

    Some(MapFieldInfo {
        value_type: resolve_field_type(value_field, descriptors, enums, models, uses_long),
    })
}

fn resolve_field_type(
    field: &FieldDescriptorProto,
    descriptors: &DescriptorIndex,
    enums: &mut IndexMap<String, RenderedEnum>,
    models: &mut IndexMap<String, RenderedModel>,
    uses_long: &mut bool,
) -> ResolvedFieldType {
    match field_type(field) {
        Some(Type::Double | Type::Float) => ResolvedFieldType {
            annotation: "number".to_string(),
            kind: ResolvedFieldKind::Scalar,
            uses_long: false,
        },
        Some(Type::Int64 | Type::Uint64 | Type::Fixed64 | Type::Sfixed64 | Type::Sint64) => {
            *uses_long = true;
            ResolvedFieldType {
                annotation: "Long".to_string(),
                kind: ResolvedFieldKind::Scalar,
                uses_long: true,
            }
        }
        Some(Type::Int32 | Type::Fixed32 | Type::Uint32 | Type::Sfixed32 | Type::Sint32) => {
            ResolvedFieldType {
                annotation: "number".to_string(),
                kind: ResolvedFieldKind::Scalar,
                uses_long: false,
            }
        }
        Some(Type::Bool) => ResolvedFieldType {
            annotation: "boolean".to_string(),
            kind: ResolvedFieldKind::Scalar,
            uses_long: false,
        },
        Some(Type::String) => ResolvedFieldType {
            annotation: "string".to_string(),
            kind: ResolvedFieldKind::Scalar,
            uses_long: false,
        },
        Some(Type::Bytes) => ResolvedFieldType {
            annotation: "Uint8Array".to_string(),
            kind: ResolvedFieldKind::Scalar,
            uses_long: false,
        },
        Some(Type::Enum) => {
            if let Some(enumeration) = field
                .type_name
                .as_deref()
                .and_then(|type_name| descriptors.enumeration(type_name.trim_start_matches('.')))
            {
                ensure_enum(enumeration, enums);
                ResolvedFieldType {
                    annotation: enum_name(&enumeration.full_name),
                    kind: ResolvedFieldKind::Enum,
                    uses_long: false,
                }
            } else {
                ResolvedFieldType {
                    annotation: "number".to_string(),
                    kind: ResolvedFieldKind::Enum,
                    uses_long: false,
                }
            }
        }
        Some(Type::Message) | Some(Type::Group) => {
            if let Some(message) = field
                .type_name
                .as_deref()
                .and_then(|type_name| descriptors.message(type_name.trim_start_matches('.')))
            {
                ensure_model(message, descriptors, enums, models, uses_long);
                ResolvedFieldType {
                    annotation: message_model_name(&message.full_name),
                    kind: ResolvedFieldKind::Message,
                    uses_long: false,
                }
            } else {
                ResolvedFieldType {
                    annotation: "unknown".to_string(),
                    kind: ResolvedFieldKind::Unknown,
                    uses_long: false,
                }
            }
        }
        None => ResolvedFieldType {
            annotation: "unknown".to_string(),
            kind: ResolvedFieldKind::Unknown,
            uses_long: false,
        },
    }
}

fn message_model_name(full_name: &str) -> String {
    format!(
        "{}Model",
        full_name
            .rsplit('.')
            .next()
            .expect("descriptor names should not be empty")
    )
}

fn message_type_name(full_name: &str) -> String {
    full_name
        .rsplit('.')
        .next()
        .expect("descriptor names should not be empty")
        .to_string()
}

fn enum_name(full_name: &str) -> String {
    full_name
        .rsplit('.')
        .next()
        .expect("descriptor names should not be empty")
        .to_string()
}

fn message_typescript_interface_ref(message: &MessageMetadata) -> String {
    let relative_name = relative_descriptor_name(&message.full_name, &message.package);
    let mut parts = relative_name.split('.').collect::<Vec<_>>();
    let leaf = parts
        .pop()
        .expect("descriptor names should not be empty")
        .to_string();
    if parts.is_empty() {
        format!("{}.I{leaf}", message.package)
    } else {
        format!("{}.{}.I{leaf}", message.package, parts.join("."))
    }
}

fn relative_descriptor_name(full_name: &str, package: &str) -> String {
    if package.is_empty() {
        full_name.to_string()
    } else {
        full_name
            .strip_prefix(&format!("{package}."))
            .unwrap_or(full_name)
            .to_string()
    }
}

fn field_label(field: &FieldDescriptorProto) -> Option<Label> {
    field.label.and_then(|label| Label::try_from(label).ok())
}

fn field_type(field: &FieldDescriptorProto) -> Option<Type> {
    field
        .r#type
        .and_then(|field_type| Type::try_from(field_type).ok())
}

fn api_property_annotation(schema_type: &str) -> String {
    match schema_type {
        "string" => "string".to_string(),
        "integer" | "number" => "number".to_string(),
        "boolean" => "boolean".to_string(),
        _ => "unknown".to_string(),
    }
}

fn typescript_default_expr(default_value: &ApiMethodPropertyDefault) -> String {
    match default_value {
        ApiMethodPropertyDefault::Null => "undefined".to_string(),
        ApiMethodPropertyDefault::Bool(true) => "true".to_string(),
        ApiMethodPropertyDefault::Bool(false) => "false".to_string(),
        ApiMethodPropertyDefault::Integer(value) => value.to_string(),
        ApiMethodPropertyDefault::Float(value) => value.clone(),
        ApiMethodPropertyDefault::String(value) => typescript_string_literal(value),
    }
}

fn render_module(
    enums: &[&RenderedEnum],
    models: &[&RenderedModel],
    services: &[RenderedService<'_>],
    support_source: Option<&str>,
    uses_long: bool,
) -> String {
    let api_option_types = services
        .iter()
        .flat_map(|service| service.apis.iter())
        .filter_map(|api| api.options_type_name.as_ref().map(|name| (name, api)))
        .collect::<Vec<_>>();

    let mut output = String::new();
    output.push_str(GENERATED_HEADER);
    output.push_str("\n\n");
    output.push_str("import * as common from '@temporalio/common';\n");
    output.push_str("import * as nexus from 'nexus-rpc';\n");
    output.push_str("import type Long from 'long';\n");
    output.push_str("import type { google, temporal } from '@temporalio/proto';\n");
    output.push_str("import * as workflow from '@temporalio/workflow';\n");
    if !uses_long {
        output = output.replace("import type Long from 'long';\n", "");
    }

    if let Some(support_source) = support_source.filter(|source| !source.trim().is_empty()) {
        output.push_str("\n");
        output.push_str(TYPESCRIPT_SUPPORT_MARKER);
        output.push('\n');
        output.push_str(support_source);
        if !support_source.ends_with('\n') {
            output.push('\n');
        }
    }

    if !enums.is_empty() {
        output.push('\n');
        for enumeration in enums {
            render_enum(&mut output, enumeration);
            output.push('\n');
        }
    }

    if !models.is_empty() {
        if !enums.is_empty() || support_source.is_some() {
            output.push('\n');
        }
        for model in models {
            render_model(&mut output, model);
            output.push('\n');
        }
    }

    if !api_option_types.is_empty() {
        output.push('\n');
        for (name, api) in api_option_types {
            render_api_options_type(&mut output, name, api);
            output.push('\n');
        }
    }

    for (index, service) in services.iter().enumerate() {
        if index > 0 || !services.is_empty() {
            output.push('\n');
        }
        render_service(&mut output, service);
    }

    output
}

fn render_enum(output: &mut String, enumeration: &RenderedEnum) {
    output.push_str("export enum ");
    output.push_str(&enumeration.name);
    output.push_str(" {\n");
    if enumeration.values.is_empty() {
        output.push_str("}\n");
        return;
    }
    for value in &enumeration.values {
        output.push_str("  ");
        output.push_str(&value.name);
        output.push_str(" = ");
        output.push_str(&value.number.to_string());
        output.push_str(",\n");
    }
    output.push_str("}\n");
}

fn render_model(output: &mut String, model: &RenderedModel) {
    output.push_str("export interface ");
    output.push_str(&model.name);
    output.push_str(" {\n");
    for field in &model.fields {
        output.push_str("  ");
        output.push_str(&field.name);
        output.push_str("?: ");
        output.push_str(&field.annotation);
        output.push_str(";\n");
    }
    output.push_str("}\n\n");
    output.push_str("export const ");
    output.push_str(&model.name);
    output.push_str(" = {\n");
    output.push_str("  fromProto(\n");
    output.push_str("    proto: any,\n");
    output.push_str("  ): ");
    output.push_str(&model.name);
    output.push_str(" | undefined {\n");
    output.push_str("    if (proto == null) {\n");
    output.push_str("      return undefined;\n");
    output.push_str("    }\n");
    if model.fields.is_empty() {
        output.push_str("    return {};\n");
    } else {
        output.push_str("    return {\n");
        for field in &model.fields {
            output.push_str("      ");
            output.push_str(&field.name);
            output.push_str(": ");
            output.push_str(&field.from_proto_expr);
            output.push_str(",\n");
        }
        output.push_str("    };\n");
    }
    output.push_str("  },\n\n");
    output.push_str("  toProto(\n");
    output.push_str("    model: ");
    output.push_str(&model.name);
    output.push_str(" | null | undefined,\n");
    output.push_str("  ): any {\n");
    output.push_str("    if (model == null) {\n");
    output.push_str("      return undefined;\n");
    output.push_str("    }\n");
    if model.fields.is_empty() {
        output.push_str("    return {};\n");
    } else {
        output.push_str("    return {\n");
        for field in &model.fields {
            output.push_str("      ");
            output.push_str(&field.name);
            output.push_str(": ");
            output.push_str(&field.to_proto_expr);
            output.push_str(",\n");
        }
        output.push_str("    };\n");
    }
    output.push_str("  },\n");
    output.push_str("};\n");
}

fn render_api_options_type(output: &mut String, name: &str, api: &RenderedApi) {
    output.push_str("export interface ");
    output.push_str(name);
    output.push_str(" {\n");
    for parameter in api
        .parameters
        .iter()
        .filter(|parameter| !parameter.positional)
    {
        output.push_str("  ");
        output.push_str(&parameter.name);
        if parameter.default_expr.is_some() {
            output.push('?');
        }
        output.push_str(": ");
        output.push_str(&optional_property_annotation(&parameter.annotation));
        output.push_str(";\n");
    }
    output.push_str("}\n");
}

fn optional_property_annotation(annotation: &str) -> String {
    annotation
        .strip_suffix(" | undefined")
        .unwrap_or(annotation)
        .to_string()
}

fn render_service(output: &mut String, service: &RenderedService<'_>) {
    output.push_str("export const ");
    output.push_str(service.name);
    output.push_str(" = nexus.service('");
    output.push_str(service.name);
    output.push_str("', {\n");
    for operation in &service.operations {
        output.push_str("  ");
        output.push_str(&operation.attr_name);
        output.push_str(": nexus.operation<\n");
        output.push_str("    ");
        output.push_str(&operation.input_proto_ref);
        output.push_str(",\n");
        output.push_str("    ");
        output.push_str(&operation.output_proto_ref);
        output.push('\n');
        output.push_str("  >({ name: ");
        output.push_str(&typescript_string_literal(operation.name));
        output.push_str(" }),\n");
    }
    output.push_str("});\n\n");

    output.push_str("export class ");
    output.push_str(&service.client_name);
    output.push_str(" {\n");
    output.push_str("  private readonly client: workflow.NexusServiceClient<typeof ");
    output.push_str(service.name);
    output.push_str(">;\n\n");
    output.push_str("  public constructor() {\n");
    output.push_str("    this.client = workflow.createNexusServiceClient({\n");
    output.push_str("      service: ");
    output.push_str(service.name);
    output.push_str(",\n");
    output.push_str("      endpoint: ");
    output.push_str(&typescript_string_literal(&service.endpoint));
    output.push_str(",\n");
    output.push_str("    });\n");
    output.push_str("  }\n");

    for operation in &service.operations {
        output.push('\n');
        render_operation_client_methods(output, service.name, operation);
    }

    for api in &service.apis {
        output.push('\n');
        render_api_client_method(output, api);
    }

    output.push_str("}\n");
}

fn render_operation_client_methods(
    output: &mut String,
    service_name: &str,
    operation: &RenderedOperation<'_>,
) {
    output.push_str("  public async ");
    output.push_str(&operation.attr_name);
    output.push_str("(\n");
    output.push_str("    request: ");
    output.push_str(&operation.input_model_name);
    output.push_str(",\n");
    output.push_str("  ): Promise<workflow.NexusOperationHandle<");
    output.push_str(&operation.output_proto_ref);
    output.push_str(">> {\n");
    output.push_str("    return await this.client.startOperation(\n");
    output.push_str("      ");
    output.push_str(service_name);
    output.push_str(".operations.");
    output.push_str(&operation.attr_name);
    output.push_str(",\n");
    output.push_str("      ");
    output.push_str(&operation.input_model_name);
    output.push_str(".toProto(request) ?? {},\n");
    output.push_str("    );\n");
    output.push_str("  }\n");
}

fn render_api_client_method(output: &mut String, api: &RenderedApi) {
    let positional_parameters = api
        .parameters
        .iter()
        .filter(|parameter| parameter.positional)
        .collect::<Vec<_>>();
    let option_parameters = api
        .parameters
        .iter()
        .filter(|parameter| !parameter.positional)
        .collect::<Vec<_>>();

    output.push_str("  public async ");
    output.push_str(&api.attr_name);
    output.push_str("(\n");
    for parameter in &positional_parameters {
        output.push_str("    ");
        output.push_str(&parameter.local_name);
        output.push_str(": ");
        output.push_str(&parameter.annotation);
        if let Some(default_expr) = &parameter.default_expr {
            output.push_str(" = ");
            output.push_str(default_expr);
        }
        output.push_str(",\n");
    }
    if let Some(options_type_name) = &api.options_type_name {
        output.push_str("    options: ");
        output.push_str(options_type_name);
        if option_parameters
            .iter()
            .all(|parameter| parameter.default_expr.is_some())
        {
            output.push_str(" = {}");
        }
        output.push_str(",\n");
    }
    output.push_str("  ): Promise<");
    output.push_str(&api.output_ref);
    output.push_str("> {\n");

    if !option_parameters.is_empty() {
        output.push_str("    const {\n");
        for parameter in &option_parameters {
            output.push_str("      ");
            output.push_str(&parameter.name);
            if parameter.local_name != parameter.name {
                output.push_str(": ");
                output.push_str(&parameter.local_name);
            }
            if let Some(default_expr) = parameter
                .default_expr
                .as_deref()
                .filter(|default_expr| *default_expr != "undefined")
            {
                output.push_str(" = ");
                output.push_str(default_expr);
            }
            output.push_str(",\n");
        }
        output.push_str("    } = options;\n");
    }

    render_api_request(output, &api.request_strategy, &api.parameters);
    output.push_str("    const handle = await this.");
    output.push_str(&api.operation_attr_name);
    output.push_str("(request);\n");
    output.push_str("    const responseProto = await handle.result();\n");
    output.push_str("    const response = ");
    output.push_str(&api.operation_output_model_name);
    output.push_str(".fromProto(responseProto) ?? {};\n");
    render_api_response(output, &api.response_strategy);
    output.push_str("  }\n");
}

fn render_api_request(
    output: &mut String,
    strategy: &RenderedApiRequestStrategy,
    parameters: &[RenderedApiParameter],
) {
    match strategy {
        RenderedApiRequestStrategy::Converter(converter) => {
            output.push_str("    const request = ");
            output.push_str(converter);
            output.push_str("({\n");
            for parameter in parameters {
                output.push_str("      ");
                output.push_str(&parameter.name);
                output.push_str(": ");
                output.push_str(&parameter.local_name);
                output.push_str(",\n");
            }
            output.push_str("    });\n");
        }
        RenderedApiRequestStrategy::SinglePropertyConverter {
            parameter_name,
            converter,
        } => {
            output.push_str("    const request = ");
            output.push_str(converter);
            output.push('(');
            output.push_str(parameter_name);
            output.push_str(") ?? {};\n");
        }
        RenderedApiRequestStrategy::ModelConstructor { model_name, fields } => {
            output.push_str("    const request: ");
            output.push_str(model_name);
            output.push_str(" = {\n");
            for field in fields {
                output.push_str("      ");
                output.push_str(&field.field_name);
                output.push_str(": ");
                if let Some(converter) = &field.converter {
                    output.push_str(converter);
                    output.push('(');
                    output.push_str(&field.parameter_name);
                    output.push(')');
                } else {
                    output.push_str(&field.parameter_name);
                }
                output.push_str(",\n");
            }
            output.push_str("    };\n");
        }
    }
}

fn render_api_response(output: &mut String, strategy: &RenderedApiResponseStrategy) {
    match strategy {
        RenderedApiResponseStrategy::Converter(converter) => {
            output.push_str("    return ");
            output.push_str(converter);
            output.push_str("({ request, response });\n");
        }
        RenderedApiResponseStrategy::SinglePropertyConverter(converter) => {
            output.push_str("    return ");
            output.push_str(converter);
            output.push_str("(response);\n");
        }
    }
}

fn typescript_field_name(field: &FieldDescriptorProto) -> String {
    let json_name = field
        .json_name
        .as_deref()
        .or_else(|| field.name.as_deref())
        .expect("descriptor fields should be named");
    typescript_ident(json_name)
}

fn typescript_ident(name: &str) -> String {
    if is_typescript_keyword(name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

fn typescript_local_ident(name: &str) -> String {
    let ident = typescript_ident(name);
    if matches!(
        ident.as_str(),
        "common" | "google" | "nexus" | "temporal" | "workflow"
    ) {
        format!("{ident}_")
    } else {
        ident
    }
}

fn typescript_string_literal(value: &str) -> String {
    format!("{value:?}")
}

fn is_typescript_keyword(name: &str) -> bool {
    matches!(
        name,
        "break"
            | "case"
            | "catch"
            | "class"
            | "const"
            | "continue"
            | "debugger"
            | "default"
            | "delete"
            | "do"
            | "else"
            | "enum"
            | "export"
            | "extends"
            | "false"
            | "finally"
            | "for"
            | "function"
            | "if"
            | "import"
            | "in"
            | "instanceof"
            | "new"
            | "null"
            | "return"
            | "super"
            | "switch"
            | "this"
            | "throw"
            | "true"
            | "try"
            | "typeof"
            | "var"
            | "void"
            | "while"
            | "with"
            | "yield"
            | "as"
            | "implements"
            | "interface"
            | "let"
            | "package"
            | "private"
            | "protected"
            | "public"
            | "static"
    )
}
