// Generated by nex-gen. DO NOT EDIT!

package com.example.chat;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/** A chat message. */
@NullMarked
@JsonDeserialize(using = Message.Deserializer.class)
@JsonSerialize(using = Message.Serializer.class)
public final class Message {
  /**
   * Open value class for the discriminator (const "text"). Any wire value is
   * representable for forward compatibility; the validator rejects anything but
   * {@link #TEXT} because a const is a closed contract.
   */
  public static final class Kind {
    public static final Kind TEXT = new Kind("text");

    private final String value;

    private Kind(String value) {
      this.value = value;
    }

    @JsonCreator
    public static @Nullable Kind fromString(@Nullable String v) {
      if (v == null) {
        return null;
      }
      if (v.equals("text")) {
        return TEXT;
      }
      return new Kind(v);
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    public boolean isUnrecognized() {
      return this != TEXT;
    }

    @Override
    public boolean equals(@Nullable Object o) {
      return o instanceof Kind && value.equals(((Kind) o).value);
    }

    @Override
    public int hashCode() {
      return value.hashCode();
    }

    @Override
    public String toString() {
      return value;
    }
  }

  private final Kind kind = Kind.TEXT;
  private final String body;
  private final @Nullable String replyToId;
  private final @Nullable Long priority;

  public Message(String body, @Nullable String replyToId, @Nullable Long priority) {
    this.body = body;
    this.replyToId = replyToId;
    this.priority = priority;
  }

  /** Discriminator; always "text". */
  public Kind getKind() {
    return kind;
  }

  public String getBody() {
    return body;
  }

  /** Id of the message this replies to, if any. */
  public @Nullable String getReplyToId() {
    return replyToId;
  }

  /** Delivery priority. */
  public long getPriority() {
    return priority != null ? priority : 0L;
  }

  public static final class Deserializer extends JsonDeserializer<Message> {
    @Override
    public Message deserialize(JsonParser p, DeserializationContext ctx) throws IOException {
      JsonNode root = p.readValueAsTree();
      List<Violation> errs = new ArrayList<>();

      JsonNode kindNode = root.get("kind");
      if (kindNode == null || kindNode.isNull()) {
        errs.add(new Violation("kind", "required"));
      } else if (!kindNode.isTextual()) {
        errs.add(new Violation("kind", "expected string"));
      } else {
        Kind k = Kind.fromString(kindNode.asText());
        if (k == null || k.isUnrecognized()) {
          errs.add(new Violation("kind", "const: expected \"text\""));
        }
      }

      String body = null;
      JsonNode bodyNode = root.get("body");
      if (bodyNode == null || bodyNode.isNull()) {
        errs.add(new Violation("body", "required"));
      } else if (!bodyNode.isTextual()) {
        errs.add(new Violation("body", "expected string"));
      } else {
        body = bodyNode.asText();
      }

      String replyToId = null;
      JsonNode replyToIdNode = root.get("replyToId");
      if (replyToIdNode != null && !replyToIdNode.isNull()) {
        if (!replyToIdNode.isTextual()) {
          errs.add(new Violation("replyToId", "expected string"));
        } else {
          replyToId = replyToIdNode.asText();
        }
      }

      Long priority = null;
      JsonNode priorityNode = root.get("priority");
      if (priorityNode != null) {
        if (priorityNode.isNull()) {
          errs.add(new Violation("priority", "explicit null not allowed"));
        } else {
          priority = SpecNumbers.specLong(priorityNode, "priority", errs);
        }
      }

      Iterator<String> keyIt = root.fieldNames();
      while (keyIt.hasNext()) {
        String key = keyIt.next();
        if (!key.equals("kind") && !key.equals("body") && !key.equals("replyToId") && !key.equals("priority")) {
          errs.add(new Violation(key, "unknown field"));
        }
      }

      if (!errs.isEmpty()) {
        throw new ValidationException(p, errs);
      }
      return new Message(Objects.requireNonNull(body), replyToId, priority);
    }
  }

  public static final class Serializer extends JsonSerializer<Message> {
    @Override
    public void serialize(Message v, JsonGenerator gen, SerializerProvider sp) throws IOException {
      List<Violation> errs = new ArrayList<>();
      if (v.body == null) {
        errs.add(new Violation("body", "required"));
      }
      if (!errs.isEmpty()) {
        throw new ValidationException(null, errs);
      }

      gen.writeStartObject();
      gen.writeStringField("kind", v.kind.getValue());
      gen.writeStringField("body", v.body);
      if (v.replyToId != null) {
        gen.writeStringField("replyToId", v.replyToId);
      }
      if (v.priority != null) {
        gen.writeNumberField("priority", v.priority);
      }
      gen.writeEndObject();
    }
  }
}
