// Generated by nex-gen. DO NOT EDIT!

package com.example.chat;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/** Request to post a message. */
@NullMarked
@JsonDeserialize(using = SendMessageInput.Deserializer.class)
@JsonSerialize(using = SendMessageInput.Serializer.class)
public final class SendMessageInput {
  private final String roomId;
  private final Message message;

  public SendMessageInput(String roomId, Message message) {
    this.roomId = roomId;
    this.message = message;
  }

  public String getRoomId() {
    return roomId;
  }

  public Message getMessage() {
    return message;
  }

  public static final class Deserializer extends JsonDeserializer<SendMessageInput> {
    @Override
    public SendMessageInput deserialize(JsonParser p, DeserializationContext ctx) throws IOException {
      JsonNode root = p.readValueAsTree();
      List<Violation> errs = new ArrayList<>();

      String roomId = null;
      JsonNode roomIdNode = root.get("roomId");
      if (roomIdNode == null || roomIdNode.isNull()) {
        errs.add(new Violation("roomId", "required"));
      } else if (!roomIdNode.isTextual()) {
        errs.add(new Violation("roomId", "expected string"));
      } else {
        roomId = roomIdNode.asText();
      }

      Message message = null;
      JsonNode messageNode = root.get("message");
      if (messageNode == null || messageNode.isNull()) {
        errs.add(new Violation("message", "required"));
      } else {
        try {
          message = ctx.readTreeAsValue(messageNode, Message.class);
        } catch (ValidationException nested) {
          for (Violation v : nested.getViolations()) {
            errs.add(new Violation("message." + v.getPath(), v.getReason()));
          }
        }
      }

      Iterator<String> keyIt = root.fieldNames();
      while (keyIt.hasNext()) {
        String key = keyIt.next();
        if (!key.equals("roomId") && !key.equals("message")) {
          errs.add(new Violation(key, "unknown field"));
        }
      }

      if (!errs.isEmpty()) {
        throw new ValidationException(p, errs);
      }
      return new SendMessageInput(Objects.requireNonNull(roomId), Objects.requireNonNull(message));
    }
  }

  public static final class Serializer extends JsonSerializer<SendMessageInput> {
    @Override
    public void serialize(SendMessageInput v, JsonGenerator gen, SerializerProvider sp) throws IOException {
      List<Violation> errs = new ArrayList<>();
      if (v.roomId == null) {
        errs.add(new Violation("roomId", "required"));
      }
      if (v.message == null) {
        errs.add(new Violation("message", "required"));
      }
      if (!errs.isEmpty()) {
        throw new ValidationException(null, errs);
      }

      gen.writeStartObject();
      gen.writeStringField("roomId", v.roomId);
        gen.writeFieldName("message");
        sp.defaultSerializeValue(v.message, gen);
      gen.writeEndObject();
    }
  }
}
