# Generated by nexus-api-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

from temporalio import workflow

from ..models import GetUserRequest
from .._resources import User


async def _get_user(
    request: GetUserRequest,
) -> User:
    nexus_client = workflow.create_nexus_client(
        service="TypeShowcase",
        endpoint="type-showcase",
    )
    handle = await nexus_client.start_operation(
        operation="GetUser",
        input=request,
        output_type=User,
    )
    return await handle


async def get_user(
    *,
    consistency_token: str | None = None,
    user_id: str,
) -> User:
    request = GetUserRequest(
        consistency_token=consistency_token,
        user_id=user_id,
    )
    return await _get_user(request)
