# Generated by nexus-api-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

from temporalio import workflow

from ..models import (
    SetProfileRequest,
    UserProfile,
)
from .._resources import User


async def _set_profile(
    request: SetProfileRequest,
) -> User:
    nexus_client = workflow.create_nexus_client(
        service="TypeShowcase",
        endpoint="type-showcase",
    )
    handle = await nexus_client.start_operation(
        operation="SetProfile",
        input=request,
        output_type=User,
    )
    return await handle


async def set_profile(
    *,
    profile: UserProfile,
    user_id: str,
) -> User:
    request = SetProfileRequest(
        profile=profile,
        user_id=user_id,
    )
    return await _set_profile(request)
