# Generated by nexus-api-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

from datetime import timedelta
import temporalio.common
from temporalio import workflow
import temporalio.api.activity.v1.message_pb2

from ..service import WorkflowService
from ..models import ActivityOptions


async def _activity_options_operation(
    request: ActivityOptions,
) -> workflow.NexusOperationHandle[
    temporalio.api.activity.v1.message_pb2.ActivityOptions,
]:
    nexus_client: workflow.NexusClient[WorkflowService] = workflow.create_nexus_client(
        service=WorkflowService,
        endpoint="__temporal_system",
    )
    return await nexus_client.start_operation(
        WorkflowService.activity_options_operation,
        request.to_proto(),
    )


async def activity_options_operation(
    *,
    task_queue: str | None = None,
    schedule_to_close_timeout: timedelta | None = None,
    retry_policy: temporalio.common.RetryPolicy,
    priority: temporalio.common.Priority | None = None,
) -> workflow.NexusOperationHandle[
    temporalio.api.activity.v1.message_pb2.ActivityOptions,
]:
    request = ActivityOptions(
        task_queue=task_queue,
        schedule_to_close_timeout=schedule_to_close_timeout,
        retry_policy=retry_policy,
        priority=priority,
    )
    return await _activity_options_operation(request)
