# Generated by nexus-api-gen. DO NOT EDIT!
# pyright: reportAny=false

from __future__ import annotations

import collections.abc
import typing
import typing_extensions
from datetime import timedelta
import temporalio.common
from temporalio import workflow

from ..service import WorkflowService
from ..models import (
    SignalWithStartWorkflowExecutionRequest,
    UserMetadata,
)


def _nexus_normalize_function_args(
    value: object | tuple[object, ...] | None,
) -> tuple[object, ...] | None:
    if value is None:
        return None
    if isinstance(value, tuple):
        return typing.cast(tuple[object, ...], value)
    return (value,)


FirstWorkflowArg = typing.TypeVar("FirstWorkflowArg")
SignalArg1 = typing.TypeVar("SignalArg1")
SignalArg2 = typing.TypeVar("SignalArg2")
SignalArg3 = typing.TypeVar("SignalArg3")
SignalArg4 = typing.TypeVar("SignalArg4")
SignalArg5 = typing.TypeVar("SignalArg5")
SignalArg6 = typing.TypeVar("SignalArg6")
RemainingWorkflowArgs = typing_extensions.TypeVarTuple("RemainingWorkflowArgs")


async def _signal_with_start_workflow_execution(
    request: SignalWithStartWorkflowExecutionRequest,
) -> workflow.ExternalWorkflowHandle[typing.Any]:
    request_proto = request.to_proto()
    nexus_client: workflow.NexusClient[WorkflowService] = workflow.create_nexus_client(
        service=WorkflowService,
        endpoint="__temporal_system",
    )
    handle = await nexus_client.start_operation(
        WorkflowService.signal_with_start_workflow_execution,
        request_proto,
    )
    result = await handle
    return workflow.get_external_workflow_handle(
        request.workflow_id, run_id=result.run_id
    )


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: str,
    task_queue: str,
    input: tuple[typing.Any, ...] | None = ...,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: str,
    signal_input: tuple[typing.Any, ...] | None = ...,
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[[typing.Any], collections.abc.Awaitable[object]],
    task_queue: str,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: str,
    signal_input: tuple[typing.Any, ...] | None = ...,
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg], collections.abc.Awaitable[object]
    ],
    task_queue: str,
    input: FirstWorkflowArg,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: str,
    signal_input: tuple[typing.Any, ...] | None = ...,
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
        collections.abc.Awaitable[object],
    ],
    task_queue: str,
    input: tuple[FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: str,
    signal_input: tuple[typing.Any, ...] | None = ...,
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: str,
    task_queue: str,
    input: tuple[typing.Any, ...] | None = ...,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any], None | collections.abc.Awaitable[None]
    ],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[[typing.Any], collections.abc.Awaitable[object]],
    task_queue: str,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any], None | collections.abc.Awaitable[None]
    ],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg], collections.abc.Awaitable[object]
    ],
    task_queue: str,
    input: FirstWorkflowArg,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any], None | collections.abc.Awaitable[None]
    ],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
        collections.abc.Awaitable[object],
    ],
    task_queue: str,
    input: tuple[FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any], None | collections.abc.Awaitable[None]
    ],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: str,
    task_queue: str,
    input: tuple[typing.Any, ...] | None = ...,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1], None | collections.abc.Awaitable[None]
    ],
    signal_input: SignalArg1,
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[[typing.Any], collections.abc.Awaitable[object]],
    task_queue: str,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1], None | collections.abc.Awaitable[None]
    ],
    signal_input: SignalArg1,
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg], collections.abc.Awaitable[object]
    ],
    task_queue: str,
    input: FirstWorkflowArg,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1], None | collections.abc.Awaitable[None]
    ],
    signal_input: SignalArg1,
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
        collections.abc.Awaitable[object],
    ],
    task_queue: str,
    input: tuple[FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1], None | collections.abc.Awaitable[None]
    ],
    signal_input: SignalArg1,
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: str,
    task_queue: str,
    input: tuple[typing.Any, ...] | None = ...,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1], None | collections.abc.Awaitable[None]
    ],
    signal_input: tuple[SignalArg1],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[[typing.Any], collections.abc.Awaitable[object]],
    task_queue: str,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1], None | collections.abc.Awaitable[None]
    ],
    signal_input: tuple[SignalArg1],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg], collections.abc.Awaitable[object]
    ],
    task_queue: str,
    input: FirstWorkflowArg,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1], None | collections.abc.Awaitable[None]
    ],
    signal_input: tuple[SignalArg1],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
        collections.abc.Awaitable[object],
    ],
    task_queue: str,
    input: tuple[FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1], None | collections.abc.Awaitable[None]
    ],
    signal_input: tuple[SignalArg1],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: str,
    task_queue: str,
    input: tuple[typing.Any, ...] | None = ...,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2], None | collections.abc.Awaitable[None]
    ],
    signal_input: tuple[SignalArg1, SignalArg2],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[[typing.Any], collections.abc.Awaitable[object]],
    task_queue: str,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2], None | collections.abc.Awaitable[None]
    ],
    signal_input: tuple[SignalArg1, SignalArg2],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg], collections.abc.Awaitable[object]
    ],
    task_queue: str,
    input: FirstWorkflowArg,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2], None | collections.abc.Awaitable[None]
    ],
    signal_input: tuple[SignalArg1, SignalArg2],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
        collections.abc.Awaitable[object],
    ],
    task_queue: str,
    input: tuple[FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2], None | collections.abc.Awaitable[None]
    ],
    signal_input: tuple[SignalArg1, SignalArg2],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: str,
    task_queue: str,
    input: tuple[typing.Any, ...] | None = ...,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2, SignalArg3],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[SignalArg1, SignalArg2, SignalArg3],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[[typing.Any], collections.abc.Awaitable[object]],
    task_queue: str,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2, SignalArg3],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[SignalArg1, SignalArg2, SignalArg3],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg], collections.abc.Awaitable[object]
    ],
    task_queue: str,
    input: FirstWorkflowArg,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2, SignalArg3],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[SignalArg1, SignalArg2, SignalArg3],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
        collections.abc.Awaitable[object],
    ],
    task_queue: str,
    input: tuple[FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2, SignalArg3],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[SignalArg1, SignalArg2, SignalArg3],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: str,
    task_queue: str,
    input: tuple[typing.Any, ...] | None = ...,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2, SignalArg3, SignalArg4],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[SignalArg1, SignalArg2, SignalArg3, SignalArg4],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[[typing.Any], collections.abc.Awaitable[object]],
    task_queue: str,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2, SignalArg3, SignalArg4],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[SignalArg1, SignalArg2, SignalArg3, SignalArg4],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg], collections.abc.Awaitable[object]
    ],
    task_queue: str,
    input: FirstWorkflowArg,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2, SignalArg3, SignalArg4],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[SignalArg1, SignalArg2, SignalArg3, SignalArg4],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
        collections.abc.Awaitable[object],
    ],
    task_queue: str,
    input: tuple[FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2, SignalArg3, SignalArg4],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[SignalArg1, SignalArg2, SignalArg3, SignalArg4],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: str,
    task_queue: str,
    input: tuple[typing.Any, ...] | None = ...,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2, SignalArg3, SignalArg4, SignalArg5],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[SignalArg1, SignalArg2, SignalArg3, SignalArg4, SignalArg5],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[[typing.Any], collections.abc.Awaitable[object]],
    task_queue: str,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2, SignalArg3, SignalArg4, SignalArg5],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[SignalArg1, SignalArg2, SignalArg3, SignalArg4, SignalArg5],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg], collections.abc.Awaitable[object]
    ],
    task_queue: str,
    input: FirstWorkflowArg,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2, SignalArg3, SignalArg4, SignalArg5],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[SignalArg1, SignalArg2, SignalArg3, SignalArg4, SignalArg5],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
        collections.abc.Awaitable[object],
    ],
    task_queue: str,
    input: tuple[FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [typing.Any, SignalArg1, SignalArg2, SignalArg3, SignalArg4, SignalArg5],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[SignalArg1, SignalArg2, SignalArg3, SignalArg4, SignalArg5],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: str,
    task_queue: str,
    input: tuple[typing.Any, ...] | None = ...,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [
            typing.Any,
            SignalArg1,
            SignalArg2,
            SignalArg3,
            SignalArg4,
            SignalArg5,
            SignalArg6,
        ],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[
        SignalArg1, SignalArg2, SignalArg3, SignalArg4, SignalArg5, SignalArg6
    ],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[[typing.Any], collections.abc.Awaitable[object]],
    task_queue: str,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [
            typing.Any,
            SignalArg1,
            SignalArg2,
            SignalArg3,
            SignalArg4,
            SignalArg5,
            SignalArg6,
        ],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[
        SignalArg1, SignalArg2, SignalArg3, SignalArg4, SignalArg5, SignalArg6
    ],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg], collections.abc.Awaitable[object]
    ],
    task_queue: str,
    input: FirstWorkflowArg,
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [
            typing.Any,
            SignalArg1,
            SignalArg2,
            SignalArg3,
            SignalArg4,
            SignalArg5,
            SignalArg6,
        ],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[
        SignalArg1, SignalArg2, SignalArg3, SignalArg4, SignalArg5, SignalArg6
    ],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


@typing.overload
async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: collections.abc.Callable[
        [typing.Any, FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
        collections.abc.Awaitable[object],
    ],
    task_queue: str,
    input: tuple[FirstWorkflowArg, typing_extensions.Unpack[RemainingWorkflowArgs]],
    workflow_execution_timeout: timedelta | None = ...,
    workflow_run_timeout: timedelta | None = ...,
    workflow_task_timeout: timedelta | None = ...,
    identity: str | None = ...,
    request_id: str | None = ...,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = ...,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = ...,
    signal: collections.abc.Callable[
        [
            typing.Any,
            SignalArg1,
            SignalArg2,
            SignalArg3,
            SignalArg4,
            SignalArg5,
            SignalArg6,
        ],
        None | collections.abc.Awaitable[None],
    ],
    signal_input: tuple[
        SignalArg1, SignalArg2, SignalArg3, SignalArg4, SignalArg5, SignalArg6
    ],
    retry_policy: temporalio.common.RetryPolicy | None = ...,
    cron_schedule: str | None = ...,
    memo: collections.abc.Mapping[str, typing.Any] | None = ...,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = ...,
    static_summary: str | None = ...,
    static_details: str | None = ...,
    versioning_override: temporalio.common.VersioningOverride | None = ...,
    priority: temporalio.common.Priority | None = ...,
) -> workflow.ExternalWorkflowHandle[typing.Any]: ...


async def signal_with_start_workflow_execution(
    *,
    workflow_id: str,
    workflow: str | collections.abc.Callable[..., collections.abc.Awaitable[object]],
    task_queue: str,
    input: object | tuple[object, ...] | None = None,
    workflow_execution_timeout: timedelta | None = None,
    workflow_run_timeout: timedelta | None = None,
    workflow_task_timeout: timedelta | None = None,
    identity: str | None = None,
    request_id: str | None = None,
    workflow_id_reuse_policy: temporalio.common.WorkflowIDReusePolicy | None = None,
    workflow_id_conflict_policy: temporalio.common.WorkflowIDConflictPolicy
    | None = None,
    signal: str | collections.abc.Callable[..., None | collections.abc.Awaitable[None]],
    signal_input: object | tuple[object, ...] | None = None,
    retry_policy: temporalio.common.RetryPolicy | None = None,
    cron_schedule: str | None = None,
    memo: collections.abc.Mapping[str, typing.Any] | None = None,
    search_attributes: temporalio.common.TypedSearchAttributes
    | temporalio.common.SearchAttributes
    | None = None,
    static_summary: str | None = None,
    static_details: str | None = None,
    versioning_override: temporalio.common.VersioningOverride | None = None,
    priority: temporalio.common.Priority | None = None,
) -> workflow.ExternalWorkflowHandle[typing.Any]:
    normalized_signal_input = _nexus_normalize_function_args(signal_input)
    normalized_input = _nexus_normalize_function_args(input)
    user_metadata = (
        None
        if static_summary is None and static_details is None
        else UserMetadata(
            static_summary=static_summary,
            static_details=static_details,
        )
    )
    request = SignalWithStartWorkflowExecutionRequest(
        workflow_id=workflow_id,
        workflow=workflow,
        task_queue=task_queue,
        input=normalized_input,
        workflow_execution_timeout=workflow_execution_timeout,
        workflow_run_timeout=workflow_run_timeout,
        workflow_task_timeout=workflow_task_timeout,
        identity=identity,
        request_id=request_id,
        workflow_id_reuse_policy=workflow_id_reuse_policy,
        workflow_id_conflict_policy=workflow_id_conflict_policy,
        signal=signal,
        signal_input=normalized_signal_input,
        retry_policy=retry_policy,
        cron_schedule=cron_schedule,
        memo=memo,
        search_attributes=search_attributes,
        user_metadata=user_metadata,
        versioning_override=versioning_override,
        priority=priority,
    )
    return await _signal_with_start_workflow_execution(request)
